// ──────────────────────────────────────────────────────────────
// PiBridge Academy — Mock Data for MVP
// ──────────────────────────────────────────────────────────────

import type {
  Programme,
  Course,
  LearnerProfile,
  InstructorProfile,
  Enrollment,
  LearningProgress,
  Certificate,
} from "./types";
import { ALL_COURSE_MODULES } from "./courseContent";
import { EXPANDED_COURSE_MODULES } from "./expandedCourseContent";
import { ALL_NEW_PROGRAMMES, ALL_NEW_COURSES } from "./expandedProgrammes";

// ── Programmes ──
export const PROGRAMMES: Programme[] = [
  {
    id: "prog-cyber",
    title: "Cybersecurity Professional Path",
    slug: "cybersecurity",
    description:
      "From IT fundamentals to SOC Analyst — learn to protect organizations from cyber threats.",
    longDescription:
      "The Cybersecurity Professional Path takes you from zero experience to job-ready SOC Analyst. You'll master networking, Linux, security fundamentals, SIEM tools, incident response, and threat analysis through hands-on labs and real-world scenarios. Graduate with a Professional Passport that proves you can do the work.",
    level: "foundation",
    domain: "cybersecurity",
    icon: "🛡️",
    color: "red",
    image: "https://images.unsplash.com/photo-1550751827-4bd374c3f58b?w=800&q=80",
    durationWeeks: 24,
    totalHours: 360,
    priceGHS: 5500,
    currency: "GHS",
    prerequisites: ["Basic computer literacy", "High school diploma or equivalent"],
    outcomes: [
      "Configure and manage Linux systems",
      "Analyze network traffic and identify threats",
      "Operate SIEM platforms (Splunk, ELK)",
      "Respond to security incidents",
      "Build a SOC analyst portfolio",
      "Earn a Professional Passport credential",
    ],
    enrolledCount: 247,
    rating: 4.8,
    reviewCount: 89,
    status: "published",
    featured: true,
    courses: ["course-net-fundamentals", "course-linux-fundamentals", "course-cyber-fundamentals", "course-soc-operations"],
    createdAt: "2026-06-01",
    updatedAt: "2026-08-15",
  },
  {
    id: "prog-software",
    title: "Software Engineering Professional Path",
    slug: "software-engineering",
    description:
      "Build real applications from scratch — frontend, backend, databases, and deployment.",
    longDescription:
      "The Software Engineering path builds practical, production-ready development skills. You'll learn JavaScript/TypeScript, React, Node.js, databases, APIs, testing, and deployment. Every module includes hands-on projects that become your portfolio. Graduate ready to join a dev team or build your own products.",
    level: "foundation",
    domain: "software_engineering",
    icon: "💻",
    color: "blue",
    image: "https://images.unsplash.com/photo-1461749280684-dccba630e2f6?w=800&q=80",
    durationWeeks: 20,
    totalHours: 300,
    priceGHS: 4800,
    currency: "GHS",
    prerequisites: ["Basic computer literacy", "Logical thinking"],
    outcomes: [
      "Build full-stack web applications with React and Node.js",
      "Design and query SQL and NoSQL databases",
      "Write clean, tested, maintainable code",
      "Deploy applications to cloud platforms",
      "Use Git and collaborative development workflows",
      "Build a professional developer portfolio",
    ],
    enrolledCount: 312,
    rating: 4.7,
    reviewCount: 124,
    status: "published",
    featured: true,
    courses: ["course-web-fundamentals", "course-react-frontend", "course-node-backend", "course-fullstack-project"],
    createdAt: "2026-06-01",
    updatedAt: "2026-08-20",
  },
  {
    id: "prog-cloud",
    title: "Cloud & Infrastructure Professional Path",
    slug: "cloud-infrastructure",
    description:
      "Master cloud platforms, infrastructure as code, and DevOps practices.",
    longDescription:
      "The Cloud & Infrastructure path prepares you for the modern IT landscape. You'll learn cloud platforms (AWS, Azure, GCP), infrastructure as code (Terraform), containerization (Docker, Kubernetes), CI/CD pipelines, and monitoring. Graduate with the skills to design, deploy, and manage scalable cloud infrastructure.",
    level: "foundation",
    domain: "cloud_infrastructure",
    icon: "☁️",
    color: "amber",
    image: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=800&q=80",
    durationWeeks: 20,
    totalHours: 280,
    priceGHS: 5000,
    currency: "GHS",
    prerequisites: ["Basic networking concepts", "Command line familiarity"],
    outcomes: [
      "Deploy and manage resources on AWS, Azure, or GCP",
      "Write infrastructure as code with Terraform",
      "Containerize applications with Docker",
      "Orchestrate services with Kubernetes",
      "Build CI/CD pipelines for automated deployment",
      "Monitor and troubleshoot cloud infrastructure",
    ],
    enrolledCount: 183,
    rating: 4.9,
    reviewCount: 67,
    status: "published",
    featured: true,
    courses: ["course-cloud-foundations", "course-terraform", "course-containers", "course-devops-pipeline"],
    createdAt: "2026-06-01",
    updatedAt: "2026-08-10",
  },
];

// ── Courses ──
export const COURSES: Course[] = [
  // ── Cybersecurity Path ──
  {
    id: "course-net-fundamentals",
    programmeId: "prog-cyber",
    title: "Networking Fundamentals",
    slug: "networking-fundamentals",
    description: "Build a solid foundation in networking — the backbone of cybersecurity.",
    objectives: [
      "Understand the OSI and TCP/IP models",
      "Configure routers, switches, and firewalls",
      "Analyze network traffic with Wireshark",
      "Implement basic network security controls",
    ],
    prerequisites: ["Basic computer literacy"],
    level: "foundation",
    durationHours: 60,
    moduleCount: 6,
    totalLessons: 36,
    instructorId: "inst-1",
    instructorName: "Kwame Asante",
    instructorAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=kwame",
    priceGHS: 800,
    enrolledCount: 247,
    rating: 4.8,
    reviewCount: 89,
    status: "published",
    thumbnail: "https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=600&q=80",
    tags: ["networking", "fundamentals", "cybersecurity"],
    modules: [
      {
        id: "mod-nf-1",
        courseId: "course-net-fundamentals",
        title: "Introduction to Networking",
        description: "What networks are, how they work, and why they matter for security.",
        order: 1,
        lessons: [
          { id: "les-nf-1-1", moduleId: "mod-nf-1", title: "What is a Network?", type: "video", durationMinutes: 18, order: 1, isPreview: true },
          { id: "les-nf-1-2", moduleId: "mod-nf-1", title: "Network Topologies", type: "reading", durationMinutes: 12, order: 2, content: "Network topologies define how devices are arranged and communicate. The main types are star, bus, ring, and mesh. In modern networks, the star topology dominates because individual failures don't cascade. Mesh topologies provide redundancy for critical infrastructure.", isPreview: true },
          { id: "les-nf-1-3", moduleId: "mod-nf-1", title: "Networking Basics Quiz", type: "quiz", durationMinutes: 10, order: 3, isPreview: false },
        ],
      },
      {
        id: "mod-nf-2",
        courseId: "course-net-fundamentals",
        title: "The OSI Model",
        description: "Understand the seven-layer model that governs network communication.",
        order: 2,
        lessons: [
          { id: "les-nf-2-1", moduleId: "mod-nf-2", title: "The 7 Layers Explained", type: "video", durationMinutes: 25, order: 1, isPreview: false },
          { id: "les-nf-2-2", moduleId: "mod-nf-2", title: "Data Encapsulation", type: "video", durationMinutes: 20, order: 2, isPreview: false },
          { id: "les-nf-2-3", moduleId: "mod-nf-2", title: "OSI Model Lab", type: "lab", durationMinutes: 30, order: 3, isPreview: false },
          { id: "les-nf-2-4", moduleId: "mod-nf-2", title: "OSI Model Quiz", type: "quiz", durationMinutes: 10, order: 4, isPreview: false },
        ],
      },
      {
        id: "mod-nf-3",
        courseId: "course-net-fundamentals",
        title: "TCP/IP Deep Dive",
        description: "The protocol suite that powers the internet.",
        order: 3,
        lessons: [
          { id: "les-nf-3-1", moduleId: "mod-nf-3", title: "IP Addressing & Subnetting", type: "video", durationMinutes: 30, order: 1, isPreview: false },
          { id: "les-nf-3-2", moduleId: "mod-nf-3", title: "TCP vs UDP", type: "reading", durationMinutes: 15, order: 2, isPreview: false, content: "TCP provides reliable, ordered delivery through handshakes and acknowledgments. UDP trades reliability for speed — critical for VoIP, streaming, and DNS. Security analysts must understand both to detect anomalies." },
          { id: "les-nf-3-3", moduleId: "mod-nf-3", title: "DNS & DHCP", type: "video", durationMinutes: 22, order: 3, isPreview: false },
          { id: "les-nf-3-4", moduleId: "mod-nf-3", title: "Subnetting Practice", type: "assignment", durationMinutes: 45, order: 4, isPreview: false },
        ],
      },
      {
        id: "mod-nf-4",
        courseId: "course-net-fundamentals",
        title: "Network Security Basics",
        description: "Firewalls, IDS/IPS, and securing network traffic.",
        order: 4,
        lessons: [
          { id: "les-nf-4-1", moduleId: "mod-nf-4", title: "Firewalls & ACLs", type: "video", durationMinutes: 20, order: 1, isPreview: false },
          { id: "les-nf-4-2", moduleId: "mod-nf-4", title: "IDS vs IPS", type: "reading", durationMinutes: 12, order: 2, isPreview: false, content: "Intrusion Detection Systems passively monitor traffic and alert on suspicious patterns. Intrusion Prevention Systems actively block detected threats. Both are essential in a layered defense strategy." },
          { id: "les-nf-4-3", moduleId: "mod-nf-4", title: "Firewall Configuration Lab", type: "lab", durationMinutes: 40, order: 3, isPreview: false },
        ],
      },
      {
        id: "mod-nf-5",
        courseId: "course-net-fundamentals",
        title: "Packet Analysis",
        description: "Capture and analyze network traffic with Wireshark.",
        order: 5,
        lessons: [
          { id: "les-nf-5-1", moduleId: "mod-nf-5", title: "Wireshark Fundamentals", type: "video", durationMinutes: 25, order: 1, isPreview: false },
          { id: "les-nf-5-2", moduleId: "mod-nf-5", title: "Reading Packet Captures", type: "reading", durationMinutes: 15, order: 2, isPreview: false, content: "Every packet tells a story. Learn to identify protocol headers, spot anomalies, filter by IP/port, and reconstruct TCP streams. This is the foundational skill of network forensics." },
          { id: "les-nf-5-3", moduleId: "mod-nf-5", title: "Packet Analysis Lab", type: "lab", durationMinutes: 45, order: 3, isPreview: false },
        ],
      },
      {
        id: "mod-nf-6",
        courseId: "course-net-fundamentals",
        title: "Network Security Capstone",
        description: "Apply everything you've learned in a real-world scenario.",
        order: 6,
        lessons: [
          { id: "les-nf-6-1", moduleId: "mod-nf-6", title: "Capstone Project", type: "project", durationMinutes: 180, order: 1, isPreview: false },
          { id: "les-nf-6-2", moduleId: "mod-nf-6", title: "Final Assessment", type: "quiz", durationMinutes: 30, order: 2, isPreview: false },
        ],
      },
    ],
    createdAt: "2026-06-01",
    updatedAt: "2026-08-15",
  },
  {
    id: "course-linux-fundamentals",
    programmeId: "prog-cyber",
    title: "Linux Fundamentals",
    slug: "linux-fundamentals",
    description: "Master the Linux command line — essential for every security professional.",
    objectives: [
      "Navigate the Linux filesystem and manage files",
      "Write shell scripts for automation",
      "Manage users, permissions, and services",
      "Configure networking and troubleshoot issues",
    ],
    prerequisites: ["Networking Fundamentals"],
    level: "foundation",
    durationHours: 50,
    moduleCount: 5,
    totalLessons: 30,
    instructorId: "inst-2",
    instructorName: "Ama Darko",
    instructorAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=ama",
    priceGHS: 700,
    enrolledCount: 231,
    rating: 4.7,
    reviewCount: 78,
    status: "published",
    thumbnail: "https://images.unsplash.com/photo-1629654297299-c8506221ca97?w=600&q=80",
    tags: ["linux", "command-line", "sysadmin"],
    modules: [],
    createdAt: "2026-06-15",
    updatedAt: "2026-08-10",
  },
  {
    id: "course-cyber-fundamentals",
    programmeId: "prog-cyber",
    title: "Cybersecurity Fundamentals",
    slug: "cybersecurity-fundamentals",
    description: "Core security concepts, threat landscape, and defense strategies.",
    objectives: [
      "Identify common attack vectors and threat actors",
      "Implement access control and authentication",
      "Apply cryptography for data protection",
      "Develop a security-first mindset",
    ],
    prerequisites: ["Linux Fundamentals"],
    level: "associate",
    durationHours: 70,
    moduleCount: 7,
    totalLessons: 42,
    instructorId: "inst-1",
    instructorName: "Kwame Asante",
    instructorAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=kwame",
    priceGHS: 1200,
    enrolledCount: 198,
    rating: 4.9,
    reviewCount: 56,
    status: "published",
    thumbnail: "https://images.unsplash.com/photo-1563013544-824ae1b704d3?w=600&q=80",
    tags: ["cybersecurity", "security", "defense"],
    modules: [],
    createdAt: "2026-07-01",
    updatedAt: "2026-08-20",
  },
  {
    id: "course-soc-operations",
    programmeId: "prog-cyber",
    title: "SOC Operations",
    slug: "soc-operations",
    description: "Run a Security Operations Center — monitoring, detection, and response.",
    objectives: [
      "Operate SIEM platforms (Splunk, ELK Stack)",
      "Triage and investigate security alerts",
      "Perform incident response procedures",
      "Write professional incident reports",
    ],
    prerequisites: ["Cybersecurity Fundamentals"],
    level: "professional",
    durationHours: 80,
    moduleCount: 8,
    totalLessons: 48,
    instructorId: "inst-1",
    instructorName: "Kwame Asante",
    instructorAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=kwame",
    priceGHS: 1500,
    enrolledCount: 156,
    rating: 4.8,
    reviewCount: 42,
    status: "published",
    thumbnail: "https://images.unsplash.com/photo-1504639725590-34d0984388bd?w=600&q=80",
    tags: ["soc", "siem", "incident-response"],
    modules: [],
    createdAt: "2026-07-15",
    updatedAt: "2026-08-25",
  },

  // ── Software Engineering Path ──
  {
    id: "course-web-fundamentals",
    programmeId: "prog-software",
    title: "Web Development Fundamentals",
    slug: "web-development-fundamentals",
    description: "HTML, CSS, JavaScript — the building blocks of every web application.",
    objectives: [
      "Build semantic HTML structures",
      "Style responsive layouts with CSS",
      "Add interactivity with vanilla JavaScript",
      "Understand the browser rendering pipeline",
    ],
    prerequisites: ["Basic computer literacy"],
    level: "foundation",
    durationHours: 60,
    moduleCount: 6,
    totalLessons: 36,
    instructorId: "inst-3",
    instructorName: "Nana Yaw Boateng",
    instructorAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=nana",
    priceGHS: 700,
    enrolledCount: 312,
    rating: 4.7,
    reviewCount: 124,
    status: "published",
    thumbnail: "https://images.unsplash.com/photo-1461749280684-dccba630e2f6?w=600&q=80",
    tags: ["html", "css", "javascript", "web"],
    modules: [],
    createdAt: "2026-06-01",
    updatedAt: "2026-08-15",
  },
  {
    id: "course-react-frontend",
    programmeId: "prog-software",
    title: "React Frontend Development",
    slug: "react-frontend-development",
    description: "Build modern, interactive user interfaces with React and TypeScript.",
    objectives: [
      "Build component-based UIs with React",
      "Manage state with hooks and context",
      "Use TypeScript for type-safe development",
      "Implement routing, forms, and API integration",
    ],
    prerequisites: ["Web Development Fundamentals"],
    level: "associate",
    durationHours: 65,
    moduleCount: 7,
    totalLessons: 42,
    instructorId: "inst-3",
    instructorName: "Nana Yaw Boateng",
    instructorAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=nana",
    priceGHS: 900,
    enrolledCount: 278,
    rating: 4.8,
    reviewCount: 98,
    status: "published",
    thumbnail: "https://images.unsplash.com/photo-1633356122544-f134324a6cee?w=600&q=80",
    tags: ["react", "typescript", "frontend"],
    modules: [],
    createdAt: "2026-06-15",
    updatedAt: "2026-08-20",
  },
  {
    id: "course-node-backend",
    programmeId: "prog-software",
    title: "Node.js Backend Development",
    slug: "nodejs-backend-development",
    description: "Build APIs, work with databases, and handle authentication.",
    objectives: [
      "Build RESTful APIs with Express.js",
      "Design and query SQL and MongoDB databases",
      "Implement JWT authentication and authorization",
      "Write tests and handle errors gracefully",
    ],
    prerequisites: ["React Frontend Development"],
    level: "associate",
    durationHours: 60,
    moduleCount: 6,
    totalLessons: 36,
    instructorId: "inst-3",
    instructorName: "Nana Yaw Boateng",
    instructorAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=nana",
    priceGHS: 900,
    enrolledCount: 245,
    rating: 4.6,
    reviewCount: 87,
    status: "published",
    thumbnail: "https://images.unsplash.com/photo-1627398242454-45a1465c2479?w=600&q=80",
    tags: ["nodejs", "backend", "api", "databases"],
    modules: [],
    createdAt: "2026-07-01",
    updatedAt: "2026-08-22",
  },
  {
    id: "course-fullstack-project",
    programmeId: "prog-software",
    title: "Full-Stack Capstone Project",
    slug: "fullstack-capstone-project",
    description: "Build and deploy a production-style application from scratch.",
    objectives: [
      "Architect a full-stack application",
      "Implement frontend, backend, and database",
      "Deploy to a cloud platform",
      "Present your work to peers and instructors",
    ],
    prerequisites: ["Node.js Backend Development"],
    level: "professional",
    durationHours: 55,
    moduleCount: 5,
    totalLessons: 25,
    instructorId: "inst-3",
    instructorName: "Nana Yaw Boateng",
    instructorAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=nana",
    priceGHS: 1000,
    enrolledCount: 198,
    rating: 4.9,
    reviewCount: 56,
    status: "published",
    thumbnail: "https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=600&q=80",
    tags: ["capstone", "fullstack", "deployment"],
    modules: [],
    createdAt: "2026-07-15",
    updatedAt: "2026-08-28",
  },

  // ── Cloud & Infrastructure Path ──
  {
    id: "course-cloud-foundations",
    programmeId: "prog-cloud",
    title: "Cloud Computing Foundations",
    slug: "cloud-computing-foundations",
    description: "AWS, Azure, GCP — understand cloud models, services, and architecture.",
    objectives: [
      "Compare IaaS, PaaS, and SaaS models",
      "Navigate AWS, Azure, and GCP consoles",
      "Deploy virtual machines and storage",
      "Understand cloud networking and security",
    ],
    prerequisites: ["Basic networking"],
    level: "foundation",
    durationHours: 55,
    moduleCount: 5,
    totalLessons: 30,
    instructorId: "inst-4",
    instructorName: "Efua Mensah",
    instructorAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=efua",
    priceGHS: 900,
    enrolledCount: 183,
    rating: 4.9,
    reviewCount: 67,
    status: "published",
    thumbnail: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=600&q=80",
    tags: ["cloud", "aws", "azure", "gcp"],
    modules: [],
    createdAt: "2026-06-01",
    updatedAt: "2026-08-10",
  },
  {
    id: "course-terraform",
    programmeId: "prog-cloud",
    title: "Infrastructure as Code with Terraform",
    slug: "terraform-infrastructure-as-code",
    description: "Automate cloud infrastructure provisioning with Terraform.",
    objectives: [
      "Write Terraform configuration files",
      "Manage infrastructure state and modules",
      "Deploy multi-environment setups",
      "Integrate with CI/CD pipelines",
    ],
    prerequisites: ["Cloud Computing Foundations"],
    level: "associate",
    durationHours: 50,
    moduleCount: 5,
    totalLessons: 30,
    instructorId: "inst-4",
    instructorName: "Efua Mensah",
    instructorAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=efua",
    priceGHS: 800,
    enrolledCount: 156,
    rating: 4.8,
    reviewCount: 45,
    status: "published",
    thumbnail: "https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=600&q=80",
    tags: ["terraform", "iac", "devops"],
    modules: [],
    createdAt: "2026-06-15",
    updatedAt: "2026-08-15",
  },
  {
    id: "course-containers",
    programmeId: "prog-cloud",
    title: "Docker & Kubernetes",
    slug: "docker-kubernetes",
    description: "Containerize applications and orchestrate them at scale.",
    objectives: [
      "Build and manage Docker containers",
      "Write Docker Compose configurations",
      "Deploy applications to Kubernetes clusters",
      "Manage deployments, services, and scaling",
    ],
    prerequisites: ["Infrastructure as Code with Terraform"],
    level: "associate",
    durationHours: 55,
    moduleCount: 5,
    totalLessons: 30,
    instructorId: "inst-4",
    instructorName: "Efua Mensah",
    instructorAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=efua",
    priceGHS: 900,
    enrolledCount: 142,
    rating: 4.7,
    reviewCount: 38,
    status: "published",
    thumbnail: "https://images.unsplash.com/photo-1667372393119-3d4c48d07fc9?w=600&q=80",
    tags: ["docker", "kubernetes", "containers"],
    modules: [],
    createdAt: "2026-07-01",
    updatedAt: "2026-08-18",
  },
  {
    id: "course-devops-pipeline",
    programmeId: "prog-cloud",
    title: "DevOps & CI/CD Pipeline",
    slug: "devops-cicd-pipeline",
    description: "Build automated pipelines for testing, building, and deploying software.",
    objectives: [
      "Design CI/CD pipeline architectures",
      "Implement GitHub Actions or GitLab CI",
      "Automate testing and deployment",
      "Monitor production systems",
    ],
    prerequisites: ["Docker & Kubernetes"],
    level: "professional",
    durationHours: 50,
    moduleCount: 5,
    totalLessons: 25,
    instructorId: "inst-4",
    instructorName: "Efua Mensah",
    instructorAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=efua",
    priceGHS: 900,
    enrolledCount: 128,
    rating: 4.8,
    reviewCount: 32,
    status: "published",
    thumbnail: "https://images.unsplash.com/photo-1618401471353-b98afee0b2eb?w=600&q=80",
    tags: ["devops", "cicd", "automation"],
    modules: [],
    createdAt: "2026-07-15",
    updatedAt: "2026-08-25",
  },
];

// ── Add new programmes and courses FIRST, so the module merge and the
// reading deepening below cover them too ──
for (const p of ALL_NEW_PROGRAMMES) {
  if (!PROGRAMMES.find((existing) => existing.id === p.id)) {
    PROGRAMMES.push(p);
  }
}
for (const c of ALL_NEW_COURSES) {
  if (!COURSES.find((existing) => existing.id === c.id)) {
    COURSES.push(c);
  }
}

// Merge full course content (modules, lessons) into courses.
// Foundation courses get their modules from courseContent.ts; the expanded
// courses (intermediate/advanced/high-demand) get theirs from
// expandedCourseContent.ts. The expanded arrays are shared module-level
// consts — clone them so per-lesson progress mutations never leak between
// courses that slice the same source array.
for (const course of COURSES) {
  const fullModules = ALL_COURSE_MODULES[course.id];
  if (fullModules && fullModules.length > 0) {
    course.modules = fullModules;
  } else {
    const expandedModules = EXPANDED_COURSE_MODULES[course.id];
    if (expandedModules && expandedModules.length > 0) {
      course.modules = structuredClone(expandedModules);
    }
  }
}

// Note: reading-lesson deepening (readingContent.ts, ~190 kB of authored
// content) is applied in the lazy CoursePlayer, NOT here — importing it in
// this module would pull it into the initial bundle and blow the CI budget.
// data.ts stays catalog-only; Learner/CoursePlayer enriches at render time.
// Update original programmes with careerTier and tags
for (const p of PROGRAMMES) {
  if (!p.careerTier) {
    (p as any).careerTier = "foundation";
    if (!p.tags) (p as any).tags = [p.domain];
  }
}

// ── Instructors ──
export const INSTRUCTORS: InstructorProfile[] = [
  {
    id: "inst-1",
    userId: "user-inst-1",
    name: "Kwame Asante",
    email: "kwame@pibridge.com",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=kwame",
    bio: "10+ years in cybersecurity. Former SOC Lead at a major Ghanaian bank. CISSP, CEH certified. Passionate about building Africa's next generation of security professionals.",
    title: "Lead Cybersecurity Instructor",
    specializations: ["SOC Operations", "Incident Response", "Threat Intelligence"],
    courseIds: ["course-net-fundamentals", "course-cyber-fundamentals", "course-soc-operations"],
    rating: 4.8,
    studentCount: 247,
    joinedAt: "2026-05-01",
  },
  {
    id: "inst-2",
    userId: "user-inst-2",
    name: "Ama Darko",
    email: "ama@pibridge.com",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=ama",
    bio: "Linux systems engineer and open-source advocate. Previously at MTN Ghana. Specializes in making command-line skills accessible to beginners.",
    title: "Linux & Systems Instructor",
    specializations: ["Linux Administration", "Shell Scripting", "Open Source"],
    courseIds: ["course-linux-fundamentals"],
    rating: 4.7,
    studentCount: 231,
    joinedAt: "2026-05-15",
  },
  {
    id: "inst-3",
    userId: "user-inst-3",
    name: "Nana Yaw Boateng",
    email: "nana@pibridge.com",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=nana",
    bio: "Full-stack developer with 8 years of experience. Built apps serving millions of users. Former tech lead at a Y Combinator startup. Loves teaching people to code.",
    title: "Lead Software Engineering Instructor",
    specializations: ["React", "Node.js", "TypeScript", "System Design"],
    courseIds: ["course-web-fundamentals", "course-react-frontend", "course-node-backend", "course-fullstack-project"],
    rating: 4.8,
    studentCount: 312,
    joinedAt: "2026-05-01",
  },
  {
    id: "inst-4",
    userId: "user-inst-4",
    name: "Efua Mensah",
    email: "efua@pibridge.com",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=efua",
    bio: "Cloud architect and DevOps engineer. AWS Solutions Architect Professional certified. Previously at Vodafone Ghana. Believes infrastructure should be automated, not feared.",
    title: "Cloud & DevOps Instructor",
    specializations: ["AWS", "Azure", "Terraform", "Kubernetes", "CI/CD"],
    courseIds: ["course-cloud-foundations", "course-terraform", "course-containers", "course-devops-pipeline"],
    rating: 4.9,
    studentCount: 183,
    joinedAt: "2026-05-01",
  },
];

// ── Mock Learner (for demo) ──
export const DEMO_LEARNER: LearnerProfile = {
  id: "learner-1",
  userId: "user-1",
  name: "Kofi Mensah",
  email: "kofi@example.com",
  phone: "+233241234567",
  avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=kofi",
  bio: "Computer science graduate looking to break into cybersecurity.",
  location: "Accra, Ghana",
  goals: ["get_a_job"],
  skillLevel: "beginner",
  enrollments: ["enroll-1", "enroll-2"],
  completedCourses: 1,
  certificates: 1,
  totalHoursLearned: 87,
  streak: 12,
  joinedAt: "2026-07-01",
};

// ── Mock Enrollments ──
export const ENROLLMENTS: Enrollment[] = [
  {
    id: "enroll-1",
    learnerId: "learner-1",
    courseId: "course-net-fundamentals",
    programmeId: "prog-cyber",
    status: "completed",
    progress: 100,
    enrolledAt: "2026-07-01",
    completedAt: "2026-08-15",
    lastAccessedAt: "2026-08-15",
  },
  {
    id: "enroll-2",
    learnerId: "learner-1",
    courseId: "course-linux-fundamentals",
    programmeId: "prog-cyber",
    status: "active",
    progress: 42,
    enrolledAt: "2026-08-16",
    lastAccessedAt: "2026-08-30",
    currentModuleId: "mod-lf-3",
    currentLessonId: "les-lf-3-2",
  },
];

// ── Mock Learning Progress ──
export const LEARNING_PROGRESS: Record<string, LearningProgress> = {
  "course-net-fundamentals": {
    learnerId: "learner-1",
    courseId: "course-net-fundamentals",
    completedLessons: [
      "les-nf-1-1", "les-nf-1-2", "les-nf-1-3",
      "les-nf-2-1", "les-nf-2-2", "les-nf-2-3", "les-nf-2-4",
      "les-nf-3-1", "les-nf-3-2", "les-nf-3-3", "les-nf-3-4",
      "les-nf-4-1", "les-nf-4-2", "les-nf-4-3",
      "les-nf-5-1", "les-nf-5-2", "les-nf-5-3",
      "les-nf-6-1", "les-nf-6-2",
    ],
    completedModules: ["mod-nf-1", "mod-nf-2", "mod-nf-3", "mod-nf-4", "mod-nf-5", "mod-nf-6"],
    quizScores: { "les-nf-1-3": 90, "les-nf-2-4": 85, "les-nf-6-2": 92 },
    assignmentScores: { "les-nf-3-4": 88 },
    projectScores: { "les-nf-6-1": 95 },
    totalTimeSpent: 2400,
    lastAccessedAt: "2026-08-15",
  },
  "course-linux-fundamentals": {
    learnerId: "learner-1",
    courseId: "course-linux-fundamentals",
    completedLessons: ["les-lf-1-1", "les-lf-1-2", "les-lf-1-3", "les-lf-2-1", "les-lf-2-2"],
    completedModules: ["mod-lf-1"],
    quizScores: {},
    assignmentScores: {},
    projectScores: {},
    totalTimeSpent: 1020,
    lastAccessedAt: "2026-08-30",
  },
};

// ── Mock Certificate ──
export const CERTIFICATES: Certificate[] = [
  {
    id: "cert-1",
    credentialId: "PIBR-CERT-2026-NF-001",
    learnerId: "learner-1",
    learnerName: "Kofi Mensah",
    courseId: "course-net-fundamentals",
    courseName: "Networking Fundamentals",
    programmeId: "prog-cyber",
    programmeName: "Cybersecurity Professional Path",
    instructorName: "Kwame Asante",
    score: 91,
    issuedAt: "2026-08-15",
    verificationUrl: "https://pibridge.com/verify/PIBR-CERT-2026-NF-001",
    qrCode: "PIBR-CERT-2026-NF-001",
  },
];
