// ──────────────────────────────────────────────────────────────
// PiBridge Academy — Expanded Programmes, Courses & Platforms
// Foundation → Intermediate → Advanced career paths
// + High-demand tech courses + BusinessOS & Secure platforms
// ──────────────────────────────────────────────────────────────

import type { Programme, Course } from "./types";

// ════════════════════════════════════════════════════════════════
// CYBERSECURITY PATH — Intermediate & Advanced
// ════════════════════════════════════════════════════════════════

export const CYBER_INTERMEDIATE: Programme = {
  id: "prog-cyber-intermediate",
  title: "SOC Analyst Professional",
  slug: "soc-analyst-professional",
  description: "Become a job-ready SOC Analyst — master SIEM, threat detection, incident response, and security operations.",
  longDescription: "This intermediate programme builds on your cybersecurity foundation to prepare you for a Security Operations Center role. You will learn to operate SIEM platforms, detect threats using MITRE ATT&CK, investigate incidents, and respond to real-world attacks. Graduate with a portfolio of detection rules, investigation reports, and incident response playbooks.",
  level: "professional",
  careerTier: "intermediate",
  domain: "cybersecurity",
  icon: "🛡️",
  color: "red",
  image: "https://images.unsplash.com/photo-1563013544-824ae1b704d3?w=800&q=80",
  durationWeeks: 16,
  totalHours: 240,
  priceGHS: 4500,
  currency: "GHS",
  prerequisites: ["Cybersecurity Foundations (Foundation Tier)", "Networking Fundamentals", "Linux Fundamentals"],
  outcomes: [
    "Operate Splunk and ELK SIEM platforms",
    "Write detection rules mapped to MITRE ATT&CK",
    "Investigate and triage security incidents",
    "Perform threat intelligence analysis",
    "Write professional incident reports",
    "Build a SOC analyst portfolio",
  ],
  enrolledCount: 156,
  rating: 4.8,
  reviewCount: 42,
  status: "published",
  featured: false,
  courses: ["course-soc-operations", "course-threat-intel", "course-detection-eng"],
  nextProgrammeId: "prog-cyber-advanced",
  tags: ["soc", "siem", "incident-response", "mitre-attack", "career"],
  createdAt: "2026-07-01",
  updatedAt: "2026-08-25",
};

export const CYBER_ADVANCED: Programme = {
  id: "prog-cyber-advanced",
  title: "Security Engineer & Architect",
  slug: "security-engineer-architect",
  description: "Design and build enterprise security architectures — from network defense to cloud security to governance.",
  longDescription: "The advanced cybersecurity programme prepares you for senior security roles. You will learn to design secure network architectures, implement cloud security controls, conduct penetration testing, manage compliance frameworks, and lead security teams. Graduate with the skills to protect enterprise environments and earn industry certifications.",
  level: "advanced",
  careerTier: "advanced",
  domain: "cybersecurity",
  icon: "🏰",
  color: "red",
  image: "https://images.unsplash.com/photo-1550751827-4bd374c3f58b?w=800&q=80",
  durationWeeks: 20,
  totalHours: 320,
  priceGHS: 7500,
  currency: "GHS",
  prerequisites: ["SOC Analyst Professional (Intermediate Tier)", "Cybersecurity Fundamentals"],
  outcomes: [
    "Design enterprise security architectures",
    "Implement cloud security (AWS/Azure security services)",
    "Conduct penetration testing and vulnerability assessments",
    "Manage compliance frameworks (ISO 27001, NIST, SOC 2)",
    "Lead a security team and build security culture",
    "Prepare for CISSP, CEH, or AWS Security Specialty certifications",
  ],
  enrolledCount: 89,
  rating: 4.9,
  reviewCount: 28,
  status: "published",
  featured: false,
  courses: ["course-pentesting", "course-cloud-security", "course-security-architecture"],
  tags: ["architecture", "penetration-testing", "cloud-security", "compliance", "leadership"],
  createdAt: "2026-08-01",
  updatedAt: "2026-08-30",
};

// ════════════════════════════════════════════════════════════════
// SOFTWARE ENGINEERING PATH — Intermediate & Advanced
// ════════════════════════════════════════════════════════════════

export const SE_INTERMEDIATE: Programme = {
  id: "prog-se-intermediate",
  title: "Full-Stack Developer",
  slug: "fullstack-developer",
  description: "Build production applications end-to-end — React, Node.js, databases, testing, and deployment.",
  longDescription: "This intermediate programme takes you from front-end basics to full-stack proficiency. You will build real applications with React, Node.js, PostgreSQL, and MongoDB. Learn testing, CI/CD, authentication, and deployment. Graduate with a deployed application and a professional developer portfolio.",
  level: "professional",
  careerTier: "intermediate",
  domain: "software_engineering",
  icon: "💻",
  color: "blue",
  image: "https://images.unsplash.com/photo-1461749280684-dccba630e2f6?w=800&q=80",
  durationWeeks: 16,
  totalHours: 240,
  priceGHS: 4000,
  currency: "GHS",
  prerequisites: ["Web Development Fundamentals (Foundation Tier)", "HTML, CSS, JavaScript basics"],
  outcomes: [
    "Build full-stack applications with React and Node.js",
    "Design and query SQL and NoSQL databases",
    "Implement JWT authentication and authorization",
    "Write unit and integration tests",
    "Deploy to cloud platforms with CI/CD",
    "Build a professional developer portfolio",
  ],
  enrolledCount: 245,
  rating: 4.7,
  reviewCount: 98,
  status: "published",
  featured: false,
  courses: ["course-react-frontend", "course-node-backend", "course-testing-cicd"],
  nextProgrammeId: "prog-se-advanced",
  tags: ["fullstack", "react", "nodejs", "databases", "career"],
  createdAt: "2026-07-01",
  updatedAt: "2026-08-25",
};

export const SE_ADVANCED: Programme = {
  id: "prog-se-advanced",
  title: "Tech Lead & Software Architect",
  slug: "tech-lead-architect",
  description: "Lead engineering teams, design systems, and architect scalable applications at enterprise scale.",
  longDescription: "The advanced software engineering programme prepares you for senior technical roles. You will learn system design, microservices architecture, advanced DevOps, team leadership, and technical decision-making. Graduate with the skills to lead engineering teams and design systems that scale.",
  level: "advanced",
  careerTier: "advanced",
  domain: "software_engineering",
  icon: "🏛️",
  color: "blue",
  image: "https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=800&q=80",
  durationWeeks: 20,
  totalHours: 300,
  priceGHS: 6500,
  currency: "GHS",
  prerequisites: ["Full-Stack Developer (Intermediate Tier)", "Node.js Backend Development"],
  outcomes: [
    "Design distributed systems and microservices architectures",
    "Implement advanced DevOps and platform engineering",
    "Lead technical teams and conduct code reviews",
    "Make build-vs-buy decisions and evaluate technology",
    "Design APIs for scale (rate limiting, caching, pagination)",
    "Prepare for senior/lead developer interviews",
  ],
  enrolledCount: 67,
  rating: 4.9,
  reviewCount: 19,
  status: "published",
  featured: false,
  courses: ["course-system-design", "course-microservices", "course-tech-leadership"],
  tags: ["architecture", "leadership", "system-design", "devops", "career"],
  createdAt: "2026-08-01",
  updatedAt: "2026-08-30",
};

// ════════════════════════════════════════════════════════════════
// CLOUD & INFRASTRUCTURE PATH — Intermediate & Advanced
// ════════════════════════════════════════════════════════════════

export const CLOUD_INTERMEDIATE: Programme = {
  id: "prog-cloud-intermediate",
  title: "Cloud Engineer",
  slug: "cloud-engineer",
  description: "Deploy, manage, and optimize cloud infrastructure on AWS, Azure, or GCP with Kubernetes and Terraform.",
  longDescription: "This intermediate programme builds practical cloud engineering skills. You will work with multiple cloud providers, master infrastructure as code, containerize applications, and manage Kubernetes clusters. Graduate with hands-on experience and preparation for AWS Solutions Architect or Azure Administrator certifications.",
  level: "professional",
  careerTier: "intermediate",
  domain: "cloud_infrastructure",
  icon: "☁️",
  color: "amber",
  image: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=800&q=80",
  durationWeeks: 16,
  totalHours: 220,
  priceGHS: 4500,
  currency: "GHS",
  prerequisites: ["Cloud Computing Foundations (Foundation Tier)", "Basic networking"],
  outcomes: [
    "Deploy and manage resources on AWS, Azure, and GCP",
    "Write production-grade Terraform configurations",
    "Containerize applications with Docker and deploy to Kubernetes",
    "Build CI/CD pipelines for cloud-native applications",
    "Implement cloud monitoring and cost optimization",
    "Prepare for AWS Solutions Architect or Azure Administrator certifications",
  ],
  enrolledCount: 134,
  rating: 4.8,
  reviewCount: 45,
  status: "published",
  featured: false,
  courses: ["course-terraform", "course-containers", "course-devops-pipeline"],
  nextProgrammeId: "prog-cloud-advanced",
  tags: ["cloud", "terraform", "kubernetes", "devops", "career"],
  createdAt: "2026-07-01",
  updatedAt: "2026-08-25",
};

export const CLOUD_ADVANCED: Programme = {
  id: "prog-cloud-advanced",
  title: "Solutions Architect",
  slug: "solutions-architect",
  description: "Design enterprise cloud architectures, lead migration projects, and optimize for cost, performance, and security.",
  longDescription: "The advanced cloud programme prepares you for solutions architect roles. You will design multi-region, highly available architectures, lead cloud migration projects, implement FinOps practices, and build enterprise-grade security controls. Graduate with the skills to architect complex cloud solutions and lead technical transformation.",
  level: "expert",
  careerTier: "advanced",
  domain: "cloud_infrastructure",
  icon: "🏗️",
  color: "amber",
  image: "https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=800&q=80",
  durationWeeks: 20,
  totalHours: 300,
  priceGHS: 7000,
  currency: "GHS",
  prerequisites: ["Cloud Engineer (Intermediate Tier)", "Docker & Kubernetes"],
  outcomes: [
    "Design multi-region, highly available cloud architectures",
    "Lead cloud migration projects (lift-and-shift, re-platform, re-architect)",
    "Implement FinOps and cloud cost optimization",
    "Build enterprise security controls (Guardrails, SCPs, Landing Zones)",
    "Design disaster recovery and business continuity plans",
    "Prepare for AWS Solutions Architect Professional or equivalent",
  ],
  enrolledCount: 56,
  rating: 4.9,
  reviewCount: 18,
  status: "published",
  featured: false,
  courses: ["course-advanced-architecture", "course-cloud-migration", "course-finops"],
  tags: ["architecture", "migration", "finops", "enterprise", "leadership"],
  createdAt: "2026-08-01",
  updatedAt: "2026-08-30",
};

// ════════════════════════════════════════════════════════════════
// NEW HIGH-DEMAND TECH PROGRAMMES
// ════════════════════════════════════════════════════════════════

export const AI_ML_PROGRAMME: Programme = {
  id: "prog-ai-ml",
  title: "AI & Machine Learning Engineer",
  slug: "ai-machine-learning",
  description: "Build intelligent systems — from data pipelines to model training to production deployment.",
  longDescription: "Artificial Intelligence and Machine Learning are transforming every industry. This programme takes you from Python fundamentals through data science, machine learning, deep learning, and MLOps. You will build real AI applications including computer vision, NLP, and recommendation systems. Graduate with a portfolio of AI projects ready for the job market.",
  level: "foundation",
  careerTier: "foundation",
  domain: "ai_ml",
  icon: "🤖",
  color: "purple",
  image: "https://images.unsplash.com/photo-1677442136019-21780ecad995?w=800&q=80",
  durationWeeks: 24,
  totalHours: 360,
  priceGHS: 5500,
  currency: "GHS",
  prerequisites: ["Basic Python programming", "High school mathematics"],
  outcomes: [
    "Build and train machine learning models with Python",
    "Work with data using pandas, numpy, and scikit-learn",
    "Build deep learning models with TensorFlow or PyTorch",
    "Deploy ML models to production",
    "Build NLP and computer vision applications",
    "Understand responsible AI and ethics",
  ],
  enrolledCount: 189,
  rating: 4.8,
  reviewCount: 67,
  status: "published",
  featured: true,
  courses: ["course-python-fundamentals", "course-data-science", "course-ml-fundamentals", "course-deep-learning"],
  tags: ["ai", "machine-learning", "python", "data", "deep-learning"],
  createdAt: "2026-07-01",
  updatedAt: "2026-08-25",
};

export const DATA_PROGRAMME: Programme = {
  id: "prog-data",
  title: "Data Engineering & Analytics",
  slug: "data-engineering-analytics",
  description: "Build data pipelines, analyze datasets, and create business intelligence dashboards.",
  longDescription: "Data is the new oil, but only if you can extract, transform, and analyze it. This programme covers SQL mastery, Python for data, ETL pipelines, data warehousing, and business intelligence. You will work with real datasets and build end-to-end analytics solutions. Graduate ready for roles in data analytics, business intelligence, or data engineering.",
  level: "foundation",
  careerTier: "foundation",
  domain: "data",
  icon: "📊",
  color: "emerald",
  image: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&q=80",
  durationWeeks: 20,
  totalHours: 300,
  priceGHS: 4500,
  currency: "GHS",
  prerequisites: ["Basic computer literacy", "Comfort with spreadsheets"],
  outcomes: [
    "Write advanced SQL queries and design databases",
    "Use Python for data analysis (pandas, numpy, matplotlib)",
    "Build ETL pipelines for data transformation",
    "Create interactive dashboards with Power BI or Tableau",
    "Perform statistical analysis and hypothesis testing",
    "Understand data warehousing concepts",
  ],
  enrolledCount: 167,
  rating: 4.7,
  reviewCount: 56,
  status: "published",
  featured: true,
  courses: ["course-python-fundamentals", "course-sql-advanced", "course-etl-pipelines", "course-bi-dashboards"],
  tags: ["data", "sql", "python", "analytics", "bi"],
  createdAt: "2026-07-01",
  updatedAt: "2026-08-20",
};

export const DEVSECOPS_PROGRAMME: Programme = {
  id: "prog-devsecops",
  title: "DevSecOps Engineer",
  slug: "devsecops-engineer",
  description: "Embed security into every stage of the software delivery pipeline — from code to cloud.",
  longDescription: "DevSecOps is one of the fastest-growing roles in tech. This programme combines development, operations, and security into a single discipline. You will learn to automate security testing, implement infrastructure as code with security controls, manage secrets, and build secure CI/CD pipelines. Graduate ready for roles that bridge development and security teams.",
  level: "foundation",
  careerTier: "foundation",
  domain: "devsecops",
  icon: "🔒",
  color: "red",
  image: "https://images.unsplash.com/photo-1618401471353-b98afee0b2eb?w=800&q=80",
  durationWeeks: 20,
  totalHours: 280,
  priceGHS: 5000,
  currency: "GHS",
  prerequisites: ["Basic Linux command line", "Basic networking concepts"],
  outcomes: [
    "Integrate SAST, DAST, and SCA into CI/CD pipelines",
    "Implement infrastructure as code with security controls",
    "Manage secrets and credentials securely",
    "Container security scanning and hardening",
    "Implement policy-as-code (OPA, Sentinel)",
    "Build secure software supply chains",
  ],
  enrolledCount: 98,
  rating: 4.9,
  reviewCount: 32,
  status: "published",
  featured: true,
  courses: ["course-linux-fundamentals", "course-docker-security", "course-ci-cd-security", "course-cloud-security"],
  tags: ["devsecops", "security", "ci-cd", "containers", "iac"],
  createdAt: "2026-07-15",
  updatedAt: "2026-08-28",
};

export const MOBILE_PROGRAMME: Programme = {
  id: "prog-mobile",
  title: "Mobile App Development",
  slug: "mobile-app-development",
  description: "Build cross-platform mobile apps with React Native and Flutter for iOS and Android.",
  longDescription: "Mobile development is essential in Africa-first markets. This programme teaches you to build cross-platform mobile applications using React Native and Flutter. You will learn UI/UX design principles, state management, API integration, offline-first patterns, and app store deployment. Graduate with deployed apps and a mobile development portfolio.",
  level: "foundation",
  careerTier: "foundation",
  domain: "mobile",
  icon: "📱",
  color: "cyan",
  image: "https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?w=800&q=80",
  durationWeeks: 20,
  totalHours: 280,
  priceGHS: 4500,
  currency: "GHS",
  prerequisites: ["Basic programming knowledge", "JavaScript fundamentals"],
  outcomes: [
    "Build cross-platform mobile apps with React Native or Flutter",
    "Implement mobile UI/UX best practices",
    "Handle offline data and low-bandwidth scenarios",
    "Integrate with REST APIs and real-time databases",
    "Implement push notifications and deep linking",
    "Deploy to App Store and Google Play Store",
  ],
  enrolledCount: 145,
  rating: 4.6,
  reviewCount: 48,
  status: "published",
  featured: false,
  courses: ["course-react-native", "course-flutter", "course-mobile-ui", "course-mobile-deploy"],
  tags: ["mobile", "react-native", "flutter", "ios", "android"],
  createdAt: "2026-07-15",
  updatedAt: "2026-08-22",
};

export const BLOCKCHAIN_PROGRAMME: Programme = {
  id: "prog-blockchain",
  title: "Blockchain & Web3 Development",
  slug: "blockchain-web3",
  description: "Build decentralized applications, smart contracts, and digital payment systems.",
  longDescription: "Blockchain and Web3 are reshaping finance, supply chain, and digital identity across Africa. This programme covers Solidity smart contracts, Ethereum development, DeFi protocols, and decentralized application architecture. You will build real dApps and understand the regulatory landscape for blockchain in Ghana. Graduate ready for the emerging Web3 job market.",
  level: "foundation",
  careerTier: "foundation",
  domain: "blockchain",
  icon: "⛓️",
  color: "amber",
  image: "https://images.unsplash.com/photo-1639762681485-074b7f938ba0?w=800&q=80",
  durationWeeks: 16,
  totalHours: 240,
  priceGHS: 4000,
  currency: "GHS",
  prerequisites: ["JavaScript fundamentals", "Basic understanding of cryptography"],
  outcomes: [
    "Write Solidity smart contracts",
    "Build decentralized applications (dApps)",
    "Understand Ethereum, Polygon, and L2 solutions",
    "Implement DeFi protocols (DEX, lending, staking)",
    "Understand blockchain security and auditing",
    "Navigate Ghana blockchain regulation",
  ],
  enrolledCount: 78,
  rating: 4.7,
  reviewCount: 24,
  status: "published",
  featured: false,
  courses: ["course-solidity", "course-dapp-dev", "course-defi-protocols"],
  tags: ["blockchain", "web3", "solidity", "ethereum", "defi"],
  createdAt: "2026-08-01",
  updatedAt: "2026-08-28",
};

// ════════════════════════════════════════════════════════════════
// NEW COURSES (High-Demand Tech)
// ════════════════════════════════════════════════════════════════

export const NEW_COURSES: Course[] = [
  // ── Cybersecurity Intermediate/Advanced ──
  {
    id: "course-threat-intel", programmeId: "prog-cyber-intermediate",
    title: "Threat Intelligence & Hunting", slug: "threat-intelligence",
    description: "Collect, analyze, and act on threat intelligence to proactively defend against adversaries.",
    objectives: ["Collect OSINT and commercial threat intel", "Analyze IOCs and TTPs", "Perform threat hunts using MITRE ATT&CK", "Write threat intel reports"],
    prerequisites: ["SOC Operations"], level: "professional", durationHours: 50, moduleCount: 5, totalLessons: 28,
    instructorId: "inst-1", instructorName: "Kwame Asante", instructorAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=kwame",
    priceGHS: 800, enrolledCount: 112, rating: 4.8, reviewCount: 34, status: "published",
    thumbnail: "https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=600&q=80",
    tags: ["threat-intel", "osint", "mitre-attack", "hunting"], modules: [], createdAt: "2026-07-15", updatedAt: "2026-08-20",
  },
  {
    id: "course-detection-eng", programmeId: "prog-cyber-intermediate",
    title: "Detection Engineering", slug: "detection-engineering",
    description: "Build, test, and tune detection rules for a modern SOC.",
    objectives: ["Write detection rules in Sigma/YARA", "Build SIEM use cases", "Test rules against attack simulations", "Tune rules to reduce false positives"],
    prerequisites: ["SOC Operations"], level: "professional", durationHours: 45, moduleCount: 4, totalLessons: 22,
    instructorId: "inst-1", instructorName: "Kwame Asante", instructorAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=kwame",
    priceGHS: 700, enrolledCount: 98, rating: 4.9, reviewCount: 28, status: "published",
    thumbnail: "https://images.unsplash.com/photo-1555949963-ff9fe0c870eb?w=600&q=80",
    tags: ["detection", "sigma", "yara", "siem"], modules: [], createdAt: "2026-07-20", updatedAt: "2026-08-22",
  },
  {
    id: "course-pentesting", programmeId: "prog-cyber-advanced",
    title: "Penetration Testing", slug: "penetration-testing",
    description: "Master ethical hacking — reconnaissance, exploitation, privilege escalation, and reporting.",
    objectives: ["Conduct network penetration tests", "Exploit web application vulnerabilities", "Perform privilege escalation on Linux/Windows", "Write professional pentest reports"],
    prerequisites: ["SOC Analyst Professional"], level: "advanced", durationHours: 60, moduleCount: 6, totalLessons: 32,
    instructorId: "inst-1", instructorName: "Kwame Asante", instructorAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=kwame",
    priceGHS: 1200, enrolledCount: 76, rating: 4.9, reviewCount: 22, status: "published",
    thumbnail: "https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=600&q=80",
    tags: ["pentesting", "ethical-hacking", "exploitation", "kali"], modules: [], createdAt: "2026-08-01", updatedAt: "2026-08-28",
  },
  {
    id: "course-cloud-security", programmeId: "prog-cyber-advanced",
    title: "Cloud Security Engineering", slug: "cloud-security",
    description: "Secure cloud infrastructure — IAM, network security, data protection, and compliance.",
    objectives: ["Implement AWS/Azure security controls", "Design secure cloud architectures", "Implement cloud-native security tools", "Manage cloud compliance (CIS, SOC 2)"],
    prerequisites: ["Cloud Computing Foundations"], level: "advanced", durationHours: 55, moduleCount: 5, totalLessons: 28,
    instructorId: "inst-4", instructorName: "Efua Mensah", instructorAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=efua",
    priceGHS: 1000, enrolledCount: 68, rating: 4.8, reviewCount: 19, status: "published",
    thumbnail: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=600&q=80",
    tags: ["cloud-security", "aws", "azure", "iam", "compliance"], modules: [], createdAt: "2026-08-05", updatedAt: "2026-08-30",
  },
  {
    id: "course-security-architecture", programmeId: "prog-cyber-advanced",
    title: "Security Architecture & Governance", slug: "security-architecture",
    description: "Design enterprise security programs and lead security governance.",
    objectives: ["Design security architectures", "Implement ISO 27001 / NIST CSF", "Build security policies and procedures", "Lead security risk assessments"],
    prerequisites: ["Penetration Testing", "Cloud Security Engineering"], level: "advanced", durationHours: 50, moduleCount: 5, totalLessons: 25,
    instructorId: "inst-1", instructorName: "Kwame Asante", instructorAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=kwame",
    priceGHS: 1100, enrolledCount: 45, rating: 4.9, reviewCount: 12, status: "published",
    thumbnail: "https://images.unsplash.com/photo-1550751827-4bd374c3f58b?w=600&q=80",
    tags: ["architecture", "governance", "iso27001", "nist"], modules: [], createdAt: "2026-08-10", updatedAt: "2026-08-30",
  },

  // ── Software Engineering Intermediate/Advanced ──
  {
    id: "course-testing-cicd", programmeId: "prog-se-intermediate",
    title: "Testing & CI/CD", slug: "testing-cicd",
    description: "Write automated tests and build deployment pipelines.",
    objectives: ["Write unit, integration, and E2E tests", "Set up GitHub Actions workflows", "Implement test-driven development", "Deploy with zero-downtime"],
    prerequisites: ["React Frontend Development"], level: "professional", durationHours: 45, moduleCount: 4, totalLessons: 22,
    instructorId: "inst-3", instructorName: "Nana Yaw Boateng", instructorAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=nana",
    priceGHS: 700, enrolledCount: 189, rating: 4.7, reviewCount: 56, status: "published",
    thumbnail: "https://images.unsplash.com/photo-1618401471353-b98afee0b2eb?w=600&q=80",
    tags: ["testing", "cicd", "github-actions", "tdd"], modules: [], createdAt: "2026-07-20", updatedAt: "2026-08-22",
  },
  {
    id: "course-system-design", programmeId: "prog-se-advanced",
    title: "System Design & Architecture", slug: "system-design",
    description: "Design scalable distributed systems — from load balancers to databases to caching.",
    objectives: ["Design scalable architectures", "Choose appropriate databases and caches", "Implement microservices patterns", "Design for high availability"],
    prerequisites: ["Full-Stack Developer"], level: "advanced", durationHours: 55, moduleCount: 5, totalLessons: 28,
    instructorId: "inst-3", instructorName: "Nana Yaw Boateng", instructorAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=nana",
    priceGHS: 1000, enrolledCount: 56, rating: 4.9, reviewCount: 18, status: "published",
    thumbnail: "https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=600&q=80",
    tags: ["system-design", "architecture", "distributed-systems", "scaling"], modules: [], createdAt: "2026-08-05", updatedAt: "2026-08-28",
  },
  {
    id: "course-microservices", programmeId: "prog-se-advanced",
    title: "Microservices & Platform Engineering", slug: "microservices",
    description: "Decompose monoliths into microservices and build internal developer platforms.",
    objectives: ["Decompose monolithic applications", "Implement service mesh and API gateways", "Build internal developer platforms", "Manage service observability"],
    prerequisites: ["System Design"], level: "advanced", durationHours: 50, moduleCount: 5, totalLessons: 25,
    instructorId: "inst-3", instructorName: "Nana Yaw Boateng", instructorAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=nana",
    priceGHS: 900, enrolledCount: 45, rating: 4.8, reviewCount: 14, status: "published",
    thumbnail: "https://images.unsplash.com/photo-1667372393119-3d4c48d07fc9?w=600&q=80",
    tags: ["microservices", "platform-engineering", "service-mesh", "kubernetes"], modules: [], createdAt: "2026-08-10", updatedAt: "2026-08-30",
  },
  {
    id: "course-tech-leadership", programmeId: "prog-se-advanced",
    title: "Technical Leadership & Engineering Management", slug: "tech-leadership",
    description: "Lead engineering teams, conduct code reviews, and drive technical strategy.",
    objectives: ["Lead technical teams effectively", "Conduct impactful code reviews", "Manage technical debt", "Drive technical strategy and roadmap"],
    prerequisites: ["System Design"], level: "advanced", durationHours: 40, moduleCount: 4, totalLessons: 20,
    instructorId: "inst-3", instructorName: "Nana Yaw Boateng", instructorAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=nana",
    priceGHS: 800, enrolledCount: 34, rating: 4.9, reviewCount: 11, status: "published",
    thumbnail: "https://images.unsplash.com/photo-1552664730-d307ca884978?w=600&q=80",
    tags: ["leadership", "management", "code-review", "strategy"], modules: [], createdAt: "2026-08-15", updatedAt: "2026-08-30",
  },

  // ── Cloud Intermediate/Advanced ──
  {
    id: "course-advanced-architecture", programmeId: "prog-cloud-advanced",
    title: "Advanced Cloud Architecture", slug: "advanced-cloud-architecture",
    description: "Design multi-region, highly available enterprise cloud architectures.",
    objectives: ["Design multi-region architectures", "Implement disaster recovery", "Optimize for cost and performance", "Build enterprise landing zones"],
    prerequisites: ["Cloud Engineer"], level: "advanced", durationHours: 55, moduleCount: 5, totalLessons: 28,
    instructorId: "inst-4", instructorName: "Efua Mensah", instructorAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=efua",
    priceGHS: 1100, enrolledCount: 45, rating: 4.9, reviewCount: 15, status: "published",
    thumbnail: "https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=600&q=80",
    tags: ["architecture", "multi-region", "disaster-recovery", "landing-zones"], modules: [], createdAt: "2026-08-05", updatedAt: "2026-08-28",
  },
  {
    id: "course-cloud-migration", programmeId: "prog-cloud-advanced",
    title: "Cloud Migration & Modernization", slug: "cloud-migration",
    description: "Migrate legacy systems to the cloud using industry-proven frameworks.",
    objectives: ["Assess workloads for migration", "Execute lift-and-shift, re-platform, and re-architect strategies", "Minimize downtime during migration", "Validate and optimize post-migration"],
    prerequisites: ["Advanced Cloud Architecture"], level: "advanced", durationHours: 45, moduleCount: 4, totalLessons: 22,
    instructorId: "inst-4", instructorName: "Efua Mensah", instructorAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=efua",
    priceGHS: 900, enrolledCount: 38, rating: 4.8, reviewCount: 12, status: "published",
    thumbnail: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=600&q=80",
    tags: ["migration", "modernization", "legacy", "cloud"], modules: [], createdAt: "2026-08-10", updatedAt: "2026-08-30",
  },
  {
    id: "course-finops", programmeId: "prog-cloud-advanced",
    title: "FinOps & Cloud Cost Optimization", slug: "finops",
    description: "Master cloud financial operations — budgeting, forecasting, and cost optimization.",
    objectives: ["Implement cloud cost governance", "Build cost allocation and tagging strategies", "Optimize compute, storage, and network costs", "Build FinOps dashboards and reports"],
    prerequisites: ["Cloud Engineer"], level: "advanced", durationHours: 35, moduleCount: 4, totalLessons: 18,
    instructorId: "inst-4", instructorName: "Efua Mensah", instructorAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=efua",
    priceGHS: 700, enrolledCount: 52, rating: 4.8, reviewCount: 16, status: "published",
    thumbnail: "https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=600&q=80",
    tags: ["finops", "cost-optimization", "cloud-governance"], modules: [], createdAt: "2026-08-15", updatedAt: "2026-08-30",
  },

  // ── AI/ML Courses ──
  {
    id: "course-python-fundamentals", programmeId: "prog-ai-ml",
    title: "Python for AI & Data", slug: "python-ai-data",
    description: "Master Python programming for data science and machine learning.",
    objectives: ["Write Python scripts and functions", "Use data structures effectively", "Work with libraries (pandas, numpy)", "Perform data cleaning and transformation"],
    prerequisites: [], level: "foundation", durationHours: 60, moduleCount: 6, totalLessons: 36,
    instructorId: "inst-3", instructorName: "Nana Yaw Boateng", instructorAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=nana",
    priceGHS: 700, enrolledCount: 312, rating: 4.7, reviewCount: 124, status: "published",
    thumbnail: "https://images.unsplash.com/photo-1526379095098-d400fd0bf935?w=600&q=80",
    tags: ["python", "programming", "data", "fundamentals"], modules: [], createdAt: "2026-07-01", updatedAt: "2026-08-20",
  },
  {
    id: "course-data-science", programmeId: "prog-data",
    title: "Data Science with Python", slug: "data-science-python",
    description: "Analyze real datasets, build visualizations, and extract business insights.",
    objectives: ["Clean and transform messy data", "Perform statistical analysis", "Create insightful visualizations", "Communicate findings effectively"],
    prerequisites: ["Python Fundamentals"], level: "foundation", durationHours: 55, moduleCount: 5, totalLessons: 28,
    instructorId: "inst-3", instructorName: "Nana Yaw Boateng", instructorAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=nana",
    priceGHS: 800, enrolledCount: 189, rating: 4.8, reviewCount: 67, status: "published",
    thumbnail: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=600&q=80",
    tags: ["data-science", "python", "statistics", "visualization"], modules: [], createdAt: "2026-07-10", updatedAt: "2026-08-22",
  },
  {
    id: "course-ml-fundamentals", programmeId: "prog-ai-ml",
    title: "Machine Learning Fundamentals", slug: "ml-fundamentals",
    description: "Build, train, and evaluate machine learning models with scikit-learn.",
    objectives: ["Understand supervised and unsupervised learning", "Build regression, classification, and clustering models", "Evaluate model performance", "Feature engineering techniques"],
    prerequisites: ["Data Science with Python"], level: "foundation", durationHours: 60, moduleCount: 6, totalLessons: 32,
    instructorId: "inst-3", instructorName: "Nana Yaw Boateng", instructorAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=nana",
    priceGHS: 900, enrolledCount: 156, rating: 4.8, reviewCount: 52, status: "published",
    thumbnail: "https://images.unsplash.com/photo-1677442136019-21780ecad995?w=600&q=80",
    tags: ["machine-learning", "scikit-learn", "models", "data"], modules: [], createdAt: "2026-07-20", updatedAt: "2026-08-25",
  },
  {
    id: "course-deep-learning", programmeId: "prog-ai-ml",
    title: "Deep Learning & Neural Networks", slug: "deep-learning",
    description: "Build neural networks with TensorFlow and PyTorch for vision, NLP, and more.",
    objectives: ["Build and train neural networks", "Implement CNNs for computer vision", "Build RNNs/Transformers for NLP", "Deploy models to production"],
    prerequisites: ["Machine Learning Fundamentals"], level: "advanced", durationHours: 70, moduleCount: 7, totalLessons: 35,
    instructorId: "inst-3", instructorName: "Nana Yaw Boateng", instructorAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=nana",
    priceGHS: 1100, enrolledCount: 98, rating: 4.9, reviewCount: 32, status: "published",
    thumbnail: "https://images.unsplash.com/photo-1677442136019-21780ecad995?w=600&q=80",
    tags: ["deep-learning", "neural-networks", "tensorflow", "pytorch"], modules: [], createdAt: "2026-08-01", updatedAt: "2026-08-30",
  },

  // ── Data Engineering Courses ──
  {
    id: "course-sql-advanced", programmeId: "prog-data",
    title: "Advanced SQL & Database Design", slug: "advanced-sql",
    description: "Master complex queries, performance optimization, and data modeling.",
    objectives: ["Write complex SQL queries", "Design normalized databases", "Optimize query performance", "Use window functions and CTEs"],
    prerequisites: [], level: "foundation", durationHours: 50, moduleCount: 5, totalLessons: 28,
    instructorId: "inst-3", instructorName: "Nana Yaw Boateng", instructorAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=nana",
    priceGHS: 700, enrolledCount: 234, rating: 4.7, reviewCount: 78, status: "published",
    thumbnail: "https://images.unsplash.com/photo-1544383835-bda2bc66a55d?w=600&q=80",
    tags: ["sql", "databases", "optimization", "modeling"], modules: [], createdAt: "2026-07-05", updatedAt: "2026-08-18",
  },
  {
    id: "course-etl-pipelines", programmeId: "prog-data",
    title: "ETL Pipelines & Data Engineering", slug: "etl-pipelines",
    description: "Build robust data pipelines for extraction, transformation, and loading.",
    objectives: ["Design ETL architectures", "Build pipelines with Python and Airflow", "Handle data quality and validation", "Implement data warehouses"],
    prerequisites: ["Python Fundamentals", "Advanced SQL"], level: "foundation", durationHours: 55, moduleCount: 5, totalLessons: 28,
    instructorId: "inst-3", instructorName: "Nana Yaw Boateng", instructorAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=nana",
    priceGHS: 800, enrolledCount: 123, rating: 4.8, reviewCount: 42, status: "published",
    thumbnail: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=600&q=80",
    tags: ["etl", "data-engineering", "airflow", "pipelines"], modules: [], createdAt: "2026-07-15", updatedAt: "2026-08-22",
  },
  {
    id: "course-bi-dashboards", programmeId: "prog-data",
    title: "Business Intelligence & Dashboards", slug: "bi-dashboards",
    description: "Build interactive dashboards and business intelligence solutions.",
    objectives: ["Build dashboards with Power BI or Tableau", "Design KPI frameworks", "Create automated reports", "Tell stories with data"],
    prerequisites: ["Data Science with Python"], level: "foundation", durationHours: 40, moduleCount: 4, totalLessons: 20,
    instructorId: "inst-3", instructorName: "Nana Yaw Boateng", instructorAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=nana",
    priceGHS: 600, enrolledCount: 167, rating: 4.6, reviewCount: 56, status: "published",
    thumbnail: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=600&q=80",
    tags: ["bi", "dashboards", "power-bi", "tableau"], modules: [], createdAt: "2026-07-20", updatedAt: "2026-08-25",
  },

  // ── DevSecOps Courses ──
  {
    id: "course-docker-security", programmeId: "prog-devsecops",
    title: "Container Security & Hardening", slug: "container-security",
    description: "Secure Docker and Kubernetes deployments following CIS benchmarks.",
    objectives: ["Harden Docker images and containers", "Implement runtime security controls", "Scan images for vulnerabilities", "Secure Kubernetes clusters"],
    prerequisites: ["Docker & Kubernetes"], level: "foundation", durationHours: 50, moduleCount: 5, totalLessons: 26,
    instructorId: "inst-4", instructorName: "Efua Mensah", instructorAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=efua",
    priceGHS: 800, enrolledCount: 89, rating: 4.9, reviewCount: 28, status: "published",
    thumbnail: "https://images.unsplash.com/photo-1667372393119-3d4c48d07fc9?w=600&q=80",
    tags: ["docker", "kubernetes", "security", "cis-benchmark"], modules: [], createdAt: "2026-07-20", updatedAt: "2026-08-25",
  },
  {
    id: "course-ci-cd-security", programmeId: "prog-devsecops",
    title: "Secure CI/CD Pipelines", slug: "secure-cicd",
    description: "Integrate security testing into every stage of the software delivery pipeline.",
    objectives: ["Integrate SAST/DAST into pipelines", "Implement software composition analysis", "Secure secrets management", "Build policy-as-code"],
    prerequisites: ["Container Security"], level: "foundation", durationHours: 45, moduleCount: 4, totalLessons: 22,
    instructorId: "inst-4", instructorName: "Efua Mensah", instructorAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=efua",
    priceGHS: 700, enrolledCount: 76, rating: 4.8, reviewCount: 24, status: "published",
    thumbnail: "https://images.unsplash.com/photo-1618401471353-b98afee0b2eb?w=600&q=80",
    tags: ["cicd", "security", "sast", "dast", "supply-chain"], modules: [], createdAt: "2026-08-01", updatedAt: "2026-08-28",
  },

  // ── Mobile Courses ──
  {
    id: "course-react-native", programmeId: "prog-mobile",
    title: "React Native Development", slug: "react-native",
    description: "Build cross-platform mobile apps with React Native and TypeScript.",
    objectives: ["Build mobile UIs with React Native", "Manage state and navigation", "Integrate device APIs", "Handle offline-first patterns"],
    prerequisites: ["JavaScript Fundamentals"], level: "foundation", durationHours: 60, moduleCount: 6, totalLessons: 30,
    instructorId: "inst-3", instructorName: "Nana Yaw Boateng", instructorAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=nana",
    priceGHS: 800, enrolledCount: 145, rating: 4.6, reviewCount: 48, status: "published",
    thumbnail: "https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?w=600&q=80",
    tags: ["react-native", "mobile", "typescript", "cross-platform"], modules: [], createdAt: "2026-07-15", updatedAt: "2026-08-20",
  },
  {
    id: "course-flutter", programmeId: "prog-mobile",
    title: "Flutter & Dart", slug: "flutter-dart",
    description: "Build beautiful native apps from a single codebase with Flutter.",
    objectives: ["Learn Dart programming language", "Build Flutter widgets and layouts", "Implement state management", "Deploy to iOS and Android"],
    prerequisites: ["Basic programming"], level: "foundation", durationHours: 55, moduleCount: 5, totalLessons: 28,
    instructorId: "inst-3", instructorName: "Nana Yaw Boateng", instructorAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=nana",
    priceGHS: 700, enrolledCount: 98, rating: 4.7, reviewCount: 32, status: "published",
    thumbnail: "https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?w=600&q=80",
    tags: ["flutter", "dart", "mobile", "cross-platform"], modules: [], createdAt: "2026-07-20", updatedAt: "2026-08-22",
  },
  {
    id: "course-mobile-ui", programmeId: "prog-mobile",
    title: "Mobile UI/UX Design", slug: "mobile-ui-ux",
    description: "Design intuitive, beautiful mobile interfaces following platform guidelines.",
    objectives: ["Apply Material Design and iOS HIG", "Create responsive mobile layouts", "Implement accessibility on mobile", "Design for low-bandwidth users"],
    prerequisites: [], level: "foundation", durationHours: 35, moduleCount: 3, totalLessons: 18,
    instructorId: "inst-3", instructorName: "Nana Yaw Boateng", instructorAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=nana",
    priceGHS: 500, enrolledCount: 134, rating: 4.5, reviewCount: 42, status: "published",
    thumbnail: "https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?w=600&q=80",
    tags: ["ui-ux", "design", "mobile", "accessibility"], modules: [], createdAt: "2026-07-25", updatedAt: "2026-08-20",
  },
  {
    id: "course-mobile-deploy", programmeId: "prog-mobile",
    title: "Mobile App Deployment & DevOps", slug: "mobile-deployment",
    description: "Deploy mobile apps to app stores with automated build pipelines.",
    objectives: ["Set up app signing and provisioning", "Build and deploy to App Store and Play Store", "Implement fastlane automation", "Monitor app performance"],
    prerequisites: ["React Native or Flutter"], level: "foundation", durationHours: 30, moduleCount: 3, totalLessons: 15,
    instructorId: "inst-4", instructorName: "Efua Mensah", instructorAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=efua",
    priceGHS: 500, enrolledCount: 87, rating: 4.6, reviewCount: 28, status: "published",
    thumbnail: "https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?w=600&q=80",
    tags: ["deployment", "app-store", "play-store", "fastlane"], modules: [], createdAt: "2026-08-01", updatedAt: "2026-08-25",
  },

  // ── Blockchain Courses ──
  {
    id: "course-solidity", programmeId: "prog-blockchain",
    title: "Solidity & Smart Contracts", slug: "solidity-smart-contracts",
    description: "Write, test, and deploy smart contracts on Ethereum and EVM-compatible chains.",
    objectives: ["Write Solidity smart contracts", "Test with Hardhat/Foundry", "Deploy to testnets and mainnet", "Understand gas optimization"],
    prerequisites: ["JavaScript"], level: "foundation", durationHours: 55, moduleCount: 5, totalLessons: 28,
    instructorId: "inst-3", instructorName: "Nana Yaw Boateng", instructorAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=nana",
    priceGHS: 800, enrolledCount: 78, rating: 4.7, reviewCount: 24, status: "published",
    thumbnail: "https://images.unsplash.com/photo-1639762681485-074b7f938ba0?w=600&q=80",
    tags: ["solidity", "smart-contracts", "ethereum", "hardhat"], modules: [], createdAt: "2026-08-01", updatedAt: "2026-08-25",
  },
  {
    id: "course-dapp-dev", programmeId: "prog-blockchain",
    title: "Decentralized Application Development", slug: "dapp-development",
    description: "Build full-stack dApps with React, ethers.js, and decentralized storage.",
    objectives: ["Connect to Ethereum with ethers.js", "Build dApp frontends", "Integrate with IPFS and Arweave", "Implement wallet connectivity"],
    prerequisites: ["Solidity & Smart Contracts"], level: "foundation", durationHours: 50, moduleCount: 5, totalLessons: 25,
    instructorId: "inst-3", instructorName: "Nana Yaw Boateng", instructorAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=nana",
    priceGHS: 700, enrolledCount: 56, rating: 4.8, reviewCount: 18, status: "published",
    thumbnail: "https://images.unsplash.com/photo-1639762681485-074b7f938ba0?w=600&q=80",
    tags: ["dapp", "web3", "ethers", "ipfs", "wallet"], modules: [], createdAt: "2026-08-05", updatedAt: "2026-08-28",
  },
  {
    id: "course-defi-protocols", programmeId: "prog-blockchain",
    title: "DeFi Protocol Development", slug: "defi-protocols",
    description: "Understand and build decentralized finance protocols — DEX, lending, staking.",
    objectives: ["Understand AMM and DEX mechanics", "Build lending protocol smart contracts", "Implement staking mechanisms", "Analyze DeFi security risks"],
    prerequisites: ["Solidity & Smart Contracts"], level: "foundation", durationHours: 45, moduleCount: 4, totalLessons: 22,
    instructorId: "inst-3", instructorName: "Nana Yaw Boateng", instructorAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=nana",
    priceGHS: 800, enrolledCount: 34, rating: 4.8, reviewCount: 12, status: "published",
    thumbnail: "https://images.unsplash.com/photo-1639762681485-074b7f938ba0?w=600&q=80",
    tags: ["defi", "dex", "lending", "staking", "protocols"], modules: [], createdAt: "2026-08-10", updatedAt: "2026-08-30",
  },
];

// ════════════════════════════════════════════════════════════════
// ALL NEW PROGRAMMES
// ════════════════════════════════════════════════════════════════

export const ALL_NEW_PROGRAMMES: Programme[] = [
  // Existing Foundation programmes get careerTier added
  // (updated in data.ts merge step)
  // Cybersecurity Path
  CYBER_INTERMEDIATE, CYBER_ADVANCED,
  // Software Engineering Path
  SE_INTERMEDIATE, SE_ADVANCED,
  // Cloud & Infrastructure Path
  CLOUD_INTERMEDIATE, CLOUD_ADVANCED,
  // New High-Demand Tech
  AI_ML_PROGRAMME,
  DATA_PROGRAMME,
  DEVSECOPS_PROGRAMME,
  MOBILE_PROGRAMME,
  BLOCKCHAIN_PROGRAMME,
];

export const ALL_NEW_COURSES: Course[] = NEW_COURSES;
