import {
  title, keyterms, bullets, steps, diagram, flow, code, terminal, compare, scenario, quiz, stat, recap,
  type LessonVideoScript,
} from "./core";

// ════════════════════════════════════════════════════════════════
// CLOUD COMPUTING — deep scripts (course-cloud-fundamentals)
// ════════════════════════════════════════════════════════════════

export const deepCloud: LessonVideoScript[] = [
  {
    lessonId: "les-cfnd-1-1",
    lessonTitle: "What is Cloud Computing?",
    scenes: [
      title({
        eyebrow: "Module 1 · Cloud Foundations",
        heading: "What is Cloud Computing?",
        sub: "The three service models, four pricing levers, and the shared responsibility model",
        goals: [
          "Define cloud computing and its six essential characteristics",
          "Compare IaaS, PaaS and SaaS with real examples",
          "Explain the shared responsibility model precisely",
          "Estimate cost using the four pricing levers",
        ],
        accent: "sky",
      }),
      keyterms([
        { term: "IaaS", definition: "Raw infrastructure: virtual machines, networks, storage — you manage the stack above.", color: "sky" },
        { term: "PaaS", definition: "A managed platform: the runtime, scaling and patching are someone else's problem.", color: "lime" },
        { term: "SaaS", definition: "Finished software over the web — you manage only configuration and users.", color: "amber" },
        { term: "On-demand self-service", definition: "Provision resources through an API or console, in minutes — no ticket queues.", color: "violet" },
        { term: "Shared responsibility", definition: "AWS secures the cloud; YOU secure what's inside it. Every layer has an owner.", color: "rose" },
      ], "The five terms that unlock every cloud conversation"),
      diagram({
        heading: "IaaS vs PaaS vs SaaS — who does what",
        sub: "Each row is a layer; the shaded band is what YOU manage",
        rows: [
          { label: "Application & data", detail: "on-prem: you · IaaS: you · PaaS: you · SaaS: provider", color: "amber" },
          { label: "Runtime & middleware", detail: "on-prem: you · IaaS: you · PaaS: provider · SaaS: provider", color: "sky" },
          { label: "OS & containers", detail: "on-prem: you · IaaS: you · PaaS: provider · SaaS: provider", color: "sky" },
          { label: "Compute, network, storage", detail: "on-prem: you · IaaS: provider · PaaS: provider · SaaS: provider", color: "lime" },
          { label: "Physical facilities", detail: "everyone: provider (or your DC)", color: "rose" },
        ],
      }, "Who manages what — the whole model on one slide"),
      steps({
        heading: "The six characteristics that define 'cloud'",
        sub: "If a vendor can't say yes to all six, it isn't cloud — it's hosting",
        steps: [
          { label: "1. on-demand", detail: "provision via API in minutes — no forms, no tickets", color: "lime" },
          { label: "2. broad access", detail: "you reach resources from anywhere, over standard networks", color: "sky" },
          { label: "3. pooling", detail: "many tenants share provider infrastructure — utilisation is the business model", color: "amber" },
          { label: "4. elasticity", detail: "scale up AND down with demand — you pay for what you use", color: "violet" },
          { label: "5. measured service", detail: "metering on every resource — the bill IS your capacity planning data", color: "rose" },
          { label: "6. economies of scale", detail: "the provider's bulk buying is your lower price", color: "cyan" },
        ],
      }, "The litmus test"),
      code({
        heading: "The shared responsibility model, honestly",
        sub: "The split depends on the service model — here's IaaS vs PaaS",
        lang: "text",
        codeLines: [
          "IaaS (EC2, VMs):",
          "  AWS: facilities · hardware · virtualization · network · patching the HYPERVISOR",
          "  YOU: OS patches · runtime & apps · data · firewalls INSIDE the OS",
          "        · IAM keys · backups · encryption configuration",
          "",
          "PaaS (RDS, Elastic Beanstalk):",
          "  AWS: + OS · runtime · DB engine patching · high-availability plumbing",
          "  YOU: your schema · your data · parameter groups · IAM · backups policy",
          "",
          "CATASTROPHIC ERROR: assume the provider handles your OS patching on IaaS.",
          "Unpatched EC2 instances are the #1 'we thought AWS did it' breach.",
        ],
        captions: [
          "responsibility is a spectrum — never assume, always check the model",
          "on IaaS, an unpatched OS is YOUR vulnerability inventory",
          "on PaaS, your schema, data and access policies are still your risk",
          "the shared model is why cloud security requires real architecture skills",
        ],
      }, "The model that defines blame"),
      compare({
        heading: "CapEx vs OpEx — why finance loves cloud",
        left: { label: "Traditional data centre", points: ["CapEx: buy servers years before need", "Capacity planning is forecasting", "Peak-provisioned, idle otherwise", "Quarterly procurement cycles"], verdict: "slow & wasteful", color: "rose" },
        right: { label: "Cloud", points: ["OpEx: pay per use, per hour/minute", "Elasticity matches actual demand", "No idle hardware you own", "Slider, not forecast"], verdict: "fast & flexible", color: "lime" },
      }, "The financial argument in one slide"),
      bullets({
        heading: "The four pricing levers",
        items: [
          { text: "compute pricing: on-demand vs reserved vs spot — 70% savings for commitment or flexibility", kind: "info" },
          { text: "storage tiers: standard / infrequent / archive — 90% cheaper for cold data", kind: "info" },
          { text: "networking: egress is the silent cost — data OUT of the cloud is the expensive direction", kind: "bad", note: "design so heavy traffic stays inside" },
          { text: "rightsizing: the #1 bill reduction is killing over-provisioned instances", kind: "good", note: "idle 4x-large is money on fire" },
        ],
      }, "Control cost; cost controls you"),
      scenario({
        heading: "Case study: the $18,000 forgotten snapshot",
        text: "A dev team left a 6-TB database snapshot scheduled nightly 'for safety' after a migration. No one ever deleted the old generation. Six months later, storage alone billed $18,000 a month — more than the entire production stack. Cost explorer showed the anomaly, but there was no budget alert. The fixes were two lines of policy: lifecycle rules expire snapshots after 30 days automatically, and billing alarms fire at 80% of budget. 'Who's responsible for cost?' is a shared-responsibility question too — and this team now answers it: everyone, automatically.",
      }, "Real-world postmortem"),
      quiz([
        { question: "You manage the OS, runtime and app. Which service model?", options: ["SaaS", "PaaS", "IaaS", "FaaS"], answer: 2, explain: "IaaS gives you the machine; everything above the hypervisor is yours, including patching." },
        { question: "Which direction of network traffic is the expensive one?", options: ["Ingress", "Egress", "Same-region east-west", "They're equal"], answer: 1, explain: "Egress — moving data OUT of the cloud — is billed; ingress is generally free." },
        { question: "On EC2 (IaaS), who patches the OS?", options: ["AWS automatically", "Nobody — EC2 is unpatched", "You", "The hypervisor vendor"], answer: 2, explain: "Shared responsibility: AWS patches the host and hypervisor; the guest OS is entirely yours." },
      ], "Check yourself: cloud fundamentals"),
      stat({
        heading: "Cloud economics in three numbers",
        stats: [
          { value: "~70%", label: "savings potential from reserved vs on-demand compute", color: "lime" },
          { value: "90%", label: "cheaper archive storage vs standard tiers", color: "amber" },
          { value: "#1", label: "cost killer: over-provisioned, under-utilised instances", color: "rose" },
        ],
      }, "Know the numbers, own the bill"),
      recap({
        points: [
          "Cloud = on-demand, broad-access, pooled, elastic, measured infrastructure",
          "IaaS/PaaS/SaaS shift the responsibility band — know who owns each layer",
          "Never assume: on IaaS your OS patching is not the provider's job",
          "CapEx → OpEx; elasticity is a cost feature, not just an ops one",
          "Watch egress, rightsize, lifecycle your data — cost is a design input",
        ],
      }),
    ],
  },
  {
    lessonId: "les-cfnd-2-1",
    lessonTitle: "EC2 / Virtual Machines",
    scenes: [
      title({
        eyebrow: "Module 2 · Compute",
        heading: "EC2 / Virtual Machines",
        sub: "Instances, AMIs, storage tiers and the decisions that set your bill on fire",
        goals: [
          "Choose instance families, sizes and purchase options deliberately",
          "Work with AMIs, EBS volumes and snapshots safely",
          "Use security groups as a firewall you can reason about",
          "Make instances disposable and data durable",
        ],
        accent: "sky",
      }),
      keyterms([
        { term: "Instance type", definition: "CPU/memory/network profile: general, compute, memory, storage optimised.", color: "sky" },
        { term: "AMI", definition: "Amazon Machine Image — a frozen boot drive: OS + your software, versioned.", color: "lime" },
        { term: "EBS", definition: "Network-attached block storage attached to your instance — your durable disk.", color: "amber" },
        { term: "Security group", definition: "The instance firewall: allow rules only, evaluated statefully.", color: "rose" },
        { term: "Reserved / Spot", definition: "Purchase options: commit for savings, or bid on spare capacity for ~90% off.", color: "violet" },
      ], "EC2 vocabulary that matters"),
      diagram({
        heading: "Anatomy of one EC2 instance",
        sub: "Let the instance be disposable; make the data survive",
        rows: [
          { label: "Instance (compute)", detail: "vCPU + RAM + ephemeral scratch disk — DEATH is expected; auto-scaling replaces it", color: "slate" },
          { label: "EBS root volume", detail: "your OS + data — detachable, snapshotable, survives instance death", color: "lime" },
          { label: "AMI", detail: "the golden image others spawn from — versioned, immutable, patched", color: "sky" },
          { label: "Security group", detail: "stateful allow-lists: 0.0.0.0/0:22 is a breach announcement", color: "rose" },
          { label: "Key pairs / IAM role", detail: "SSH keys for login; the instance's IAM role grants AWS permissions", color: "violet" },
        ],
      }, "Pets vs cattle, done properly"),
      steps({
        heading: "A hardened launch, in order",
        sub: "Every step below is a line in the checklist your audit will ask about",
        steps: [
          { label: "1. pick the family", detail: "general/c/m5 for web; compute/c6i for number crunching; memory/r6i for caches", color: "sky" },
          { label: "2. choose the AMI", detail: "Amazon Linux 2023 / Ubuntu LTS — patched base, pin the version", color: "amber" },
          { label: "3. size honestly", detail: "start small, scale on metrics — not on hope", color: "violet" },
          { label: "4. security groups", detail: "only needed ports, only needed sources — 22/3389 never from 0.0.0.0/0", color: "rose" },
          { label: "5. place the IAM role", detail: "secrets via SSM Parameter Store, never baked into the AMI", color: "lime" },
        ],
      }, "Launch checklist, without the panic"),
      terminal({
        heading: "The lifecycle commands",
        sub: "What you'll actually type in a recovery",
        prompt: "cloudops",
        commandLines: [
          "aws ec2 run-instances --image-id ami-0abc --instance-type t3.micro \\",
          "  --security-group-ids sg-1 --subnet-id subnet-1 --iam-instance-profile \\",
          "  Name=app-role",
          "aws ec2 create-snapshot --volume-id vol-0d1e        # backup BEFORE changes",
          "aws ec2 describe-instances --query 'Reservations[].Instances[].{Ip:PublicIpAddress,Id:InstanceId}'",
          "aws ec2 stop-instances --instance-ids i-0f00        # stop ≠ terminate",
          "aws ec2 terminate-instances --instance-ids i-0f00    # 💥 bill stops, data gone",
          "aws autoscaling update-auto-scaling-group --group-name web \\",
          "  --desired-capacity 2   # the ops knob",
        ],
        captions: [
          "an instance profile gives the machine permissions WITHOUT storing keys",
          "snapshot BEFORE destructive work — restore is your undo button",
          "stop keeps EBS (billed); terminate keeps nothing (bill stops)",
          "autoscaling is how you scale — and how you recover from a dead instance",
        ],
      }, "The commands that matter"),
      compare({
        heading: "On-demand vs Reserved vs Spot",
        left: { label: "On-demand", points: ["Pay hourly, no commitment", "Most flexible, most expensive", "Baseline workloads"], verdict: "default", color: "amber" },
        middle: { label: "Reserved / Savings Plan", points: ["1–3 year commitment", "~70% cheaper", "Predictable steady load — prod databases, API fleets"], verdict: "steady state", color: "lime" },
        right: { label: "Spot", points: ["Bid on spare capacity", "~90% cheaper, can be reclaimed", "Batch, rendering, CI runners"], verdict: "interruptible", color: "violet" },
      }, "Time to choose your purchase option"),
      bullets({
        heading: "EC2 bills that explode, and the fixes",
        items: [
          { text: "An 'experiment' left running for weeks — instance was a 4x-large", kind: "bad", note: "tag everything; alarm on cost per tag" },
          { text: "Snapshots accumulating nightly forever", kind: "bad", note: "lifecycle rules keep the last N" },
          { text: "EBS: gp3 GP3 default is cheaper than gp2 — migrate old volumes", kind: "good" },
          { text: "Data transfer: cross-AZ sync traffic adds up", kind: "bad", note: "keep chatty services in one AZ" },
        ],
      }, "Your bill reads back your design choices"),
      scenario({
        heading: "Case study: the pet that couldn't die",
        text: "A startup's 'production server' had been hand-configured over eighteen months — nobody could rebuild it from scratch. When a kernel update crashed it during peak, recovery took nine hours and two engineers improvising. The team rebuilt as cattle in two weekends: a packer AMI from code, EBS snapshots on a schedule, autoscaling with a health check, and all config in a repo. The next instance death — during launch day — was replaced automatically inside four minutes with zero user-visible downtime. The difference between 'it was working' and 'it works' is reproducibility.",
      }, "Real-world postmortem"),
      quiz([
        { question: "Which purchase option is ~90% cheaper but can be reclaimed?", options: ["On-demand", "Reserved", "Spot", "Savings Plan"], answer: 2, explain: "Spot rides spare capacity — great for batch and CI, never for a lonely database." },
        { question: "A security group should contain…", options: ["Deny rules and blocklists", "Allow rules only", "A copy of your firewall config", "Everything open, audited later"], answer: 1, explain: "Security groups are stateful allow-lists — the default-deny posture is built in." },
        { question: "How do you give an EC2 instance AWS permissions safely?", options: ["Bake access keys into the AMI", "Use an IAM instance role", "Email the keys to ops", "Set them in the security group"], answer: 1, explain: "Instance roles hand credentials to the metadata service automatically — no keys on disk." },
      ], "Check yourself: EC2"),
      recap({
        points: [
          "Instances are cattle: disposable compute, durable data (EBS + snapshots + AMIs)",
          "Family, size and purchase option are cost AND performance decisions",
          "Security groups are stateful allow-lists — least privilege per port per source",
          "Roles over keys; SSM/parameter store over baked secrets",
          "Tag, alarm, lifecycle: the bill is feedback on your architecture",
        ],
      }),
    ],
  },
  {
    lessonId: "les-cfnd-3-1",
    lessonTitle: "S3 & Object Storage",
    scenes: [
      title({
        eyebrow: "Module 3 · Storage",
        heading: "S3 & Object Storage",
        sub: "Buckets, keys, durability and the access misconfigurations behind most data breaches",
        goals: [
          "Explain S3's model: buckets, objects, keys, versioning",
          "Engineer durability with versioning, lifecycle and replication",
          "Lock down public access and reason about bucket policies",
          "Choose the right storage class per access pattern",
        ],
        accent: "sky",
      }),
      keyterms([
        { term: "Bucket", definition: "A global-namespace container (DNS-qualified) with its own policies, region and logging.", color: "sky" },
        { term: "Object key", definition: "The full path inside a bucket — 'photos/2026/jan/1.jpg'. The hierarchical URL is an illusion.", color: "lime" },
        { term: "Versioning", definition: "Every overwrite keeps the prior version — your undo, retention and audit history.", color: "amber" },
        { term: "Storage class", definition: "Standard / IA / Glacier — the trade between cost and retrieval latency.", color: "violet" },
        { term: "Bucket policy", definition: "JSON access rules attached to the bucket — where misconfigurations become breaches.", color: "rose" },
      ], "Object vocabulary in five terms"),
      diagram({
        heading: "How an object gets found",
        sub: "s3://bucket + key + version = one object, three coordinates",
        rows: [
          { label: "bucket", detail: "must be globally unique — the DNS name — with region, policy, encryption defaults", color: "sky" },
          { label: "key", detail: "'uploads/2026/03/report.pdf' — folders are just keys with slashes", color: "lime" },
          { label: "object data", detail: "up to 5 TB, stored 11 nines of durability across AZs", color: "amber" },
          { label: "metadata", detail: "content-type, tags, encryption headers, user metadata", color: "violet" },
          { label: "version id", detail: "auto-generated on write when versioning is on — the undo layer", color: "rose" },
        ],
      }, "Three coordinates, one object"),
      code({
        heading: "The access policies, side by side",
        sub: "Read the JSON; trust the principle of least privilege",
        lang: "json",
        codeLines: [
          "// ❌ the one behind headline breaches:",
          "{ \"Effect\": \"Allow\", \"Principal\": \"*\", \"Action\": \"s3:GetObject\",",
          "  \"Resource\": \"arn:aws:s3:::corp-data/*\" }   // public GET, world",
          "",
          "// ✅ locked, least-privilege server-side default:",
          "{ \"Effect\": \"Deny\", \"Principal\": \"*\", \"Action\": \"s3:*\",",
          "  \"Resource\": \"*\", \"Condition\": { \"Bool\": { \"aws:SecureTransport\": \"false\" } } }",
          "",
          "// ✅ app role only, no wildcard principals:",
          "{ \"Effect\": \"Allow\", \"Principal\": { \"AWS\": \"arn:aws:iam::1234:role/app\" },",
          "  \"Action\": \"s3:GetObject\", \"Resource\": \"arn:aws:s3:::corp-data/*\" }",
        ],
        captions: [
          "Principal \"*\" + GetObject = your data is one URL discovery away from the internet",
          "a Deny for non-TLS turns off HTTP access to the bucket",
          "scoped roles and explicit ARNs are the difference between policy and permission",
          "default-deny public access + Block Public Access stays ON unless you prove otherwise",
        ],
      }, "Policies, read like the contract they are"),
      steps({
        heading: "The resilience ladder",
        sub: "Each rung adds protection and costs a little more",
        steps: [
          { label: "1. versioning on", detail: "undo deletes & overwrites — costs pennies, saves careers", color: "lime" },
          { label: "2. lifecycle", detail: "standard → IA after 30 days → Glacier after 90 → expire at 365", color: "sky" },
          { label: "3. MFA delete", detail: "destructive deletes need the DELETE badge — insider defence", color: "amber" },
          { label: "4. cross-region replication", detail: "survive an entire region event; pair with failover procedures", color: "violet" },
          { label: "5. test the restore", detail: "a backup you've never restored is a rumour", color: "rose" },
        ],
      }, "Durability is engineered, not purchased"),
      compare({
        heading: "Choosing the storage class",
        left: { label: "Hot data", points: ["S3 Standard: instant, millisecond", "IA: cheaper storage, charge per retrieval", "Right for active products, analytics"], verdict: "instant access", color: "lime" },
        right: { label: "Cold data", points: ["Glacier Flexible: ~$0.0036/GB, minutes to restore", "Glacier Deep Archive: cheapest, ~12h", "Right for compliance archives & backups"], verdict: "save ~90%", color: "slate" },
      }, "The access-vs-cost slider"),
      bullets({
        heading: "S3 security instinct checklist",
        items: [
          { text: "Block Public Access at the ACCOUNT level — the universal defence", kind: "good" },
          { text: "Default encryption (SSE-S3/KMS) — encrypted at rest by default, no exceptions", kind: "good" },
          { text: "Server access logging or CloudTrail data events for forensics", kind: "good" },
          { text: "Presigned URLs for sharing: time-limited, scope-limited — never public read", kind: "good" },
          { text: "A scanner (s3audit, ScoutSuite) in CI: misconfigured buckets get flagged before deploy", kind: "good" },
        ],
      }, "The checklist that prevents the headline"),
      scenario({
        heading: "Case study: the bucket that taught an industry",
        text: "A company whose product was 'secure data storage' left an S3 bucket public with a wildcard GetObject policy, intending 'website assets'. Crawlers indexed it: customer records, backups, internal keys. The breach notification, remediation and legal costs dwarfed a decade of the savings the misconfiguration 'convenience' was worth. The industry rule since: Block Public Access ON by default, buckets private unless a reviewed, narrowly-scoped policy says otherwise, and automated scans in every pipeline. S3 is secure by default — every breach is a policy someone wrote.",
      }, "Real-world postmortem"),
      quiz([
        { question: "What does enabling versioning buy you?", options: ["Faster uploads", "Undo for overwrites/deletes + audit history", "Cheaper storage", "Automatic encryption"], answer: 1, explain: "Each overwrite keeps the prior version — accidental deletes and bad writes become recoverable, with a paper trail." },
        { question: "Which policy shape is behind most S3 breach headlines?", options: ["Deny non-TLS", "Principal: '*' + GetObject on sensitive data", "Scoped role access", "Versioning disabled"], answer: 1, explain: "A wildcard principal plus read allows anyone to enumerate and download objects." },
        { question: "Compliance data read once a year should live in…", options: ["Standard", "S3-IA", "Glacier Flexible or Deep Archive", "EBS"], answer: 2, explain: "Cold classes trade long retrieval latency for ~90% lower storage cost — perfect for archives." },
      ], "Check yourself: S3"),
      stat({
        heading: "Object storage by the numbers",
        stats: [
          { value: "11 9's", label: "of durability designed into S3", color: "lime" },
          { value: "90%", label: "cost saved moving archives to Glacier", color: "amber" },
          { value: "#1", label: "cloud misconfiguration behind public data exposure", color: "rose" },
        ],
      }, "Durable, cheap, and only as safe as its policies"),
      recap({
        points: [
          "Buckets + keys + versions: three coordinates address every object",
          "Versioning, lifecycle, MFA delete, replication — durability is engineered",
          "Block Public Access ON; wildcard principals are a breach headline",
          "Storage class is an access-vs-cost decision — archives don't need milliseconds",
          "Test the restore: a backup never restored is a rumour",
        ],
      }),
    ],
  },
  {
    lessonId: "les-cfnd-3-2",
    lessonTitle: "RDS & Managed Databases",
    scenes: [
      title({
        eyebrow: "Module 3 · Storage",
        heading: "RDS & Managed Databases",
        sub: "The managed database you never trust 'as it is', and every knob that matters",
        goals: [
          "Provision RDS with the right engine, size and instance class",
          "Configure Multi-AZ, backups, and maintenance windows correctly",
          "Encrypt data at rest and in transit; rotate credentials",
          "Reason about failover and what it means for connections",
        ],
        accent: "sky",
      }),
      keyterms([
        { term: "RDS", definition: "AWS's managed relational database: Postgres, MySQL, SQL Server, Aurora.", color: "sky" },
        { term: "Multi-AZ", definition: "A synchronous standby in another AZ — failover in typically a minute.", color: "lime" },
        { term: "Automated backup", definition: "Daily snapshots + transaction logs — point-in-time recovery to any second.", color: "amber" },
        { term: "Parameter group", definition: "Engine settings (timeouts, max_connections) applied safely without manual SQL.", color: "violet" },
        { term: "Read replica", definition: "A read-only copy offloading SELECT traffic — write scaling stays on the main.", color: "rose" },
      ], "Managed-database vocabulary"),
      diagram({
        heading: "A well-configured RDS, end to end",
        sub: "Every box is a decision you make, not a default you inherit",
        rows: [
          { label: "App instances", detail: "in a private subnet, connecting via the DB endpoint — no public access", color: "sky" },
          { label: "RDS primary", detail: "Multi-AZ · encrypted (KMS) · automated backups 35 days · parameter group", color: "lime" },
          { label: "Synchronous standby", detail: "the AZ that takes over when the primary fails — same data, same second", color: "amber" },
          { label: "Read replica(s)", detail: "advanced reads · reporting · can become the failover target", color: "violet" },
          { label: "Snapshots → S3", detail: "manual + automated — the restore path you must rehearse", color: "rose" },
        ],
      }, "The full topology"),
      steps({
        heading: "Provisioning decisions, in order",
        sub: "Each is auditable and each has a wrong default to avoid",
        steps: [
          { label: "engine & version", detail: "Postgres 16/17 LTS unless a legacy constraint says otherwise", color: "sky" },
          { label: "instance class", detail: "start r6i.xlarge-ish for prod; scale on metrics", color: "amber" },
          { label: "storage", detail: "gp3 with IOPS headroom; enable autoscaling or alarm early", color: "violet" },
          { label: "Multi-AZ + backups", detail: "ON for anything with users; retention ≥ 7 days; PITR on", color: "lime" },
          { label: "security", detail: "private subnet · SG allowlist · TLS required · KMS encryption", color: "rose" },
        ],
      }, "The provisioning checklist"),
      code({
        heading: "The settings that get reviewed at audit",
        sub: "Many teams pass these, then fail the connection-level checks",
        lang: "text",
        codeLines: [
          "ENCRYPTION AT REST:  ON (KMS — check 'Storage encrypted: Yes')",
          "ENCRYPTION IN TRANSIT: sslmode=verify-full on the client",
          "   // never: sslmode=disable  (cleartext passwords on the wire)",
          "BACKUPS:           automated, retention 7–35 days, PITR enabled",
          "PUBLIC ACCESS:     OFF — the DB has no public endpoint",
          "PASSWORD ROTATION: secrets-managed, rotated quarterly, humans never see them",
          "PARAMETER GROUP:   max_connections sized to instance class — not default guessing",
          "",
          "FAILOVER REALITY:  connections drop during failover (~60s).",
          "   browsers/scripts must reconnect — retry with backoff, they don't 'ride through'.",
        ],
        captions: [
          "encryption is configured at creation — adding it later requires migration",
          "TLS in transit is a client-side decision too: sslmode=verify-full or nothing",
          "PITR turns your backups into rewind-to-13:42:00, not just restore-to-last-night",
          "failover drops connections — the app must retry, or fails are silent",
        ],
      }, "The audit checklist"),
      compare({
        heading: "RDS vs Aurora — the honest fork",
        left: { label: "RDS (Postgres/MySQL)", points: ["Simplest managed model", "Single writer + replicas", "Classic Multi-AZ failover"], verdict: "default choice", color: "lime" },
        right: { label: "Aurora", points: ["Storage distributed across 3 AZs", "Faster failover, auto-scaling reads", "Up to 15 replicas, serverless option"], verdict: "when scale demands", color: "violet" },
      }, "Choose the managed service that fits the load curve"),
      bullets({
        heading: "Database failure stories you can borrow",
        items: [
          { text: "Auto-scaling app, non-scaling DB: replicas TOOK the new traffic and read-replica lag became data drift", kind: "bad", note: "replicas serve reads; writes still hit one writer" },
          { text: "No connection retry: failover cost six minutes of 5xxs because clients didn't reconnect", kind: "bad", note: "retry with backoff is part of the app" },
          { text: "Parameter group applied during peak: a connection timeout fired every query for 20 minutes", kind: "bad", note: "apply parameter changes in maintenance windows" },
          { text: "Weekly snapshot 'policy' with no restoration test: the DR drill failed — backup was missing 3 days", kind: "bad", note: "scheduled restore drills are a KPI" },
        ],
      }, "Each of these happened in production"),
      scenario({
        heading: "Case study: the failover nobody had rehearsed",
        text: "A health SaaS ran RDS Multi-AZ for a year without a single failover. During a routine AZ maintenance, the primary failed over — and the entire API went down for nine minutes. The app's connection pool held stale endpoints; lazy users' pools sat dead with no retry; the on-call engineer had never run a manual failover drill. The fix: connection pooling with retry, a load-test that performs RDS failover mid-traffic quarterly, and a runbook. The next AZ event, during a real outage elsewhere — zero user-visible impact. Drills turn surprises into rehearsals.",
      }, "Real-world postmortem"),
      quiz([
        { question: "What does Multi-AZ actually provide?", options: ["Read scaling", "A synchronous standby with automatic failover", "Two databases for the price of one", "Backup storage"], answer: 1, explain: "It's high availability — a hot standby, not extra read capacity or a second schema." },
        { question: "What happens to live connections during failover?", options: ["Nothing — they ride through", "They drop and must reconnect", "They're migrated silently", "They keep their transactions"], answer: 1, explain: "The standby takes over the endpoint; established sockets die — clients must retry with backoff." },
        { question: "How do you read-scale an RDS Postgres?", options: ["Add another primary", "Provision read replicas and route SELECTs to them", "Enable Multi-AZ", "Increase max_connections"], answer: 1, explain: "Replicas offload reads; writes still go to the single writer." },
      ], "Check yourself: RDS"),
      recap({
        points: [
          "Provision deliberately: engine, class, storage, Multi-AZ, backup retention",
          "Encrypt at rest (KMS) and force TLS in transit (sslmode=verify-full)",
          "Failover drops connections — retry with backoff is a feature of your app",
          "Parameter changes in maintenance windows; read replication, not write splitting",
          "Rehearse restore and failover quarterly — drills turn surprises into rehearsals",
        ],
      }),
    ],
  },
  {
    lessonId: "les-cfnd-4-1",
    lessonTitle: "IAM & Access Management",
    scenes: [
      title({
        eyebrow: "Module 4 · Security",
        heading: "IAM & Access Management",
        sub: "Users, roles, policies and the least-privilege discipline that prevents the worst days",
        goals: [
          "Model identity: users, groups, roles, and when each applies",
          "Write least-privilege policies with conditions and scopes",
          "Use roles for AWS-to-AWS access — never static keys",
          "Audit with Access Analyzer and CloudTrail",
        ],
        accent: "sky",
      }),
      keyterms([
        { term: "IAM user", definition: "A long-term identity for humans or machines — with static credentials you must manage.", color: "sky" },
        { term: "IAM role", definition: "A temporary-credential identity assumed by services, EC2, lambdas or federated users.", color: "lime" },
        { term: "Policy", definition: "JSON allow/deny rules with Actions, Resources, Conditions — the unit of permission.", color: "amber" },
        { term: "Least privilege", definition: "Exactly the permissions needed, nothing more — reviewed as code changes.", color: "violet" },
        { term: "Trust policy", definition: "WHO may assume the role; the permission policy states WHAT they get.", color: "rose" },
      ], "IAM vocabulary, precisely"),
      flow({
        heading: "How access is decided",
        sub: "One request; every gate must open",
        nodes: [
          { id: "a", label: "API request", shape: "pill", color: "sky" },
          { id: "b", label: "authenticated?", shape: "diamond", color: "amber" },
          { id: "c", label: "effective policy", shape: "rect", color: "lime" },
          { id: "d", label: "explicit deny?", shape: "diamond", color: "rose" },
          { id: "e", label: "allow matched?", shape: "diamond", color: "amber" },
          { id: "f", label: "ALLOWED", shape: "pill", color: "lime" },
          { id: "g", label: "DENIED", shape: "pill", color: "rose" },
        ],
        edges: [ { from: "a", to: "b" }, { from: "b", to: "c" }, { from: "c", to: "d" }, { from: "d", to: "g", animated: true }, { from: "d", to: "e" }, { from: "e", to: "f" }, { from: "e", to: "g", animated: true } ],
      }, "Deny always wins — remember that diagram"),
      code({
        heading: "Least privilege, written out",
        sub: "A role for an app server that reads a bucket and logs",
        lang: "json",
        codeLines: [
          "{",
          "  \"Version\": \"2012-10-17\",",
          "  \"Statement\": [{",
          "    \"Effect\": \"Allow\",",
          "    \"Action\": [",
          "      \"s3:GetObject\",          // read ONLY — no List, no Put, no Delete",
          "      \"s3:GetBucketLocation\"",
          "    ],",
          "    \"Resource\": [",
          "      \"arn:aws:s3:::assets-bucket-prod\",",
          "      \"arn:aws:s3:::assets-bucket-prod/*\"",
          "    ],",
          "    \"Condition\": {",
          "      \"StringEquals\": { \"aws:ResourceTag/team\": \"platform\" }",
          "    }",
          "  }]",
          "}",
          "",
          "// ❌ anti-pattern: Action: \"s3:*\" on Resource: \"*\" — a terminal",
          "//    vulnerability for a role that only reads one bucket",
        ],
        captions: [
          "scoped actions: GetObject, not s3:* — the blast radius is one operation",
          "scoped resources: one bucket, not * — the blast radius is one bucket",
          "conditions add context: this policy only works from this team's workloads",
          "s3:* on * is the classic 'expired quickly' policy that never got pruned",
        ],
      }, "Policies are blast-radius statements"),
      compare({
        heading: "Long-term users vs roles",
        left: { label: "IAM users / keys", points: ["Static credentials — live forever until rotated", "Credential leakage is game over", "Use ONLY for: humans via console (MFA), rare external integrations"], verdict: "minimise", color: "rose" },
        right: { label: "Roles (assume)", points: ["Temporary credentials (≤12h, auto-renewed)", "No secret to leak — nothing is stored", "EC2/lambda/ECS/CodePipeline: default choice"], verdict: "prefer everywhere", color: "lime" },
      }, "The credential-management fork"),
      steps({
        heading: "The IAM hygiene routine",
        sub: "Quarterly, automated where possible",
        steps: [
          { label: "1. Access Analyzer", detail: "surfaces 'this role could be assumed from outside your account'", color: "lime" },
          { label: "2. unused keys", detail: "CloudTrail + last-used: delete keys unused > 90 days", color: "sky" },
          { label: "3. review wildcards", detail: "IAMLive / policy-sentinel flag s3:* and * patterns", color: "amber" },
          { label: "4. MFA everywhere", detail: "console users forced, roles condition on MultiFactorAuthPresent: true", color: "violet" },
          { label: "5. rotate root", detail: "root account: MFA + offline key, alias disabled, never used daily", color: "rose" },
        ],
      }, "Prevention, not detection"),
      bullets({
        heading: "The 2024-2026 attack patterns IAM stops",
        items: [
          { text: "Stolen dev keys used to exfiltrate production buckets — hostile takeovers start with one over-permissioned key", kind: "bad" },
          { text: "A lambda role with s3:* nuked the company's backups during a compromised pipeline", kind: "bad" },
          { text: "Over-permissioned EC2 instance roles were pivoted onto to reach the metadata endpoint", kind: "bad" },
          { text: "Roles without trust bounds: any identity in the account could assume them", kind: "bad" },
          { text: "The defence is the same: policies scoped by action, resource and condition, and roles over keys", kind: "good" },
        ],
      }, "Every one of these has a breach report"),
      scenario({
        heading: "Case study: the key in the public repo",
        text: "A startup's engineer pasted a copy-pasted 'serverless example' that loaded AWS keys from a .env — committed it, pushed to a public repo, and forgot. Within 12 hours a scanner found the key and began launching GPU instances for crypto-mining: $14,000 in 48 hours, plus a suspended account. The postmortem rewrote policy company-wide: keys never in code or env, IAM roles everywhere, a scanner in CI that refuses any push containing an AKIA pattern, and budgets with alarms on EVERY account. The 48-hour bill became the tuition for a policy that has held for years since.",
      }, "Real-world postmortem"),
      quiz([
        { question: "How does the AWS decision engine treat an explicit deny?", options: ["It can be overridden by an allow", "It always wins", "It applies only within the same policy", "It's advisory"], answer: 1, explain: "Explicit deny outranks any allow — that's the first gate in the evaluation flow." },
        { question: "Which identity should an application server use to reach S3?", options: ["An IAM user with static keys", "An IAM role attached to the instance", "The root account", "A service-linked user"], answer: 1, explain: "Roles mint temporary, rotating credentials — nothing to leak, nothing to rotate." },
        { question: "What does IAM Access Analyzer surface?", options: ["Performance issues", "Policies that could be accessed from outside your account boundary", "Database slow queries", "Expired certificates"], answer: 1, explain: "It reasons about external access — your lead on where blast radius leaked outward." },
      ], "Check yourself: IAM"),
      stat({
        heading: "IAM by the numbers",
        stats: [
          { value: "12h", label: "max lifetime of role-issued temporary credentials", color: "lime" },
          { value: "90d", label: "and unused key = delete (CloudTrail-assisted)", color: "amber" },
          { value: "0", label: "static keys you should need in today's apps", color: "rose" },
        ],
      }, "Temporary, scoped, auditable"),
      recap({
        points: [
          "Users for humans (with MFA), roles for machines — static keys are a last resort",
          "Policy = action + resource + condition: each line defines a blast radius",
          "Explicit deny always wins; least privilege is reviewed, not intended",
          "Automate hygiene: Access Analyzer, unused-key deletion, wildcard scans",
          "Root account: MFA + alias off + emergency-only",
        ],
      }),
    ],
  },
];