import {
  title, keyterms, bullets, steps, diagram, flow, code, terminal, compare, scenario, quiz, stat, recap,
  type LessonVideoScript,
} from "./core";

// ════════════════════════════════════════════════════════════════
// CONTAINERS & KUBERNETES — deep scripts (course-containers-k8s)
// ════════════════════════════════════════════════════════════════

export const deepContainers: LessonVideoScript[] = [
  {
    lessonId: "les-ct-1-1",
    lessonTitle: "Why Containers?",
    scenes: [
      title({
        eyebrow: "Module 1 · Container Foundations",
        heading: "Why Containers?",
        sub: "Namespaces, image layers, and the reproducible deployment model that ate the world",
        goals: [
          "Explain what a container is: processes isolated by namespaces + cgroups",
          "Understand image layers and how Docker builds caches",
          "Run containers with the right flags: ports, env, volumes, health checks",
          "Write a production-quality Dockerfile with a non-root user",
        ],
        accent: "cyan",
      }),
      keyterms([
        { term: "Namespace", definition: "The kernel mechanism isolating process views — PIDs, network, filesystem, users.", color: "lime" },
        { term: "cgroup", definition: "The kernel mechanism limiting resources — CPU, memory, I/O per container.", color: "sky" },
        { term: "Image layer", definition: "A filesystem delta recorded by the build — shared, cached, immutable.", color: "amber" },
        { term: "Registry", definition: "The image store (Docker Hub, ECR, GHCR) — pull images, push builds.", color: "violet" },
        { term: "Non-root user", definition: "The container runtime user — root inside a container goes deeper than most think.", color: "rose" },
      ], "Container vocabulary in five bits"),
      diagram({
        heading: "What a container actually is",
        sub: "One kernel, many isolated gardens — each garden sees its own world",
        rows: [
          { label: "Process (PID 1 in its namespace)", detail: "the app — sees only its own process tree", color: "sky" },
          { label: "Namespaces", detail: "isolated PIDs · network stack · mounts · UIDs · hostname", color: "amber" },
          { label: "cgroups", detail: "memory limit 512Mi · CPU shares · I/O weight — enforced by the kernel", color: "lime" },
          { label: "Its own filesystem", detail: "image layers, read-only + writable top layer — no host files unless mounted", color: "violet" },
          { label: "Shared host kernel", detail: "the kernel is NOT namespaced — kernel bugs affect all containers", color: "rose" },
        ],
      }, "Isolation is a kernel feature, not a VM"),
      code({
        heading: "A Dockerfile that passes review",
        sub: "Multi-stage, pinned base, non-root, HEALTHCHECK — the checklist matters",
        lang: "dockerfile",
        codeLines: [
          "FROM node:22-alpine AS build",
          "WORKDIR /app",
          "COPY package*.json ./",
          "RUN npm ci",
          "COPY . .",
          "RUN npm run build",
          "",
          "FROM node:22-alpine        # runtime: second stage, smaller",
          "ENV NODE_ENV=production",
          "COPY --from=build /app/dist ./dist",
          "COPY --from=build /app/node_modules ./node_modules",
          "RUN addgroup -S app && adduser -S app -G app",
          "USER app                   # non-root: the default that's actually secure",
          "EXPOSE 3000",
          "HEALTHCHECK --interval=30s CMD wget -qO- http://127.0.0.1:3000/health || exit 1",
          "CMD [\"node\", \"dist/server.js\"]",
        ],
        captions: [
          "multi-stage builds shrink images — build tools never reach runtime",
          "pinned base versions (22-alpine) make builds reproducible, not floating",
          "USER app: root inside a container can escape via misconfigured mounts",
          "HEALTHCHECK gives orchestrators a survival signal — or K8s kills the container",
        ],
      }, "The produced-quality pattern"),
      terminal({
        heading: "The commands you'll type daily",
        sub: "Build, run, inspect, clean",
        prompt: "devbox:~",
        commandLines: [
          "docker build -t myapp:1.2.3 .",
          "docker run -d --name api -p 3000:3000 \\",
          "  -e NODE_ENV=production -v ./data:/data myapp:1.2.3",
          "docker logs -f api",
          "docker exec -it api sh          # debugging inside",
          "docker image prune -a           # reclaim the layer cache",
        ],
        captions: [
          "-p maps the host port to the container's — the only way in",
          "-e injects env; -v mounts a volume — the data that survives restarts",
          "logs and exec are your daily tools — log to stdout, not files",
        ],
      }, "Daily driver commands"),
      compare({
        heading: "Containers vs VMs",
        left: { label: "VM", points: ["Full guest OS per instance", "Strong isolation boundary", "GBs, starts in minutes", "More secure isolation, more overhead"], verdict: "isolation boundary", color: "amber" },
        right: { label: "Container", points: ["Shared host kernel", "Namespaces isolate processes", "MBs, starts in seconds", "Perfect for many replicas"], verdict: "density & speed", color: "lime" },
      }, "Choose the isolation level you actually need"),
      bullets({
        heading: "Container security instincts",
        items: [
          { text: "Non-root user in the image — the single highest-value line in your Dockerfile", kind: "good" },
          { text: "Never bake secrets into images — env at run time, secrets via the orchestrator", kind: "bad", note: "'docker history' leaks baked secrets" },
          { text: "Scan images in CI (Trivy/Snyk) and gate on critical findings", kind: "good" },
          { text: "read_only_root_filesystem + no-new-privileges where the app allows", kind: "good" },
          { text: "Distroless or alpine bases shrink attack surface and CVEs", kind: "info" },
        ],
      }, "The checklist that matters"),
      scenario({
        heading: "Case study: root-in-a-container and the mounted socket",
        text: "A team ran its CI container as root (the default) and mounted the Docker socket so builds could build. A compromised dependency inside the container used the socket to issue `docker run --privileged` against the host — container escape, full host compromise, credentials extracted. The fix stack: non-root USER in the image, the Docker socket mount removed entirely (Kaniko/buildkit instead), and a hardened runtime profile. The lesson: containers don't contain everything — root plus privileged access defeats the model.",
      }, "Real-world postmortem"),
      quiz([
        { question: "What isolates a container's PROCESS VIEW (its PID and network)?", options: ["cgroups", "Namespaces", "The image", "Docker daemon"], answer: 1, explain: "Namespaces give each container its own view of processes, network stack, mounts; cgroups limit resources." },
        { question: "Why do multi-stage builds matter?", options: ["They're faster to write", "Build tools don't ship to runtime — smaller, less attack surface", "They use fewer CPUs", "Docker requires them"], answer: 1, explain: "Runtime images carry only what runs — no compilers, no dev deps, fewer CVEs." },
        { question: "Where should secrets live for a container?", options: ["In the image", "In the Dockerfile", "Injected at run time (env/secrets mount)", "In the registry"], answer: 2, explain: "The image is inspected by anyone with pull access — secrets must never be baked in." },
      ], "Check yourself: containers"),
      stat({
        heading: "Container economics",
        stats: [
          { value: "s", label: "container cold start, vs minutes for a VM", color: "lime" },
          { value: "MB", label: "runtime images, vs GB for VM disks", color: "amber" },
          { value: "1", label: "kernel, sizes for thousands of isolated processes", color: "rose" },
        ],
      }, "Density and speed, at the cost of discipline"),
      recap({
        points: [
          "Containers are namespaced, cgroup-limited processes sharing one kernel",
          "Image layers are immutable deltas — multi-stage builds keep runtime small",
          "Run: non-root, no baked secrets, healthchecks, logs to stdout",
          "Never mount the Docker socket; scan images in CI",
          "Containers ≠ VMs — isolation is process-level, choose accordingly",
        ],
      }),
    ],
  },
  {
    lessonId: "les-ct-2-1",
    lessonTitle: "Docker Compose Fundamentals",
    scenes: [
      title({
        eyebrow: "Module 1 · Container Foundations",
        heading: "Docker Compose Fundamentals",
        sub: "Declaring whole stacks — services, networks, volumes and env — in one reviewable file",
        goals: [
          "Model multi-container apps: services, networks, volumes, depends_on",
          "Inject environment per service with default overrides",
          "Debug with logs, exec and profiles",
          "Keep compose safe for production use",
        ],
        accent: "cyan",
      }),
      keyterms([
        { term: "Service", definition: "One container definition — image, ports, env, volumes, healthcheck, scale.", color: "lime" },
        { term: "Network", definition: "An isolated bridge — services talk by service name, not IP.", color: "sky" },
        { term: "Volume", definition: "Named persistent storage surviving container recreation.", color: "amber" },
        { term: "depends_on", definition: "Start-order hint — with condition: service_healthy, a real dependency gate.", color: "violet" },
        { term: "Profile", definition: "Opt-in groups of services — 'compose --profile dev up' adds them.", color: "rose" },
      ], "Compose vocabulary"),
      code({
        heading: "A full dev stack, one file",
        sub: "Postgres + Redis + API, wired and reviewable",
        lang: "yaml",
        codeLines: [
          "services:",
          "  db:",
          "    image: postgres:16",
          "    env_file: .env",
          "    volumes: [dbdata:/var/lib/postgresql/data]",
          "    healthcheck:",
          "      test: [\"CMD\", \"pg_isready\", \"-U\", \"${POSTGRES_USER}\"]",
          "      interval: 5s",
          "",
          "  redis:",
          "    image: redis:7-alpine",
          "",
          "  api:",
          "    build: .",
          "    ports: [\"3000:3000\"]",
          "    environment:",
          "      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/app",
          "      REDIS_URL: redis://redis:6379",
          "    depends_on:",
          "      db: { condition: service_healthy }   # real gating",
          "      redis: { condition: service_started }",
          "",
          "volumes:",
          "  dbdata:",
        ],
        captions: [
          "service names are DNS — 'db' and 'redis' resolve inside the compose network",
          "named volumes survive down/up — the database isn't wiped by compose down",
          "healthchecks plus depends_on make startup deterministic, not raced",
          "env_file/.env keeps secrets out of the compose file itself",
        ],
      }, "The pattern, line by line"),
      terminal({
        heading: "The compose command set",
        sub: "Start/recreate/log/exec — and the flags that matter",
        prompt: "devbox:~/stack",
        commandLines: [
          "docker compose up -d                 # start detached",
          "docker compose up -d --build api     # rebuild one service",
          "docker compose ps                    # state + health",
          "docker compose logs -f api           # follow one service",
          "docker compose exec api sh           # shell inside",
          "docker compose down -v               # ⚠️ ALSO deletes volumes",
          "docker compose --profile dev up -d   # opt-in services",
        ],
        captions: [
          "--build rebuilds code changes without recreating the stack",
          "down -v destroys named volumes — the data nuke; know it before using it",
          "profiles let you start 'core' vs 'core + maildev + adminer'",
        ],
      }, "Your daily loop"),
      compare({
        heading: "Compose vs K8s — know the boundary",
        left: { label: "Docker Compose", points: ["One host, dev/preview stacks", "Simple, fast feedback", "No automatic recovery/scale", "Good for local, staging, small prod"], verdict: "dev & small prod", color: "lime" },
        right: { label: "Kubernetes", points: ["Clusters, self-healing, scaling", "Steep learning curve", "Complexity is real cost", "Production at scale"], verdict: "prod at scale", color: "violet" },
      }, "Grow into K8s with evidence, not fashion"),
      bullets({
        heading: "Compose mistakes that bite",
        items: [
          { text: "No healthchecks + no condition → the API races the DB on every start", kind: "bad", note: "intermittent 'connection refused' startup" },
          { text: "Volumes for node_modules from the host — platform drift between Mac and Linux CI", kind: "bad", note: "use anonymous volumes or bind carefully" },
          { text: "Committed .env with real secrets → the repo leaks them", kind: "bad", note: ".env.example committed, .env ignored" },
          { text: "Exposing every service port to localhost → 3000-3010 junk", kind: "bad", note: "expose only what you need" },
          { text: "compose down -v on the prod-ish stack 'to clean up'", kind: "bad", note: "read the -v warning, twice" },
        ],
      }, "Each one has a postmortem"),
      scenario({
        heading: "Case study: the startup race that chased ghosts",
        text: "A team's local API intermittently failed its first ten seconds with 'ECONNREFUSED', mysteriously healing on retry. The API started before Postgres was ready; connection pooling retried blindly and worked eventually — so nobody fixed the root cause until a code change slowed startup and the failure became permanent. The fix: a healthcheck on the DB service and depends_on with condition: service_healthy. Startup became deterministic, and the same pattern they added to CI reduced flaky test rate from ~8% to zero within a week. Races are the cheapest kind of bug to prevent and the most expensive to chase.",
      }, "Real-world postmortem"),
      quiz([
        { question: "How do services reach each other in compose?", options: ["By IP address", "By service name (DNS)", "Via the host network", "They can't"], answer: 1, explain: "Compose creates a network where each service's name resolves — no IP bookkeeping." },
        { question: "What does down -v delete that down doesn't?", options: ["Images", "Named volumes — data included", "The network", "Config files"], answer: 1, explain: "-v removes named volumes — the database data. The nuclear option." },
        { question: "Why add healthchecks to dependencies?", options: ["It's required by Docker", "depends_on + service_healthy gates startup on readiness", "They speed startup", "They replace port mapping"], answer: 1, explain: "Conditional depends_on turns 'started' into 'ready' — killing startup races." },
      ], "Check yourself: compose"),
      recap({
        points: [
          "One YAML declares the whole stack: services, networks, volumes, env",
          "Healthchecks + depends_on kill startup races",
          "Named volumes preserve data; down -v deletes it — know the difference",
          "Secrets via .env/.env_file, committed examples only",
          "Compose is a dev/small-prod tool — reach for K8s with evidence",
        ],
      }),
    ],
  },
  {
    lessonId: "les-ct-3-1",
    lessonTitle: "Kubernetes Architecture",
    scenes: [
      title({
        eyebrow: "Module 2 · Kubernetes",
        heading: "Kubernetes Architecture",
        sub: "Control plane, nodes, pods, deployments — the moving parts, named honestly",
        goals: [
          "Describe the control plane and worker node components",
          "Define pod, deployment, service and ingress roles",
          "Use the reconciliation loop model (desired vs actual)",
          "Apply labels and selectors as the wiring of the system",
        ],
        accent: "cyan",
      }),
      keyterms([
        { term: "Control plane", definition: "The brain: API server, scheduler, controller manager, etcd — decision-makers.", color: "lime" },
        { term: "Node", definition: "A worker machine running kubelet + kube-proxy + container runtime — the muscles.", color: "sky" },
        { term: "Pod", definition: "The atomic unit: one or more containers sharing a network namespace and volume.", color: "amber" },
        { term: "Deployment", definition: "The desired-state controller: replicas, rolling updates, rollbacks.", color: "violet" },
        { term: "Service", definition: "A stable network identity and load balancer for a set of pods (by label selector).", color: "rose" },
      ], "K8s vocabulary in five terms"),
      flow({
        heading: "The control loop that never sleeps",
        sub: "Desired state in, reality converged out — forever",
        nodes: [
          { id: "a", label: "declared desired state", shape: "pill", color: "sky" },
          { id: "b", label: "API server", shape: "rect", color: "lime" },
          { id: "c", label: "etcd (source of truth)", shape: "cyl", color: "amber" },
          { id: "d", label: "scheduler", shape: "rect", color: "violet" },
          { id: "e", label: "kubelet on node", shape: "rect", color: "sky" },
          { id: "f", label: "pods running", shape: "pill", color: "lime" },
        ],
        edges: [ { from: "a", to: "b" }, { from: "b", to: "c" }, { from: "c", to: "d" }, { from: "d", to: "e" }, { from: "e", to: "f" }, { from: "f", to: "b", animated: true } ],
      }, "Reconciliation, forever"),
      code({
        heading: "The three YAMLs you must read fluently",
        sub: "Each is a contract — read them like code, because they are",
        lang: "yaml",
        codeLines: [
          "apiVersion: apps/v1",
          "kind: Deployment",
          "metadata: { name: api, labels: { app: api } }",
          "spec:",
          "  replicas: 3",
          "  selector: { matchLabels: { app: api } }      # wiring: pods it manages",
          "  template:",
          "    metadata: { labels: { app: api } }",
          "    spec:",
          "      containers:",
          "      - name: api",
          "        image: myapp:1.2.3",
          "        ports: [{ containerPort: 3000 }]",
          "        resources: { requests: { cpu: 100m, memory: 128Mi },",
          "                     limits:   { cpu: 300m, memory: 256Mi } }",
          "---",
          "kind: Service",
          "apiVersion: v1",
          "metadata: { name: api-svc }",
          "spec:",
          "  selector: { app: api }                          # same labels → pods",
          "  ports: [{ port: 80, targetPort: 3000 }]",
        ],
        captions: [
          "labels wire the system: selectors find pods by label, nothing else",
          "requests are promises to the scheduler; limits are enforced ceilings",
          "a Service gives stable DNS to whatever pods carry app: api",
          "rollout: change the image → rolling update — old pods drain, new pods flow in",
        ],
      }, "Deployment + Service, wearing their wires"),
      steps({
        heading: "What happens when you kubectl apply",
        sub: "Follow one manifest through the machinery",
        steps: [
          { label: "1. apply", detail: "API server validates and stores the desired state in etcd", color: "sky" },
          { label: "2. controller sees the diff", detail: "replica controller compares actual vs desired — 'need 3, have 0'", color: "lime" },
          { label: "3. scheduler picks nodes", detail: "fits resources, spreads across nodes", color: "amber" },
          { label: "4. kubelets pull & start", detail: "each node runs its containers, reports status back", color: "violet" },
          { label: "5. reconciliation continues", detail: "a crashed pod is recreated automatically — the loop never stops", color: "rose" },
        ],
      }, "From YAML to running, end to end"),
      compare({
        heading: "The critical split",
        left: { label: "Stateless (API, workers, web)", points: ["Pods are cattle — kill and recreate freely", "One deployment, scale horizontally", "Sessions in Redis, not memory"], verdict: "K8s magic applies", color: "lime" },
        right: { label: "Stateful (databases)", points: ["Identity and storage per pod (StatefulSet)", "Ordering, stable network names", "The hard part — run managed DBs instead"], verdict: "managed service, usually", color: "rose" },
      }, "Stateful workloads are their own discipline"),
      bullets({
        heading: "K8s mistakes with operational consequences",
        items: [
          { text: "No resource requests/limits → scheduling garbage and noisy neighbors", kind: "bad", note: "requests matter more than limits" },
          { text: "Image tag :latest → rollouts that change unknowingly", kind: "bad", note: "pin immutable tags" },
          { text: "Secrets as plain ConfigMaps → base64 is not encryption", kind: "bad", note: "k8s secrets + external secret operators" },
          { text: "No readiness probe → traffic lands on still-booting pods", kind: "bad", note: "liveness restarts, readiness routes" },
          { text: "Cluster-admin for everyone → one token is now the whole company", kind: "bad", note: "RBAC: least privilege per namespace" },
        ],
      }, "Each one has cost a team a Tuesday"),
      scenario({
        heading: "Case study: the node drain that wasn't",
        text: "A team ran a three-node cluster with zero pod resource requests. The scheduler happily over-packed one node — three pods of a monolithic app plus two workers. Cloud maintenance drained that node; every pod re-landed on the same remaining node, which promptly OOM-killed them all. The whole app was down for 41 minutes before a human intervened. The fix: requests/limits on every deployment, node anti-affinity for the app's pods, and PDB (PodDisruptionBudget) so drains wait for replacement capacity. Kubernetes didn't fail — the absence of requests, affinity and PDBs did.",
      }, "Real-world postmortem"),
      quiz([
        { question: "What actually stores Kubernetes cluster state?", options: ["The scheduler", "etcd", "Each node's kubelet", "The cloud provider"], answer: 1, explain: "etcd is the source of truth; the API server is the only writer." },
        { question: "How does a Service find its pods?", options: ["By IP range", "By label selector matching pod labels", "By image name", "It doesn't — pods find it"], answer: 1, explain: "The selector matches pod labels — that's the entire wiring mechanism." },
        { question: "What does a readiness probe gate?", options: ["Restarts", "Which pods receive traffic", "Image pulls", "Node scheduling"], answer: 1, explain: "Readiness controls traffic routing; liveness triggers restarts. Different jobs." },
      ], "Check yourself: K8s architecture"),
      stat({
        heading: "K8s in three constants",
        stats: [
          { value: "5", label: "control-plane components to name in an interview", color: "lime" },
          { value: "3", label: "YAML kinds to read fluently: Deployment, Service, Ingress", color: "amber" },
          { value: "0", label: "pods you should trust that lack requests, probes and pins", color: "rose" },
        ],
      }, "Small surface, deep consequences"),
      recap({
        points: [
          "Control plane decides; nodes execute; etcd remembers",
          "Pods are units; Deployments are desired-state; Services are stable names",
          "Labels + selectors are the system's wiring — match labels or nothing works",
          "Requests, probes, pinned tags, RBAC — the non-negotiables",
          "Stateful workloads are their own discipline — managed DBs usually win",
        ],
      }),
    ],
  },
  {
    lessonId: "les-ct-4-1",
    lessonTitle: "Horizontal Pod Autoscaler",
    scenes: [
      title({
        eyebrow: "Module 2 · Kubernetes",
        heading: "Horizontal Pod Autoscaler",
        sub: "Scaling that follows metrics — CPU, custom metrics, and the limits of the model",
        goals: [
          "Explain how HPA computes desired replicas from metrics",
          "Configure target utilisation and scale bounds sensibly",
          "Recognise the scaling traps: lag, thrash, and limits as ceilings",
          "Pair HPA with requests, readiness and budget for production",
        ],
        accent: "cyan",
      }),
      keyterms([
        { term: "HPA", definition: "Horizontal Pod Autoscaler — a controller adjusting replica count from metrics.", color: "lime" },
        { term: "Target utilisation", definition: "The metric level you want: 70% CPU means every pod at 70% is 'full'.", color: "sky" },
        { term: "Metrics Server", definition: "The in-cluster component collecting pod CPU/memory samples.", color: "amber" },
        { term: "Scale-up delay", definition: "Metrics lag ~15–60s; HPA moves ~1 per 15s — spikes outrun slow loops.", color: "rose" },
        { term: "Readiness vs load", definition: "A pod that's not ready isn't counted — a broken pod can fool the ratio.", color: "violet" },
      ], "Autoscaling vocabulary"),
      diagram({
        heading: "The HPA loop",
        sub: "metrics → ratio → replica target → repeat",
        rows: [
          { label: "Metrics Server", detail: "samples CPU/memory per pod every ~15s", color: "sky" },
          { label: "Desired replicas", detail: "ceil(current × currentUtil / targetUtil) — the formula", color: "lime" },
          { label: "Bounds", detail: "minReplicas … maxReplicas — you choose the guard rails", color: "amber" },
          { label: "Controller", detail: "applies changes, waits for the pod to become READY before trusting it", color: "violet" },
          { label: "Scale-down grace", detail: "stabilisation window — no frantic 3→10→3 thrash", color: "rose" },
        ],
      }, "The loop, end to end"),
      code({
        heading: "An HPA manifest, annotated",
        sub: "The default pattern that serves most workloads",
        lang: "yaml",
        codeLines: [
          "apiVersion: autoscaling/v2",
          "kind: HorizontalPodAutoscaler",
          "metadata: { name: api-hpa }",
          "spec:",
          "  scaleTargetRef: { apiVersion: apps/v1, kind: Deployment, name: api }",
          "  minReplicas: 2",
          "  maxReplicas: 10",
          "  metrics:",
          "  - type: Resource",
          "    resource:",
          "      name: cpu",
          "      target: { type: Utilization, averageUtilization: 70 }",
          "  behavior:",
          "    scaleDown:",
          "      stabilizationWindowSeconds: 300   # no thrash on 1-min dips",
        ],
        captions: [
          "CPU utilisation is the default metric — cheap and universally available",
          "minReplicas=2 keeps headroom; maxReplicas=10 caps the bill and the blast radius",
          "the stabilization window prevents scale-down thrash",
          "memory is a poor scale metric (it doesn't drain on demand) — reserve it, don't autoscale on it",
        ],
      }, "The standard pattern"),
      steps({
        heading: "Tuning HPA for production",
        sub: "The sequence that turns autoscaling from demo into discipline",
        steps: [
          { label: "1. requests everywhere", detail: "HPA's utilisation math assumes requests exist — no requests, no honest metric", color: "sky" },
          { label: "2. readiness probes", detail: "scaling in trusts READY pods only — a crashing pod skews the ratio", color: "amber" },
          { label: "3. set the bounds", detail: "2–10 is a guess; load-test to find your real minimum and ceiling", color: "violet" },
          { label: "4. scale-up fast, down slow", detail: "raise scale-up window walls; keep scale-down stabilisation long", color: "lime" },
          { label: "5. alert on capped", detail: "stuck at maxReplicas = hunger signal: quotas, DB, or bad metric", color: "rose" },
        ],
      }, "The production checklist"),
      compare({
        heading: "HPA vs the alternatives",
        left: { label: "HPA (CPU)", points: ["Standard, easy, metric-limited", "Reacts AFTER the spike lands", "Great for uniform CPU work"], verdict: "default", color: "lime" },
        middle: { label: "Custom metrics (KEDA)", points: ["Queue depth, request rate, latency", "Event-driven: scales BEFORE the load arrives", "Prometheus/queue integrations"], verdict: "event-driven", color: "violet" },
        right: { label: "Cluster autoscaler", points: ["Adds NODES when pods can't fit", "The vertical axis of the same story", "Pair HPA + CA or you scale nothing"], verdict: "infrastructure axis", color: "amber" },
      }, "Know which lever you're pulling"),
      bullets({
        heading: "Autoscaling traps",
        items: [
          { text: "Scaling on CPU when capacity comes from DB connections — pods scale, DB degrades", kind: "bad", note: "pick the real bottleneck metric" },
          { text: "Slow cold start (JVM/heavy images): HPA's 15s cadence loses the race", kind: "bad", note: "reduce start time or pre-scale" },
          { text: "maxReplicas too low: scale hits the ceiling, everything 500s", kind: "bad", note: "alarm at the cap" },
          { text: "No limits set: one hot pod's neighbour steals allocatable CPU", kind: "bad" },
          { text: "Thrashing 3↔10 on a noisy-but-steady load", kind: "bad", note: "widen stability windows" },
        ],
      }, "Each one is a real incident"),
      scenario({
        heading: "Case study: the cascade that autoscaled into the wall",
        text: "A platform autoscaled its API pods on CPU. A launch-day spike pushed CPU up; HPA scaled 6→20 pods; each new pod opened its connection pool to the shared Postgres, which hit its max connections and began queueing. Queries slowed, CPU rose further, more pods scaled, more connections queued — a feedback loop that ended in a 40-minute outage. The fix: scale on request latency AND queue depth (KEDA), cap pools per pod, and make maxReplicas a reviewed number, not a guess. Autoscaling is a control system; every loop needs a limit and a model.",
      }, "Real-world postmortem"),
      quiz([
        { question: "What does HPA do when pods lack resource requests?", options: ["Nothing — it ignores them", "Uses actual usage instead", "Fails to scale", "Waits for limits"], answer: 0, explain: "Utilisation is usage/request ratio — without requests, HPA can't compute honest utilisation." },
        { question: "Which metric is generally POOR for autoscaling?", options: ["CPU utilisation", "Request latency (custom)", "Queue depth (custom)", "Memory utilisation"], answer: 3, explain: "Memory doesn't drain gracefully on demand — a pod at 95% memory stays degraded while scaling. CPU and queues reflect demand far better." },
        { question: "What pairs with HPA to add NODES when pods can't fit?", options: ["The scheduler", "Cluster Autoscaler", "PDB", "NodeSelector"], answer: 1, explain: "Cluster Autoscaler grows the fleet when pending pods lack capacity — the infrastructure half of autoscaling." },
      ], "Check yourself: HPA"),
      stat({
        heading: "Scaling by the numbers",
        stats: [
          { value: "15–60s", label: "metric lag — spikes outrun naive loops", color: "rose" },
          { value: "70%", label: "typical CPU target: headroom for spikes, room under limits", color: "lime" },
          { value: "2–10", label: "reviewed bounds beat unbound scaling every time", color: "amber" },
        ],
      }, "Autoscaling is a control system"),
      recap({
        points: [
          "HPA = metrics → ratio → replicas, bounded by min/max you own",
          "Requests, readiness and bounds are prerequisites, not afterthoughts",
          "CPU is the default; queues/latency (KEDA) are the event-driven upgrade",
          "Scale up fast, down slow — stability windows prevent thrash",
          "Alert at the cap; autoscaling is a control loop with limits",
        ],
      }),
    ],
  },
];