import {
  title, keyterms, bullets, steps, diagram, flow, code, terminal, compare, scenario, quiz, stat, recap,
  type LessonVideoScript,
} from "./core";

// ════════════════════════════════════════════════════════════════
// DEVOPS — deep scripts (course-devops)
// ════════════════════════════════════════════════════════════════

export const deepDevOps: LessonVideoScript[] = [
  {
    lessonId: "les-do-1-1",
    lessonTitle: "What is DevOps?",
    scenes: [
      title({
        eyebrow: "Module 1 · Culture & Loops",
        heading: "What is DevOps?",
        sub: "A culture of short feedback loops — not a title, not a tool",
        goals: [
          "Define DevOps as culture and practice, not a role",
          "Map the four key metrics: DORA's vocabulary of velocity and stability",
          "Explain the deployment pipeline as a feedback loop",
          "Distinguish CI, CD and the practices that make them work",
        ],
        accent: "violet",
      }),
      keyterms([
        { term: "DORA metrics", definition: "The four industry-standard numbers: deploy frequency, lead time, MTTR, change failure rate.", color: "lime" },
        { term: "CI (Continuous Integration)", definition: "Merge frequently; every push builds and tests — integration pain happens daily, not quarterly.", color: "sky" },
        { term: "CD (Continuous Delivery)", definition: "Every change is releasable — deployment is a business decision, not a technical one.", color: "amber" },
        { term: "Feedback loop", definition: "The distance between a change and knowing it worked — DevOps shrinks it.", color: "violet" },
        { term: "Toil", definition: "Manual, repetitive work that scales with growth but not with value — automation's target.", color: "rose" },
      ], "The vocabulary of the movement"),
      diagram({
        heading: "The infinite loop",
        sub: "Each arrow is a feedback channel you can shorten",
        rows: [
          { label: "Plan → Code", detail: "small changes into review fast — trunk-based, not feature tombs", color: "sky" },
          { label: "Build → Test", detail: "CI gates every push; tests are the safety net that makes speed safe", color: "lime" },
          { label: "Release → Deploy", detail: "small, reversible releases — canary or feature-flagged", color: "amber" },
          { label: "Operate → Monitor", detail: "metrics, logs, traces — the loop's eyes", color: "violet" },
          { label: "Monitor → Learn", detail: "postmortems write knowledge back into the next plan", color: "rose" },
        ],
      }, "DevOps, drawn as a circle"),
      stat({
        heading: "The DORA elite benchmark",
        sub: "What the top quartile ships, as numbers",
        stats: [
          { value: "Multiple×", label: "deploy frequency per day, vs weekly for low performers", color: "lime" },
          { value: "< 1 day", label: "lead time for a change, vs months", color: "sky" },
          { value: "< 1 hour", label: "time to restore service, vs a week", color: "amber" },
          { value: "0–15%", label: "change failure rate, vs 46–60%", color: "rose" },
        ],
      }, "Speed and stability are not a trade-off"),
      flow({
        heading: "The pipeline as a feedback machine",
        sub: "Every stage is a gate that says NO cheaply, so production never has to",
        nodes: [
          { id: "a", label: "push", shape: "pill", color: "sky" },
          { id: "b", label: "build", shape: "rect", color: "lime" },
          { id: "c", label: "test", shape: "rect", color: "amber" },
          { id: "d", label: "preview env", shape: "rect", color: "violet" },
          { id: "e", label: "approve", shape: "diamond", color: "rose" },
          { id: "f", label: "deploy", shape: "rect", color: "lime" },
          { id: "g", label: "monitor", shape: "pill", color: "cyan" },
        ],
        edges: [ { from: "a", to: "b" }, { from: "b", to: "c" }, { from: "c", to: "d" }, { from: "d", to: "e" }, { from: "e", to: "f" }, { from: "f", to: "g" } ],
      }, "Fail cheap, far from production"),
      compare({
        heading: "DevOps vs the alternatives it replaced",
        left: { label: "Waterfall / ops silos", points: ["Releases every months", "Integration discover at the end", "Dev throws over the wall", "Postmortems = blame games"], verdict: "slow by design", color: "rose" },
        right: { label: "DevOps", points: ["Releases daily, reversible", "Integration daily, in CI", "One team owns the lifecycle", "Blameless postmortems feed back"], verdict: "fast by design", color: "lime" },
      }, "What changed is the loop, not the tools"),
      bullets({
        heading: "Practices that make the loop short",
        items: [
          { text: "Trunk-based development: small merges daily, branches measured in hours", kind: "good" },
          { text: "Feature flags: new code ships dark, flips on per cohort — release ≠ deploy", kind: "good" },
          { text: "Monitoring before release: the pipeline ends where the alerting begins", kind: "good" },
          { text: "Toil inventory: list every manual step; the top three get automated next sprint", kind: "good" },
          { text: "Blameless postmortems: process fixes beat personnel fixes", kind: "good" },
        ],
      }, "Culture is practice, repeated"),
      scenario({
        heading: "Case study: the 3 a.m. release ritual",
        text: "A bank's 'release' was a fortnightly ritual: a team of six, a change freeze, a 2-hour window, and prayer. Deploys were regular, scary and irreversible. They moved to trunk-based dev with full CI and feature-flagged releases: changes now ship in minutes, dark, and are flipped per customer cohort. The first flag-limited release of a payment change — flipped to 1% of users, monitored for an hour, then rolled wider — produced zero incidents and ended the ritual. The bank didn't get faster by trying harder; it got faster by making releases boring.",
      }, "Real-world postmortem"),
      quiz([
        { question: "Which DORA metric measures how quickly an emergency is resolved?", options: ["Deploy frequency", "Lead time", "Time to restore service", "Change failure rate"], answer: 2, explain: "MTTR — mean time to restore, the <1 hour elite benchmark." },
        { question: "CI's core promise is…", options: ["Automated deploys", "Frequent integration with automated build+test on each change", "Zero downtime", "Green builds"], answer: 1, explain: "Integrate daily, catch conflicts and regressions daily — before they compound." },
        { question: "A feature flag lets you…", options: ["Speed up builds", "Ship code dark and enable it per cohort", "Replace tests", "Skip monitoring"], answer: 1, explain: "Deploy and release decouple: code ships, users see it when you choose." },
      ], "Check yourself: DevOps"),
      recap({
        points: [
          "DevOps is a culture of short feedback loops, not a job title",
          "DORA's four metrics measure the loop: frequency, lead time, MTTR, failure rate",
          "CI integrates daily; CD keeps every change releasable",
          "Release ≠ deploy: feature flags decouple them",
          "Automate toil; run blameless postmortems; make releases boring",
        ],
      }),
    ],
  },
  {
    lessonId: "les-do-2-1",
    lessonTitle: "GitHub Actions Fundamentals",
    scenes: [
      title({
        eyebrow: "Module 2 · Automation",
        heading: "GitHub Actions Fundamentals",
        sub: "Workflows, jobs, runners — and pipelines that gate with confidence",
        goals: [
          "Structure a workflow: triggers, jobs, steps, and matrices",
          "Secure secrets and avoid supply-chain mistakes",
          "Cache dependencies and reuse workflows across repos",
          "Gate deploys and preview environments from a PR",
        ],
        accent: "violet",
      }),
      keyterms([
        { term: "Workflow", definition: "A YAML file in .github/workflows declaring triggers, jobs and steps.", color: "lime" },
        { term: "Job", definition: "A unit that runs on one runner — steps share state; jobs run in parallel.", color: "sky" },
        { term: "Runner", definition: "The executor: GitHub-hosted (ubuntu/windows) or your own.", color: "amber" },
        { term: "Matrix", definition: "A job expanded across combinations — test on Node 18/20/22, each parallel.", color: "violet" },
        { term: "Secrets", definition: "Encrypted values passed by name — never written, only referenced.", color: "rose" },
      ], "Actions vocabulary"),
      code({
        heading: "A pipeline you'd be proud to review",
        sub: "Test → typecheck → build → deploy, gated and cached",
        lang: "yaml",
        codeLines: [
          "name: ci",
          "on:",
          "  push: { branches: [main] }",
          "  pull_request:",
          "",
          "jobs:",
          "  test:",
          "    runs-on: ubuntu-latest",
          "    strategy:",
          "      matrix: { node-version: [18, 20, 22] }",
          "    steps:",
          "      - uses: actions/checkout@v4",
          "      - uses: actions/setup-node@v4",
          "        with: { node-version: '${{ matrix.node-version }}' }",
          "      - uses: actions/cache@v4",
          "        with: { path: ~/.npm, key: npm-${{ hashFiles('package-lock.json') }} }",
          "      - run: npm ci && npm run typecheck && npm test",
          "",
          "  deploy:",
          "    needs: test",
          "    if: github.ref == 'refs/heads/main'",
          "    steps:",
          "      - run: ./scripts/deploy.sh",
          "        env:",
          "          AWS_ROLE_ARN: ${{ secrets.DEPLOY_ROLE_ARN }}   # never inline secrets",
        ],
        captions: [
          "matrix forks the job across Node versions — compatibility proven per merge",
          "hashFiles keys the cache — lockfile-driven, invalidated when deps change",
          "deploy runs ONLY after test succeeds — needs: test is the gate",
          "secrets by reference only — what's written is a name, never a value",
        ],
      }, "The reference pipeline"),
      terminal({
        heading: "The troubleshooting surface",
        sub: "The commands between a red X and a fix",
        prompt: "gh",
        commandLines: [
          "gh run list                     # recent runs",
          "gh run view <id> --log-failed   # just the failing lines",
          "gh run rerun --failed <id>      # retry flakes, not the whole suite",
          "gh workflow disable <wf>        # stop a runaway workflow",
          "gh secret set PROD_TOKEN        # secrets live in the Settings API, never the repo",
        ],
        captions: [
          "gh CLI makes CI debuggable from the terminal",
          "rerun --failed is the flake recovery move",
          "secrets are set through the API — no curl piping, no plaintext in logs",
        ],
      }, "Operate your pipeline"),
      compare({
        heading: "GitHub-hosted vs self-hosted runners",
        left: { label: "GitHub-hosted", points: ["Zero maintenance, ephemeral", "Per-minute billing for private repos", "No custom hardware/GPU", "Starts in seconds"], verdict: "default", color: "lime" },
        right: { label: "Self-hosted", points: ["Free beyond hardware", "Long-lived = secret exposure risk", "You patch, you secure", "GPU/specialised runs"], verdict: "with care", color: "amber" },
      }, "Choose per workload, know the risk"),
      bullets({
        heading: "Supply-chain & secret hygiene in Actions",
        items: [
          { text: "Pin third-party actions to full SHAs (actions/checkout@d171c3a…) — tags can be moved", kind: "good" },
          { text: "pull_request_target with untrusted code is a secret exfiltration vector — read the docs before using it", kind: "bad" },
          { text: "Actions logs redact secrets — but a base64 'workaround' prints them in plain", kind: "bad" },
          { text: "Secrets only in env of the step that needs them — not at workflow level", kind: "good" },
          { text: "Supply-chain scanners (Dependabot/Dependency review) gate on vulnerable deps", kind: "good" },
        ],
      }, "Your pipeline is supply chain"),
      steps({
        heading: "From PR to preview environment",
        sub: "The workflow that makes every PR demoable",
        steps: [
          { label: "1. on: pull_request", detail: "trigger on PR — not just push; every branch gets a gate", color: "sky" },
          { label: "2. test + typecheck + build", detail: "fail fast; matrix if multi-version", color: "lime" },
          { label: "3. deploy preview", detail: "ephemeral env per PR — a URL comment lands on the PR", color: "violet" },
          { label: "4. label PR as ready", detail: "reviewers see reality, not screenshots", color: "amber" },
          { label: "5. teardown on close", detail: "preview envs die with the PR — no orphaned stacks", color: "rose" },
        ],
      }, "The loop that makes code review real"),
      scenario({
        heading: "Case study: the action that shipped a token",
        text: "A team used a popular third-party action at a moving tag to deploy to AWS. The action's maintainer — a solo developer — had their account hijacked; the tag was repointed to a build that exfiltrated every env secret. Two weeks of logs later, the team found credentials in an attacker's blob. The posture since: every third-party action pinned to a full commit SHA, reviewed; a dependency review gate in CI; and self-hosted with tight network egress for any workflow touching production. Repo rehearsals: the pipeline itself is now threat-modelled like any production system.",
      }, "Real-world postmortem"),
      quiz([
        { question: "When do jobs in a workflow run by default?", options: ["Sequentially always", "In parallel; needs: enforces order", "Only on push", "Never together"], answer: 1, explain: "Independent jobs parallelise; needs: makes one wait for another's success." },
        { question: "Why pin third-party actions to SHAs?", options: ["It's faster", "Tags can be repointed by a compromised owner — SHAs are immutable", "GitHub requires it", "SHA pins disable caching"], answer: 1, explain: "A moved tag changes what your pipeline executes — the classic supply-chain hijack." },
        { question: "Where should secrets be referenced?", options: ["Inline in run commands", "In env on the step that needs them, by name", "In commit messages", "Anywhere"], answer: 1, explain: "Scoped env, referenced by name — never written, never printed." },
      ], "Check yourself: Actions"),
      recap({
        points: [
          "Workflows are YAML: triggers, jobs (parallel), steps (shared state)",
          "Matrix for version coverage; cache with lockfile-based keys",
          "needs: creates gates — deploy only after green tests",
          "Pin actions to SHAs; secrets by reference, scoped to the step",
          "PR previews make every change demoable; teardown with the PR",
        ],
      }),
    ],
  },
  {
    lessonId: "les-do-3-1",
    lessonTitle: "Deployment Strategies",
    scenes: [
      title({
        eyebrow: "Module 2 · Automation",
        heading: "Deployment Strategies",
        sub: "Rolling, blue-green, canary, feature flags — and how to choose under pressure",
        goals: [
          "Compare rolling, blue-green and canary deployments",
          "Explain rollback mechanics and rehearsal",
          "Use feature flags to decouple release from deploy",
          "Run a canary with real metrics gates",
        ],
        accent: "violet",
      }),
      keyterms([
        { term: "Rolling", definition: "Replace instances gradually — zero extra capacity, but no instant rollback.", color: "lime" },
        { term: "Blue-green", definition: "Two full environments; switch traffic atomically — instant rollback by flip-back.", color: "sky" },
        { term: "Canary", definition: "Ship to a small % first; watch metrics; promote when healthy.", color: "amber" },
        { term: "Feature flag", definition: "Runtime switch decoupling code presence from user visibility.", color: "violet" },
        { term: "Rollback", definition: "Returning to the last known-good state — speed = rehearsal.", color: "rose" },
      ], "Strategy vocabulary"),
      compare({
        heading: "The three classics, contrasted",
        left: { label: "Rolling", points: ["One by one, down zero", "No extra capacity needed", "Old+new coexist briefly — mixed-version bugs", "Rollback = redeploy old"], verdict: "simple & cheap", color: "lime" },
        middle: { label: "Blue-green", points: ["Two full stacks, instant switch", "2× capacity, DB migration care", "Instant, full rollback", "Great for breaking UI/API changes"], verdict: "atomic & reversible", color: "sky" },
        right: { label: "Canary", points: ["1% → 10% → 100% on metrics", "Granular risk control", "Metric gates are the discipline", "Automation required"], verdict: "surgical", color: "amber" },
      }, "Choose by risk, not habit"),
      steps({
        heading: "A canary with real gates",
        sub: "The full loop, gates included",
        steps: [
          { label: "1. cut 5%", detail: "route one in twenty requests to the new version", color: "sky" },
          { label: "2. watch 15 min", detail: "error rate, latency, business metric (orders, not pings)", color: "lime" },
          { label: "3. auto-gate", detail: "error-rate breach → auto-rollback the canary — no human needed", color: "rose" },
          { label: "4. promote 100%", detail: "when clean, ramp to full and retire the old version", color: "amber" },
          { label: "5. record the artefact", detail: "the shipped version is known, tagged, deployable again", color: "violet" },
        ],
      }, "Canary with discipline"),
      code({
        heading: "Feature flags vs deploy types",
        sub: "Flags separate 'shipped' from 'seen' — the cleanest rollback of all",
        lang: "text",
        codeLines: [
          "DEPLOY MECHANISMS change your infrastructure:",
          "  rolling  → old/renewed hosts coexist",
          "  blue-green → two environments, one switch",
          "  canary   → a percentage of traffic",
          "",
          "FEATURE FLAGS change your SOFTWARE:",
          "  feature.checkout_v2 = user.cohort in [1%, beta]",
          "  → kill switch: set false → behaviour reverts in seconds, no deploy at all",
          "",
          "BEST PRACTICE: flags for gradual exposure; deploys stay boring;",
          "the rollback of last resort is the previous ARTEFACT, rehearsed.",
        ],
        captions: [
          "flags decouple deploy (mechanical) from release (business decision)",
          "a flag flip is the cheapest rollback — seconds, no pipeline",
          "rehearse artefact rollback anyway — flags can't fix a schema break",
        ],
      }, "Two axes, both rehearsed"),
      bullets({
        heading: "Rollback rehearsals & the full-tilt failure story",
        items: [
          { text: "A schema migration applied with the deploy: rolling back CODE didn't roll back the schema", kind: "bad", note: "forward-fix migrations beat reverse migrations" },
          { text: "Automated canary on error rate caught a broken checkout in 4 minutes", kind: "good" },
          { text: "Blue-green with a DB: both environments hit ONE database — migration coordination is the hard part", kind: "bad" },
          { text: "Quarterly 'rollback Friday': deploy old, deploy new, deploy old — boredom builds muscle memory", kind: "good" },
        ],
      }, "Story time, with receipts"),
      scenario({
        heading: "Case study: the midnight rollback that took 40 minutes",
        text: "A fintech deployed its monolith as a rolling update at midnight. The new build failed under actual traffic patterns — 500s at 2% rollout. Rolling back meant redeploying the previous artefact: 40 minutes of partial-serve, partial-fail, because rolling deployments can't snap back. The rewrite added blue-green for the monolith with automated smoke checks on the inactive environment before the switch, plus a canary ramp for the API. The next bad build was detected BEFORE users saw it, and 'rollback' became a 90-second switch. The lesson: choose the strategy that matches your rollback needs, not your deploy ceremony.",
      }, "Real-world postmortem"),
      quiz([
        { question: "Which strategy costs 2× capacity but gives instant full rollback?", options: ["Rolling", "Blue-green", "Canary", "Feature flags"], answer: 1, explain: "Two full environments + a traffic switch = atomic flip-back. Expensive, decisive." },
        { question: "What should a canary gate auto-do on an error-rate breach?", options: ["Page a human", "Roll back the canary", "Scale up", "Ignore it for 10 minutes"], answer: 1, explain: "A gated canary rolls itself back on breach — the automation is the point." },
        { question: "A feature flag's rollback superpower is…", options: ["It redeploys old code", "It flips behaviour in seconds without any deploy", "It freezes users out", "It patches the DB"], answer: 1, explain: "Flags turn 'revert this behaviour' into a config change — instant, reversible." },
      ], "Check yourself: deployment strategies"),
      recap({
        points: [
          "Rolling: cheap, gradual, slow rollback · Blue-green: atomic, 2× capacity",
          "Canary: percentage + metric gates + auto-rollback",
          "Feature flags decouple release from deploy — the cheap kill switch",
          "Migrations need forward-fix plans; rollbacks of code don't reverse schema",
          "Rehearse rollback quarterly — boredom in practice beats heroism in crisis",
        ],
      }),
    ],
  },
  {
    lessonId: "les-do-4-1",
    lessonTitle: "Metrics, Logs & Traces",
    scenes: [
      title({
        eyebrow: "Module 3 · Observability",
        heading: "Metrics, Logs & Traces",
        sub: "The three pillars, the RED/USE method, and alerting that's worth waking up for",
        goals: [
          "Distinguish metrics, logs and traces — and when each answers what",
          "Apply RED (requests, errors, duration) and USE (utilisation) methods",
          "Structure structured logs with request IDs",
          "Design alerts that fire on user impact, not trivia",
        ],
        accent: "violet",
      }),
      keyterms([
        { term: "Metrics", definition: "Aggregated numbers over time — counters, gauges, histograms. Trending and alerting.", color: "lime" },
        { term: "Logs", definition: "Discrete events with context — the narrative of one request or incident.", color: "sky" },
        { term: "Traces", definition: "The journey of one request across services — timing each hop.", color: "amber" },
        { term: "RED method", definition: "Rate (requests/s), Errors, Duration — the service health trio.", color: "violet" },
        { term: "SLO / error budget", definition: "A target like 99.9% availability — and the budget of failure you're allowed.", color: "rose" },
      ], "Observability vocabulary"),
      diagram({
        heading: "The three pillars, one incident",
        sub: "Metrics say something broke; logs say what; traces say where",
        rows: [
          { label: "Metrics", detail: "error rate 4.2% since 14:31 · p99 latency 2.8s — the alarm", color: "lime" },
          { label: "Logs", detail: "requestId req_9f2c: 'db connection timeout after 5000ms' — the cause", color: "sky" },
          { label: "Traces", detail: "api → orders → payments: 4.9s spent in payments.query — the culprit hop", color: "amber" },
          { label: "The flow", detail: "alert on metric → drill into log by requestId → follow the trace to the slow edge", color: "violet" },
        ],
      }, "Each pillar answers a different question"),
      code({
        heading: "Structured logs that save hours",
        sub: "JSON + request IDs = logs you can search, join and chart",
        lang: "javascript",
        codeLines: [
          "// one line of middleware buys you every debugging session:",
          "app.use((req, res, next) => {",
          "  req.id = req.headers['x-request-id'] ?? crypto.randomUUID();",
          "  const start = process.hrtime.bigint();",
          "  res.on('finish', () => {",
          "    logger.info({",
          "      event: 'request',",
          "      requestId: req.id,",
          "      method: req.method,",
          "      path: req.path,",
          "      status: res.statusCode,",
          "      durationMs: Number(process.hrtime.bigint() - start) / 1e6,",
          "    });",
          "  });",
          "  next();",
          "});",
          "// now: log search by requestId joins every service's story",
        ],
        captions: [
          "a request ID threads one request through every log line and service",
          "JSON logs are queryable — 'status>500' becomes a one-second search",
          "durationMs per request is your latency histogram source",
          "never log bodies, tokens or PII — fields, not secrets",
        ],
      }, "The middleware that pays forever"),
      steps({
        heading: "The RED / USE cheatsheet",
        sub: "Service health and resource health, named",
        steps: [
          { label: "RED — services", detail: "Rate (requests/s) · Errors (5xx + business failures) · Duration (p50/p95/p99)", color: "lime" },
          { label: "USE — resources", detail: "Utilisation · Saturation (queue length!) · Errors — for CPUs, disks, pools", color: "amber" },
          { label: "four golden signals", detail: "latency · traffic · errors · saturation — Google's combined view", color: "violet" },
          { label: "business metrics", detail: "orders, registrations, checkouts — the metric that actually matters", color: "rose" },
        ],
      }, "The vocabulary of healthy dashboards"),
      compare({
        heading: "Alerts that earn their wake-ups",
        left: { label: "Alert on trivia", points: ["'CPU 80%' on everything", "Alert per instance, not per service", "No severity, no runbook", "Red pages ignored within a week"], verdict: "alert fatigue", color: "rose" },
        right: { label: "Alert on user impact", points: ["Error budget burn (99.9% SLO breach window)", "p99 latency over target 10 min", "Business metric drop", "Each alert has a runbook and an owner"], verdict: "trusted pages", color: "lime" },
      }, "Alert count is not engineering achievement"),
      bullets({
        heading: "Logging truths teams learn in incidents",
        items: [
          { text: "You can't search what you never logged — log at the edges: entry, exit, errors", kind: "good" },
          { text: "Log levels in the app; verbosity controlled by config at run time", kind: "good" },
          { text: "Logs are cheap until an incident; then they're priceless — keep 30+ days", kind: "info" },
          { text: "A dashboard nobody looks at is storage: alert on the metric, chart for humans", kind: "bad" },
        ],
      }, "Incident-time truths"),
      scenario({
        heading: "Case study: the alert every engineer muted",
        text: "A platform alerted on 'CPU > 80%' for every host. Twenty alerts a night; every engineer muted the channel; the platform team stopped checking. One Tuesday the checkout service's p99 drifted to 11 seconds for two hours before a customer complaint arrived. The rebuild: the CPU alerts died; three SLO alerts replaced them — error budget burn for checkout, p99 over 2s for 10 minutes, and business-metric flatline (orders/hour < 50% of 7-day median). The mute rate went to zero. Alerting on user impact, with runbooks, restored the channel's meaning.",
      }, "Real-world postmortem"),
      quiz([
        { question: "Which pillar tells you WHERE (which service) a request is slow?", options: ["Metrics", "Logs", "Traces", "Dashboards"], answer: 2, explain: "Traces follow one request across services, timing every hop — the where." },
        { question: "What are the three RED metrics?", options: ["Rate, Errors, Duration", "Retries, Efficiency, Drops", "RPM, Epoch, Data", "Right, East, Down"], answer: 0, explain: "Requests per second, error share, and latency — the service-level trio." },
        { question: "Which alert would you keep?", options: ["CPU 80% on one instance", "Checkout error budget exhausted", "Uptime < 100% this month", "Disk 60%"], answer: 1, explain: "Error-budget and user-impact alerts page on meaning; instance trivia gets muted and ignored." },
      ], "Check yourself: observability"),
      stat({
        heading: "Gold-standard numbers",
        stats: [
          { value: "99.9%", label: "a defensible SLO — ~43 min allowed downtime a month", color: "lime" },
          { value: "15 min", label: "mean time to detection with SLO alerts vs hours without", color: "amber" },
          { value: "0", label: "alerts without runbooks and owners", color: "rose" },
        ],
      }, "Targets make decisions, not feelings"),
      recap({
        points: [
          "Metrics trend, logs narrate, traces pinpoint — all three per incident",
          "RED for services, USE for resources, business metrics on top",
          "Structured JSON + request IDs make logs searchable and joinable",
          "Alert on user impact (SLO burn, p99, business drop), with runbooks",
          "An ignored alert is worse than no alert — keep the channel trusted",
        ],
      }),
    ],
  },
];