import {
  title, keyterms, bullets, steps, diagram, flow, code, terminal, compare, scenario, quiz, stat, recap,
  type LessonVideoScript,
} from "./core";

// ════════════════════════════════════════════════════════════════
// NODE.JS BACKEND — deep scripts (course-node-backend)
// ════════════════════════════════════════════════════════════════

export const deepNode: LessonVideoScript[] = [
  {
    lessonId: "les-nb-1-1",
    lessonTitle: "Node.js Runtime & Modules",
    scenes: [
      title({
        eyebrow: "Module 1 · Node Foundations",
        heading: "Node.js Runtime & Modules",
        sub: "What Node actually is, how its event loop never blocks, and how require vs import work",
        goals: [
          "Explain the Node runtime: V8, libuv, the event loop and the thread pool",
          "Distinguish I/O-bound from CPU-bound work and handle both",
          "Choose CommonJS vs ESM with intent",
          "Read package.json dependency fields and semver ranges confidently",
        ],
        accent: "lime",
      }),
      keyterms([
        { term: "V8", definition: "Google's JavaScript engine that compiles JS to machine code — Node's execution core.", color: "lime" },
        { term: "libuv", definition: "The C library powering Node's event loop, thread pool and async I/O across platforms.", color: "cyan" },
        { term: "Event loop", definition: "The single-threaded scheduler draining callback queues in six repeating phases.", color: "amber" },
        { term: "CommonJS", definition: "Node's classic module system: require / module.exports, loaded synchronously.", color: "sky" },
        { term: "ESM", definition: "The standard module system: import / export, static graphs, tree-shakeable.", color: "violet" },
      ], "Five words that define the runtime"),
      diagram({
        heading: "The Node.js runtime stack",
        sub: "Your JavaScript never touches the OS directly — every layer below does the heavy lifting",
        rows: [
          { label: "Your application code", detail: "require/import, your modules, express handlers", color: "lime" },
          { label: "Node.js core APIs", detail: "fs, http, crypto, stream — the JS bindings", color: "sky" },
          { label: "V8 engine", detail: "compiles and runs your JavaScript at near-native speed", color: "amber" },
          { label: "libuv", detail: "event loop + 4-thread default pool + epoll/kqueue/IOCP per OS", color: "rose" },
          { label: "Operating system", detail: "Linux, macOS, Windows — the actual files, sockets and processes", color: "slate" },
        ],
      }, "Where Node actually lives"),
      steps({
        heading: "One tick through the event loop",
        sub: "The loop runs these phases over and over until nothing is left to do",
        steps: [
          { label: "timers", detail: "callbacks scheduled by setTimeout / setInterval fire here", color: "lime" },
          { label: "pending callbacks", detail: "deferred I/O callbacks from the previous cycle", color: "sky" },
          { label: "poll", detail: "fetches new I/O events; blocks here when the queue is empty", color: "amber" },
          { label: "check", detail: "setImmediate callbacks run — right after poll, always", color: "rose" },
          { label: "close callbacks", detail: "socket.on('close') style cleanup", color: "slate" },
          { label: "microtasks between phases", detail: "Promise.then and process.nextTick drain between every phase — they always jump the queue", color: "violet" },
        ],
      }, "Six phases, one heartbeat"),
      code({
        heading: "Blocking vs non-blocking — the 900 ms outage",
        sub: "One synchronous call turned a 12 ms endpoint into a 900 ms one for every user",
        lang: "javascript",
        codeLines: [
          "// ❌ BLOCKING — every request on the server waits here",
          "app.get('/report', (req, res) => {",
          "  const csv = fs.readFileSync('/data/huge.csv');   // ~900 ms",
          "  res.send(transform(csv));",
          "});",
          "",
          "// ✅ NON-BLOCKING — the event loop stays free",
          "app.get('/report', async (req, res) => {",
          "  const csv = await fs.promises.readFile('/data/huge.csv');",
          "  res.send(transform(csv));",
          "});",
          "",
          "// ✅ CPU-bound work goes to a worker thread entirely",
          "const { Worker } = require('worker_threads');",
          "new Worker('./crunch.js', { workerData: { file: path } })",
          "  .once('message', (result) => res.json(result));",
        ],
        captions: [
          "readFileSync parks the ENTIRE server — no other request progresses while it runs",
          "await fs.promises.readFile registers interest and returns control to the loop",
          "while the file reads, the loop happily serves /health, /users, everything else",
          "true CPU number-crunching still can't run on the loop — send it to a Worker",
          "rule of thumb: if it computes for more than ~10 ms, offload it",
        ],
      }, "The pattern that keeps Node fast"),
      compare({
        heading: "CommonJS vs ES Modules",
        left: { label: "CommonJS (require)", points: ["Synchronous, value-based loading", "Conditional require is possible", "__dirname / __filename for free", "Legacy code, default in .js files"], verdict: "still everywhere", color: "amber" },
        right: { label: "ESM (import)", points: ["Static graph — analysable before running", "Top-level await supported", "Named exports, tree-shaking", "Set \"type\": \"module\" or use .mjs"], verdict: "the standard going forward", color: "lime" },
      }, "Which module system, and when"),
      bullets({
        heading: "npm & package.json — the hygiene layer",
        items: [
          { text: "dependencies ship to production; devDependencies don't — categorise honestly", kind: "good" },
          { text: "^1.9.0 allows 1.x.x; ~1.9.0 allows 1.9.x; an exact pin moves nothing", kind: "info", note: "read the range before you install" },
          { text: "package-lock.json freezes the WHOLE tree — commit it and use npm ci", kind: "good", note: "byte-identical installs everywhere" },
          { text: "npm audit monthly; event-stream and ua-parser-js were supply-chain wakes-up calls", kind: "bad", note: "every dependency is imported attack surface" },
        ],
      }, "Dependency discipline is security"),
      scenario({
        heading: "Case study: the login endpoint that froze checkout",
        text: "A retailer's Node API ran password hashing with bcrypt's default cost on the main thread. Cost 12 takes ~300 ms of pure CPU. During the morning rush, thirty concurrent logins queued on one thread — and every unrelated endpoint, including checkout, stalled behind them. P99 latency went from 140 ms to 4.2 seconds. The fix: run bcrypt on a Worker Thread pool sized to the CPU count. P99 returned to 160 ms and stayed flat under 10× the original load.",
      }, "Real-world postmortem"),
      quiz([
        { question: "Which library provides Node's event loop?", options: ["Chrome's Blink engine", "libuv", "Express", "npm"], answer: 1, explain: "libuv is the C library implementing the loop, thread pool and async I/O primitives." },
        { question: "Where do Promise callbacks run relative to the loop phases?", options: ["Only in the timers phase", "In the check phase", "They drain between phases, ahead of the next one", "In a separate OS thread"], answer: 2, explain: "Microtasks (promises, process.nextTick) drain between every phase — they always run before the loop advances." },
        { question: "Your route does a 2-second CPU-heavy sort. Best fix?", options: ["Wrap it in setTimeout(fn, 0)", "Make it async with await", "Move it to a Worker Thread", "Increase UV_THREADPOOL_SIZE to 32"], answer: 2, explain: "setTimeout yields, but the sort still monopolises the single thread once it starts. Only a real thread adds parallelism." },
      ], "Check yourself: the runtime"),
      stat({
        heading: "Why the single thread wins",
        stats: [
          { value: "1", label: "thread serves thousands of idle connections", color: "lime" },
          { value: "4", label: "default libuv worker threads for fs/crypto/dns", color: "amber" },
          { value: "~10 ms", label: "safe ceiling per loop task before latency suffers", color: "rose" },
        ],
      }, "The numbers behind the model"),
      recap({
        points: [
          "Node = V8 (execution) + libuv (event loop, thread pool, async I/O)",
          "Six loop phases; promises drain between phases and always jump the queue",
          "Never block the loop: async I/O everywhere, Worker Threads for CPU work",
          "ESM is the standard; CommonJS lives on in legacy code — know both",
          "Commit lockfiles, use npm ci, audit monthly: dependencies are attack surface",
        ],
      }),
    ],
  },
  {
    lessonId: "les-nb-1-2",
    lessonTitle: "Express.js Routing & Middleware",
    scenes: [
      title({
        eyebrow: "Module 1 · Node Foundations",
        heading: "Express.js Routing & Middleware",
        sub: "The middleware pipeline, Router anatomy, and the production stack in one lesson",
        goals: [
          "Explain Express's middleware pipeline and why order is behaviour",
          "Structure routes with the Router pattern and correct HTTP verbs",
          "Mount the middleware stack every production API needs",
          "Handle errors with 4-arity error middleware registered last",
        ],
        accent: "lime",
      }),
      keyterms([
        { term: "Middleware", definition: "A function (req, res, next) that inspects, mutates, short-circuits or passes the request on.", color: "lime" },
        { term: "Router", definition: "A mini Express app grouping routes and their middleware — the unit of API organisation.", color: "sky" },
        { term: "Route handler", definition: "The terminal middleware for a verb+path match — where your business logic lives.", color: "amber" },
        { term: "Error middleware", definition: "4-argument (err, req, res, next) — registered LAST, catches everything thrown above.", color: "rose" },
        { term: "Status code", definition: "The machine verdict: 2xx succeeded, 4xx caller's fault, 5xx your fault.", color: "violet" },
      ], "The five words you'll use daily"),
      flow({
        heading: "The middleware pipeline in motion",
        sub: "Requests flow through every middleware in registration order — or until one responds",
        nodes: [
          { id: "a", label: "Request", shape: "pill", color: "sky" },
          { id: "b", label: "logger", shape: "rect", color: "slate" },
          { id: "c", label: "helmet", shape: "rect", color: "slate" },
          { id: "d", label: "auth", shape: "rect", color: "amber" },
          { id: "e", label: "validate", shape: "rect", color: "amber" },
          { id: "f", label: "handler", shape: "rect", color: "lime" },
          { id: "g", label: "error mw", shape: "rect", color: "rose" },
        ],
        edges: [ { from: "a", to: "b" }, { from: "b", to: "c" }, { from: "c", to: "d" }, { from: "d", to: "e" }, { from: "e", to: "f" }, { from: "f", to: "g" } ],
      }, "Order is behaviour"),
      code({
        heading: "A production-grade route, line by line",
        sub: "Validate, do the work, answer precisely",
        lang: "javascript",
        codeLines: [
          "import express from 'express';",
          "const app = express();",
          "app.use(express.json());               // parse JSON bodies",
          "",
          "const router = express.Router();",
          "router.post('/orders',",
          "  auth,                                // 1. who are you?",
          "  validate(orderSchema),               // 2. is the input sane?",
          "  async (req, res) => {                // 3. do the work",
          "    const order = await orders.create(req.user.id, req.body);",
          "    res.status(201).json({ data: order });   // 201 = created",
          "  }",
          ");",
          "app.use('/api/v1', router);",
          "",
          "app.use((err, req, res, next) => {     // error middleware, LAST",
          "  req.log.error(err);",
          "  res.status(err.status || 500).json({ error: 'Internal error' });",
          "});",
        ],
        captions: [
          "express.json() must come before any route that reads req.body",
          "auth first — never do work for an unauthenticated caller",
          "validation rejects garbage before it touches your database",
          "201 Created is not optional — clients and tests assert on it",
          "the 4-arity signature is how Express knows it's the error handler",
          "never leak err.message to clients — log details, return something generic",
        ],
      }, "The full anatomy"),
      steps({
        heading: "Middleware every production API mounts",
        sub: "In this order",
        steps: [
          { label: "helmet()", detail: "security headers in one line — CSP, HSTS, no-sniff", color: "lime" },
          { label: "cors({ origin: allowlist })", detail: "configured CORS, never the wildcard in production", color: "sky" },
          { label: "rate limiter", detail: "express-rate-limit — brute force and scraper brake", color: "amber" },
          { label: "express.json({ limit: '100kb' })", detail: "body parsing WITH a cap — huge payloads are an attack", color: "violet" },
          { label: "request ID + logger", detail: "pino-http with a per-request id — the thread through your logs", color: "cyan" },
          { label: "error middleware", detail: "registered last, catches everything thrown above", color: "rose" },
        ],
      }, "The non-negotiable stack"),
      bullets({
        heading: "Routing mistakes with real consequences",
        items: [
          { text: "Route order: /users/:id mounted before /users/me makes 'me' match :id", kind: "bad", note: "specific routes first" },
          { text: "app.get('/users', ...) AND router.get('/users', ...) — duplicates drift apart", kind: "bad", note: "one source of truth per resource" },
          { text: "Async handler that throws → Express 4 silently swallows? No: wrap or use Express 5", kind: "bad", note: "Express 5 catches rejected promises natively" },
          { text: "404 fallback app.use((req,res)=>res.status(404)) mounted after all routes", kind: "good", note: "unknown URLs answer 404, not 'Cannot GET'" },
        ],
      }, "Pitfalls that bite in production"),
      scenario({
        heading: "Case study: the wildcard CORS that leaked accounts",
        text: "A SaaS dashboard shipped with cors() defaults — Access-Control-Allow-Origin: * — while authenticating via an Authorization header. Any site a user visited could fire authenticated requests from their browser. The team's own analytics page demonstrated it: a pasted snippet read another tenant's /api/me. Fix: strict origin allowlist, tokens moved to httpOnly cookies with SameSite, and a regression test asserting the header on every deploy. CORS defaults are a development convenience, never a production posture.",
      }, "Real-world postmortem"),
      quiz([
        { question: "What does calling next() without arguments do?", options: ["Restarts the pipeline", "Passes to the next matching middleware", "Ends the response", "Throws an error"], answer: 1, explain: "next() hands control onward; next(err) jumps straight to the error middleware." },
        { question: "Which status code does a successful POST that creates a resource return?", options: ["200", "201", "204", "302"], answer: 1, explain: "201 Created signals a new resource exists — ideally with a Location header." },
        { question: "Where must the error-handling middleware be registered?", options: ["First", "Anywhere", "Last", "Inside each router"], answer: 2, explain: "Express matches middleware in order — an error handler registered before throwing middleware never sees the error." },
      ], "Check yourself: Express"),
      recap({
        points: [
          "Express is an ordered middleware pipeline — order IS behaviour",
          "Routers group endpoints; validate before business logic",
          "Production stack: helmet, CORS allowlist, rate limit, body cap, request-id logging",
          "Error middleware is 4-arity and always last — log details, return generic messages",
          "Mount specific routes before parameterised ones; end with a 404 fallback",
        ],
      }),
    ],
  },
  {
    lessonId: "les-nb-2-1",
    lessonTitle: "SQL Fundamentals & PostgreSQL",
    scenes: [
      title({
        eyebrow: "Module 2 · Data",
        heading: "SQL Fundamentals & PostgreSQL",
        sub: "Relations, joins, pooling and the queries that power real products",
        goals: [
          "Model data relationally: tables, keys, normalisation basics",
          "Write JOINs and aggregations that answer business questions",
          "Prevent SQL injection with parameterised queries",
          "Pool connections and use transactions correctly",
        ],
        accent: "lime",
      }),
      keyterms([
        { term: "Primary key", definition: "The unique identifier of a row — usually a bigint identity or a UUID.", color: "lime" },
        { term: "Foreign key", definition: "A column referencing another table's primary key — the edge of your data graph.", color: "sky" },
        { term: "Index", definition: "A sorted structure making lookups fast — but writes cost more per index.", color: "amber" },
        { term: "JOIN", definition: "Combining rows across tables on a key — INNER, LEFT, RIGHT, FULL.", color: "violet" },
        { term: "Transaction", definition: "BEGIN → work → COMMIT/ROLLBACK: statements that succeed or fail together.", color: "rose" },
      ], "The vocabulary of relational thinking"),
      diagram({
        heading: "A real schema, drawn honestly",
        sub: "users → orders → order_items — each edge is a foreign key",
        rows: [
          { label: "users", detail: "id PK · email UNIQUE · name · created_at", color: "sky" },
          { label: "orders", detail: "id PK · user_id FK → users.id · status · total_cents · created_at", color: "lime" },
          { label: "order_items", detail: "id PK · order_id FK → orders.id · product_id FK · qty · unit_price_cents", color: "amber" },
          { label: "products", detail: "id PK · sku UNIQUE · name · price_cents · stock", color: "violet" },
        ],
      }, "Relationships are the product"),
      code({
        heading: "The queries that answer real questions",
        sub: "Read these like prose — each clause has a job",
        lang: "sql",
        codeLines: [
          "-- total revenue per user, only users with >5 orders:",
          "SELECT u.email, COUNT(o.id) AS orders,",
          "       SUM(o.total_cents) / 100.0 AS revenue",
          "FROM users u",
          "JOIN orders o ON o.user_id = u.id",
          "GROUP BY u.id, u.email",
          "HAVING COUNT(o.id) > 5",
          "ORDER BY revenue DESC",
          "LIMIT 20;",
          "",
          "-- never build SQL by string concatenation:",
          "SELECT * FROM users WHERE email = $1;   -- ✅ values travel separately",
        ],
        captions: [
          "JOIN pulls related rows; GROUP BY collapses them by user",
          "HAVING filters AFTER grouping — WHERE filters before it",
          "aggregates like COUNT/SUM are the analytical engine of SQL",
          "parameterised queries mean input can never become SQL",
        ],
      }, "SQL as a decision engine"),
      compare({
        heading: "Writes and reads — the index trade-off",
        left: { label: "Read-heavy (typical app)", points: ["Index WHERE and ORDER BY columns", "Only the indexes queries actually use", "UNIQUE constraints instead of duplicate indexes"], verdict: "index freely", color: "lime" },
        right: { label: "Write-heavy (ingestion)", points: ["Every index slows every INSERT/UPDATE", "Consider fewer/composite indexes", "Batch writes into transactions"], verdict: "index sparingly", color: "rose" },
      }, "Every index taxes your writers"),
      bullets({
        heading: "PostgreSQL production instincts",
        items: [
          { text: "Use EXPLAIN ANALYZE before you hand-optimise — hunches are wrong half the time", kind: "good" },
          { text: "Pool connections (pg.Pool); pool size ≈ 10 × cores; mind serverless multipliers", kind: "good" },
          { text: "BIGINT identity vs UUID: UUIDs are client-generatable and merge-friendly, bigger on disk", kind: "info" },
          { text: "Money is integers — store cents, never floats that can't represent 0.1", kind: "info" },
          { text: "ALTER TABLE locks the table — big migrations run in maintenance windows", kind: "bad" },
        ],
      }, "Instincts, not recipes"),
      scenario({
        heading: "Case study: the N+1 report that took 40 seconds",
        text: "A dashboard's weekly report looped over 2,000 users and, per user, ran a query for their orders — 2,001 round trips. With 35 ms of latency each, that's 70 seconds. The fix was one JOIN + GROUP BY, read as a single statement, returning all rows in 180 ms. The same pattern haunts ORMs: always inspect the SQL your ORM generates, add eager loading or raw queries where the ORM multiplies round trips.",
      }, "Real-world postmortem"),
      quiz([
        { question: "HAVING vs WHERE — what's the rule?", options: ["They're identical", "WHERE filters rows; HAVING filters GROUPS after aggregation", "HAVING filters before GROUP BY", "WHERE only works on indexes"], answer: 1, explain: "WHERE runs before grouping; HAVING runs after — use HAVING for conditions on aggregates like COUNT(o.id) > 5." },
        { question: "Why are parameterised queries injection-proof?", options: ["They escape quotes", "They hash inputs", "SQL and values travel in separate channels — input can't alter structure", "They block special characters"], answer: 2, explain: "Escaping and blocklists have edge cases; structural separation has none." },
        { question: "What cost do indexes impose?", options: ["None", "Slower reads", "Slower writes and storage on every INSERT/UPDATE", "Faster writes"], answer: 2, explain: "Indexes must be maintained on every write — the classic read/write trade-off." },
      ], "Check yourself: SQL & Postgres"),
      recap({
        points: [
          "Model with keys and foreign keys first; joins follow the edges",
          "JOIN + GROUP BY + HAVING answer most business questions in one statement",
          "Parameterised queries: structure and values in separate channels",
          "Pool connections; EXPLAIN ANALYZE before optimising",
          "Watch N+1: one well-formed query beats two thousand small ones",
        ],
      }),
    ],
  },
  {
    lessonId: "les-nb-2-2",
    lessonTitle: "MongoDB & Mongoose ODM",
    scenes: [
      title({
        eyebrow: "Module 2 · Data",
        heading: "MongoDB & Mongoose ODM",
        sub: "Documents, schemas, and when a document store beats a relational one",
        goals: [
          "Model data as documents and understand embedding vs referencing",
          "Write CRUD queries with Mongoose and its schema validation",
          "Use indexes and the aggregation pipeline",
          "Choose between SQL and NoSQL with evidence, not hype",
        ],
        accent: "lime",
      }),
      keyterms([
        { term: "Document", definition: "A JSON-like record — one row that holds both the entity and its nested data.", color: "lime" },
        { term: "Embedding", definition: "Storing related data INSIDE the document — fast reads, atomic writes.", color: "amber" },
        { term: "Referencing", definition: "Storing an _id pointing at another collection — joins via $lookup, consistency via you.", color: "sky" },
        { term: "Schema (Mongoose)", definition: "The shape definition + validators + defaults your documents conform to.", color: "violet" },
        { term: "Aggregation pipeline", definition: "Stages ($match → $group → $sort) transforming documents into answers.", color: "rose" },
      ], "Document thinking in one minute"),
      compare({
        heading: "SQL vs MongoDB — language that sells both",
        left: { label: "SQL / PostgreSQL", points: ["Rigid schemas, FK integrity, transactions", "Joins make reporting declarative", "Most products' default choice"], verdict: "choose by default", color: "lime" },
        right: { label: "MongoDB", points: ["Flexible documents, nested data", "Fast horizontal scaling, ops-heavy", "Great for content/catalog shapes"], verdict: "choose with a reason", color: "amber" },
      }, "Both are tools; neither is a religion"),
      code({
        heading: "A Mongoose schema and its queries",
        sub: "Validation at the model boundary — before data ever touches the DB",
        lang: "javascript",
        codeLines: [
          "const userSchema = new Schema({",
          "  email: { type: String, required: true, unique: true, lowercase: true },",
          "  role: { type: String, enum: ['learner','admin'], default: 'learner' },",
          "  profile: { name: String, avatarUrl: String },   // embedded",
          "  courses: [{ type: Schema.Types.ObjectId, ref: 'Course' }], // referenced",
          "}, { timestamps: true });",
          "",
          "await User.create({ email: 'A@x.com' });            // lowercased automatically",
          "await User.find({ role: 'admin' }).sort({ createdAt: -1 }).limit(10);",
          "await Course.aggregate([",
          "  { $match: { published: true } },",
          "  { $group: { _id: '$category', count: { $sum: 1 } } },",
          "]);",
        ],
        captions: [
          "required, enum and lowercase are schema-level contracts — bad data is rejected at the door",
          "timestamps: true gives you createdAt/updatedAt for free",
          "embed the data you ALWAYS read together; reference what grows unboundedly",
          "the aggregation pipeline is MongoDB's GROUP BY + JOIN, stage by stage",
        ],
      }, "Schema-first, even in NoSQL"),
      steps({
        heading: "Embed vs reference — the decision rule",
        sub: "Six questions, one answer",
        steps: [
          { label: "Do you read it WITH the parent every time?", detail: "yes → embed; a profile inside a user is embedded", color: "lime" },
          { label: "Does it grow without bound?", detail: "yes → reference (orders, messages, events)", color: "rose" },
          { label: "Is it shared across parents?", detail: "yes → reference (a course belongs to many learners)", color: "amber" },
          { label: "Do updates need to be atomic together?", detail: "yes → embed (a cart and its items)", color: "violet" },
          { label: "Will you ever report across it?", detail: "that's when $lookup or aggregation joins in", color: "sky" },
        ],
      }, "The classic modelling fork"),
      bullets({
        heading: "MongoDB gotchas that cost teams time",
        items: [
          { text: "No schema enforcement by default — Mongoose softens this; use it", kind: "bad", note: "your app defines truth, so define it well" },
          { text: "Unique indexes on email: create them; duplicate accounts otherwise", kind: "good" },
          { text: "A missing index turns a query into a collection scan", kind: "bad", note: "explain() / .explain('executionStats')" },
          { text: "Deeply nested documents are painful to update and query", kind: "bad", note: "flatten where you can" },
          { text: "Write concerns & replication: test failover, don't discover it in an incident", kind: "info" },
        ],
      }, "Borrow these scar stories"),
      scenario({
        heading: "Case study: the catalogue that outgrew its embedding",
        text: "A storefront embedded every product's reviews inside the product document. Popular items accumulated tens of thousands of reviews; each review push rewrote the whole document, page latency crept up, and pagination became impossible. Migration: reviews became their own collection referencing productId, with a compound index (productId, createdAt). LIST reviews became a ranged query — pagination, stable writes, and the product document stayed small. The design decision that was right at ten reviews became wrong at ten thousand — know when to migrate.",
      }, "Real-world postmortem"),
      quiz([
        { question: "When should you EMBED related data?", options: ["Always", "When you always read it with the parent and it doesn't grow unbounded", "When it's shared across parents", "Never"], answer: 1, explain: "Embedding wins for always-read-together, bounded data; reference the rest." },
        { question: "What provides integrity like foreign keys in Mongo?", options: ["Nothing — referential integrity is yours to maintain", "Unique indexes", "The aggregation pipeline", "Transactions on every query"], answer: 0, explain: "MongoDB doesn't enforce references. Application logic and tests must keep them sound — or use $lookup carefully." },
        { question: "Where does Mongoose validation run?", options: ["In the database", "In the application before the query", "In the browser", "It doesn't exist"], answer: 1, explain: "Mongoose validates at the model boundary — schema, enum, required — before MongoDB sees the document." },
      ], "Check yourself: MongoDB"),
      recap({
        points: [
          "Documents are entities + nested data; embed bounded always-read data, reference the rest",
          "Mongoose schemas put contracts at the model boundary — use its validators",
          "Index what you query; profile with .explain()",
          "The aggregation pipeline is your GROUP BY and JOIN",
          "SQL vs NoSQL is a modelling decision — pick with a reason, not a fashion",
        ],
      }),
    ],
  },
  {
    lessonId: "les-nb-3-1",
    lessonTitle: "JWT Authentication",
    scenes: [
      title({
        eyebrow: "Module 3 · Security",
        heading: "JWT Authentication",
        sub: "Signed tokens, refresh rotation, cookies vs storage, and the mistakes that leak accounts",
        goals: [
          "Explain what a JWT is: header, payload, signature — and what it guarantees",
          "Choose where tokens live and why httpOnly cookies win",
          "Implement refresh-token rotation with reuse detection",
          "Hash passwords with bcrypt and pin verification algorithms",
        ],
        accent: "lime",
      }),
      keyterms([
        { term: "JWT", definition: "A signed, self-describing token: header.payload.signature — verifiable without a DB lookup.", color: "lime" },
        { term: "Signature", definition: "HMAC(secret, base64(header.payload)) — tamper-proof without the secret.", color: "sky" },
        { term: "Access token", definition: "Short-lived (10–15 min) proof of identity for API calls.", color: "amber" },
        { term: "Refresh token", definition: "Long-lived, revocable, and used ONLY to mint new access tokens.", color: "rose" },
        { term: "Rotation", definition: "Each refresh issues a new refresh token; reuse of an old one signals theft.", color: "violet" },
      ], "Five words that define token auth"),
      code({
        heading: "Login, verification, rotation — the core flow",
        sub: "Express + jsonwebtoken + bcrypt in production shape",
        lang: "javascript",
        codeLines: [
          "// register: never store a plaintext password",
          "const hash = await bcrypt.hash(password, 12);",
          "",
          "// login",
          "const ok = await bcrypt.compare(password, user.passwordHash);",
          "if (!ok) return res.status(401).json({ error: { code: 'BAD_CREDENTIALS' } });",
          "",
          "const accessToken = jwt.sign({ sub: user.id, role: user.role },",
          "  process.env.JWT_SECRET, { expiresIn: '10m' });",
          "const refreshToken = await createRotatingRefresh(user.id); // random, hashed in DB",
          "res.cookie('rt', refreshToken, {",
          "  httpOnly: true, secure: true, sameSite: 'strict', path: '/auth',",
          "});",
          "",
          "// verify (middleware)",
          "const payload = jwt.verify(token, process.env.JWT_SECRET,",
          "  { algorithms: ['HS256'] });   // pin the algorithm!",
        ],
        captions: [
          "cost 12 makes each hash ~250 ms — painful for attackers, invisible at login",
          "the access token carries only sub + role — never PII or unverifiable permissions",
          "10-minute access tokens bound the blast radius of theft",
          "the refresh token lives in an httpOnly, Secure, SameSite=strict cookie — JS can't touch it",
          "store a HASH of the refresh token in the DB so a DB leak can't mint sessions",
          "pinning algorithms prevents the classic alg:none / RS256 downgrade attacks",
        ],
      }, "The flow, end to end"),
      steps({
        heading: "Refresh-token rotation, step by step",
        sub: "The industry pattern for revocable stateless auth",
        steps: [
          { label: "issue", detail: "login returns short access token + refresh token (hashed, stored, tied to device)", color: "lime" },
          { label: "use", detail: "API calls send the access token; when it expires, 401", color: "sky" },
          { label: "refresh", detail: "client posts refresh token → new access + NEW refresh token issued", color: "amber" },
          { label: "invalidate", detail: "the old refresh token is marked used — reuse triggers theft detection", color: "rose" },
          { label: "revoke family", detail: "reuse of a rotated token kills the whole token family and forces re-login", color: "violet" },
        ],
      }, "Rotation turns theft into detection"),
      compare({
        heading: "Where should the token live?",
        left: { label: "localStorage (avoid)", points: ["Readable by ANY page script", "One XSS = wholesale token theft", "No SameSite, no httpOnly", "You must build revocation yourself"], verdict: "a breach vector", color: "rose" },
        right: { label: "httpOnly cookie (prefer)", points: ["Invisible to JavaScript", "SameSite + Secure by config", "Path-scoped (/auth only)", "Refresh rotation adds revocation"], verdict: "defence in depth", color: "lime" },
      }, "One decision, most of your exposure"),
      bullets({
        heading: "JWT mistakes that leak accounts",
        items: [
          { text: "alg: 'none' accepted — the signature is decorative", kind: "bad", note: "pin: algorithms: ['HS256']" },
          { text: "Secret committed to the repo or a hardcoded default", kind: "bad", note: "env/config services, rotated on incident" },
          { text: "Trusting payload without verify(), or ignoring exp", kind: "bad", note: "verify() or nothing" },
          { text: "Long-lived access tokens 'for convenience'", kind: "bad", note: "that's what refresh tokens are for" },
          { text: "Putting PII or permissions claims into the token", kind: "bad", note: "claims change; tokens don't" },
        ],
      }, "Each of these has a CVE and a breach report"),
      scenario({
        heading: "Case study: the eternal token",
        text: "A fintech dashboard issued JWT access tokens with a 30-day expiry — set once, 'so the app would stop logging people out'. An employee's laptop was stolen; because the token lived in localStorage with no server-side record, 'log out all devices' was impossible. The token remained valid for weeks until the team emergency-rotated the signing secret, logging out every customer at once. The rewrite: 10-minute access tokens, rotating refresh tokens stored hashed per device, a server-side revocation list, and an admin 'revoke sessions' action. Security now had a dial instead of an on/off switch.",
      }, "Real-world postmortem"),
      quiz([
        { question: "Why must JWT access tokens be short-lived?", options: ["To save bandwidth", "A stolen token is valid until expiry and can't be revoked", "Long tokens break CORS", "To reduce server CPU"], answer: 1, explain: "JWTs are stateless — there's no lookup to check revocation, so expiry IS the revocation mechanism." },
        { question: "Which password hashing is appropriate in 2026?", options: ["MD5", "SHA-256", "bcrypt or argon2", "Base64"], answer: 2, explain: "MD5/SHA are fast — GPUs brute-force them. bcrypt/argon2 are deliberately slow and salted." },
        { question: "What happens when a rotated refresh token is used twice?", options: ["Nothing", "Both tokens get extended", "Theft is assumed — the token family is revoked", "The server ignores it"], answer: 2, explain: "Reuse of a rotated token means someone copied it — revoke the family and force re-login." },
      ], "Check yourself: JWT auth"),
      stat({
        heading: "Password hashing at the frontier",
        stats: [
          { value: "12", label: "bcrypt cost factor ≈ 250 ms on a modern CPU", color: "lime" },
          { value: "10–15 min", label: "sane access-token lifetime", color: "amber" },
          { value: "0", label: "acceptable plaintext passwords, ever", color: "rose" },
        ],
      }, "Slow is the point"),
      recap({
        points: [
          "A JWT is header.payload.signature — verifiable without a DB lookup",
          "Access tokens: short-lived, minimal claims, algorithm pinned",
          "Refresh tokens rotate; reuse revokes the family; store them hashed",
          "httpOnly + Secure + SameSite cookies beat localStorage, always",
          "bcrypt/argon2 with real cost factors; plaintext is a career-ending bug",
        ],
      }),
    ],
  },
  {
    lessonId: "les-nb-4-1",
    lessonTitle: "API Security Best Practices",
    scenes: [
      title({
        eyebrow: "Module 3 · Security",
        heading: "API Security Best Practices",
        sub: "The layered defence that survives real attacks — rate limits, validation, CSP, secrets",
        goals: [
          "Apply rate limiting, payload caps and input validation by default",
          "Understand and fix OWASP API Top 10 exposure classes",
          "Configure CORS, security headers and SSRF guards",
          "Manage secrets and logging without leaking them",
        ],
        accent: "lime",
      }),
      keyterms([
        { term: "Rate limiting", definition: "Capping requests per client/IP — the brute-force and scraping brake.", color: "lime" },
        { term: "SSRF", definition: "Server-Side Request Forgery — abusing your server to reach internal services.", color: "rose" },
        { term: "CSP", definition: "Content-Security-Policy header — whitelisting what your page may load.", color: "sky" },
        { term: "IDOR", definition: "Insecure Direct Object Reference — /orders/42 leaking another user's order.", color: "violet" },
        { term: "OWASP API Top 10", definition: "The industry list of the ten most exploited API weaknesses.", color: "amber" },
      ], "The defence vocabulary"),
      diagram({
        heading: "The layered defence",
        sub: "Each layer stops the attacks that reach the next",
        rows: [
          { label: "Edge", detail: "WAF + TLS + DDoS protection — the outermost wall", color: "slate" },
          { label: "Gateway", detail: "rate limiting · request caps · origin allowlists · auth checks", color: "sky" },
          { label: "Application", detail: "validation · authorization on every object · SSRF guards · safe errors", color: "rose" },
          { label: "Data", detail: "encryption at rest · least-privilege DB users · audit logs", color: "violet" },
        ],
      }, "Security is a stack, not a line"),
      code({
        heading: "The middleware most APIs forget",
        sub: "Five lines that close several Top-10 entries",
        lang: "javascript",
        codeLines: [
          "import rateLimit from 'express-rate-limit';",
          "app.use(rateLimit({ windowMs: 60_000, limit: 60, standardHeaders: true }));",
          "",
          "app.post('/api/webhooks/payment', async (req, res) => {",
          "  // verify the signature BEFORE trusting the payload",
          "  const ok = crypto.timingSafeEqual(",
          "    Buffer.from(req.headers['x-signature'] ?? ''),",
          "    Buffer.from(hmac(process.env.WEBHOOK_SECRET, rawBody)),",
          "  );",
          "  if (!ok) return res.status(401).end();",
          "});",
          "",
          "app.get('/api/v1/fetch', async (req, res) => {",
          "  const url = new URL(req.query.url);          // SSRF guard:",
          "  if (['localhost', '169.254.169.254'].includes(url.hostname))",
          "    return res.status(400).json({ error: 'Host blocked' });",
          "});",
        ],
        captions: [
          "rate limiting is the cheapest brute-force defence you can buy",
          "webhook endpoints must verify signatures — unauthenticated webhooks are an open door",
          "timingSafeEqual avoids leaking signature comparisons through timing",
          "SSRF guards block requests to internal metadata endpoints (169.254.169.254!)",
        ],
      }, "Oral names, real lines"),
      bullets({
        heading: "OWASP API Top 10, in one minute",
        items: [
          { text: "IDOR — object-level authorization missing: check ownership on EVERY resource access", kind: "bad", note: "BOLA" },
          { text: "Unlimited pagination/page sizes — cap limits", kind: "bad", note: "API2:2023" },
          { text: "Excessive data exposure — return only the fields the client needs (DTOs)", kind: "bad" },
          { text: "Broken auth flows — password reset, OTP, refresh: each is an attack surface", kind: "bad" },
          { text: "SSRF via 'fetch this URL' features — block internal/loopback/metadata hosts", kind: "bad" },
          { text: "Misconfigured CORS is an access-control bypass in disguise", kind: "bad" },
        ],
      }, "Your annual checklist, condensed"),
      compare({
        heading: "Errors, logging & secrets",
        left: { label: "Tell clients", points: ["Status codes that mean something", "Stable error codes (VALIDATION_FAILED)", "details for form fields", "a requestId to quote in support"], verdict: "contract-safe", color: "lime" },
        right: { label: "Never expose", points: ["Stack traces and SQL queries", "Internal hostnames and versions", "Secrets, tokens, key material", "PII you don't need to return"], verdict: "leak-safe", color: "rose" },
      }, "The error/loss boundary"),
      scenario({
        heading: "Case study: the unauthenticated webhook",
        text: "A payment provider's webhook endpoint parsed payloads and updated orders — with no signature check, because 'the provider's IP is trusted'. A scanner found the endpoint and began replaying captured payment events: order statuses flipped to paid with no money received. Ten minutes of craft was all it took. The fix: verify each webhook's HMAC signature with timingSafeEqual before any processing, plus idempotency keys on the handler. A later audit found the same missing-signature pattern in three more integrations — all fixed in one pass.",
      }, "Real-world postmortem"),
      quiz([
        { question: "What is the primary purpose of rate limiting?", options: ["Saving bandwidth", "Brute-force and abuse braking — caps per client", "Replacing authentication", "Faster responses"], answer: 1, explain: "It bounds how many guesses/requests one source can throw at you per window." },
        { question: "169.254.169.254 is special because…", options: ["It's a documentation IP", "It's the cloud metadata endpoint — an SSRF jackpot", "It's IPv6-only", "It's blocked by the OS"], answer: 1, explain: "Cloud metadata servers live at that link-local address; SSRF there exposes IAM credentials." },
        { question: "Your webhook handler must…", options: ["Trust the sender's IP", "Verify a cryptographic signature before processing", "Redirect to the dashboard", "Log the raw body publicly"], answer: 1, explain: "IPs are spoofable and change; HMAC signatures prove the payload came from the real provider." },
      ], "Check yourself: API security"),
      recap({
        points: [
          "Defence is layered: edge → gateway → application → data",
          "Rate limit, cap payloads, verify webhook signatures, guard SSRF",
          "Authorize on every object access — IDOR is the #1 API vulnerability",
          "Return contract-safe errors; log (and never expose) secrets, traces, internals",
          "Run the OWASP API Top 10 as an annual review checklist",
        ],
      }),
    ],
  },
  {
    lessonId: "les-nb-5-1",
    lessonTitle: "Unit & Integration Testing",
    scenes: [
      title({
        eyebrow: "Module 4 · Quality",
        heading: "Unit & Integration Testing",
        sub: "The testing pyramid, the seam, and tests that pay for themselves",
        goals: [
          "Write focused unit tests for pure logic and helpers",
          "Test API routes with supertest against the real Express app",
          "Mock boundaries — time, network, database — deliberately",
          "Measure and defend coverage where it matters",
        ],
        accent: "lime",
      }),
      keyterms([
        { term: "Unit test", definition: "One function, isolated — its dependencies mocked or pure.", color: "lime" },
        { term: "Integration test", definition: "Several real units together — the Express app + database.", color: "sky" },
        { term: "Test double", definition: "A stand-in (stub/mock/spy) for a boundary — clock, HTTP, DB.", color: "amber" },
        { term: "Seam", definition: "The point where you can substitute reality — dependency injection gives you seams.", color: "violet" },
        { term: "Coverage", definition: "The % of lines/statements/branches tests execute — a floor, not a goal.", color: "rose" },
      ], "Testing vocabulary that pays"),
      diagram({
        heading: "The testing pyramid",
        sub: "Many cheap unit tests, fewer expensive integration tests, a handful of E2E",
        rows: [
          { label: "E2E (few)", detail: "Playwright: register → order → pay — real browser, real stack", color: "rose" },
          { label: "Integration (some)", detail: "supertest against Express + test database — routes, auth, transactions", color: "amber" },
          { label: "Unit (many)", detail: "pure helpers, validation, business rules — milliseconds each", color: "lime" },
        ],
      }, "Speed and trust, balanced"),
      code({
        heading: "Testing a route, properly",
        sub: "The seam is the Express app itself",
        lang: "javascript",
        codeLines: [
          "// app.ts exports the express app — tests import it",
          "import request from 'supertest';",
          "import { app } from './app';",
          "",
          "describe('POST /api/v1/orders', () => {",
          "  it('creates an order and returns 201', async () => {",
          "    const res = await request(app)",
          "      .post('/api/v1/orders')",
          "      .set('authorization', `Bearer ${tokenFor('learner@x.com')}`)",
          "      .send({ productId: 'p_1', qty: 2 });",
          "    expect(res.status).toBe(201);",
          "    expect(res.body.data.totalCents).toBe(3998);",
          "  });",
          "",
          "  it('rejects invalid payloads with 400', async () => {",
          "    const res = await request(app)",
          "      .post('/api/v1/orders')",
          "      .send({ qty: -3 });",
          "    expect(res.status).toBe(400);",
          "    expect(res.body.error.code).toBe('VALIDATION_FAILED');",
          "  });",
          "});",
        ],
        captions: [
          "exporting app separately from listen() makes the whole server testable",
          "supertest runs real middleware, real routes, real validation — no mocking",
          "a disposable test database per run keeps tests isolated",
          "assert on status AND error codes — that's your API contract",
        ],
      }, "The integration seam"),
      bullets({
        heading: "What to mock — and what never to mock",
        items: [
          { text: "Mock: the clock, external HTTP, message queues, third-party SDKs", kind: "good" },
          { text: "Mock: file system writes and email senders in unit tests", kind: "good" },
          { text: "NEVER mock: your validation logic, your own business rules, your own routes", kind: "bad", note: "mocking your code tests the mock" },
          { text: "NEVER mock: the database in integration tests — use a real test DB", kind: "bad" },
        ],
      }, "Mock the boundary, not the behaviour"),
      steps({
        heading: "A test suite that CI can trust",
        sub: "The full pyramid in one pipeline",
        steps: [
          { label: "1. unit", detail: "pure logic & validators — milliseconds, hundreds of cases", color: "lime" },
          { label: "2. integration", detail: "routes + DB in a disposable container — the API contract", color: "amber" },
          { label: "3. contract", detail: "OpenAPI schema diffing — client can't drift from server", color: "sky" },
          { label: "4. E2E", detail: "the three money paths in a real browser", color: "rose" },
          { label: "5. coverage floor", detail: "CI fails under threshold — and you review WHAT the tests prove", color: "violet" },
        ],
      }, "Every push, automatically"),
      scenario({
        heading: "Case study: the test that was testing a mock",
        text: "A team's 'integration tests' imported an in-memory mock repository instead of the database, because the real Postgres 'slowed CI down'. After a schema migration renamed a column, every test passed while production crashed instantly. The lesson: integration tests must cross REAL boundaries — a disposable Postgres container costs five seconds in CI and catches what mocks can't. They moved to testcontainers, and the same migration that broke the world is now caught in CI before merging.",
      }, "Real-world postmortem"),
      quiz([
        { question: "What does the pyramid's bottom (largest) layer consist of?", options: ["E2E tests", "Integration tests", "Unit tests", "Manual QA"], answer: 2, explain: "Fast, cheap, numerous unit tests form the base; expensive E2E is the tip." },
        { question: "Which boundary is safe to mock in a unit test?", options: ["Your own business rules", "Validation logic", "The system clock / external HTTP", "Your routes"], answer: 2, explain: "Mock what you don't own (fields: time, network, queues); never mock the code under test." },
        { question: "Why not mock the database in 'integration' tests?", options: ["It's slower", "Mocks hide schema drift and real SQL behaviour", "Mocks aren't allowed in Node", "The DB is too slow to start"], answer: 1, explain: "A mocked repository never exercises real SQL or migrations — it can green-light a breaking change." },
      ], "Check yourself: testing"),
      recap({
        points: [
          "Pyramid: many units, some integrations, few E2E — each layer crosses real boundaries",
          "Export app, not listen — supertest turns your routes into testable units",
          "Mock what you don't own: clock, network, queues; never your own logic",
          "Integration tests use a real disposable database — mocks hide drift",
          "Coverage is a floor with context, not a number to worship",
        ],
      }),
    ],
  },
  {
    lessonId: "les-nb-6-1",
    lessonTitle: "WebSockets with Socket.io",
    scenes: [
      title({
        eyebrow: "Module 4 · Real-Time",
        heading: "WebSockets with Socket.io",
        sub: "Full-duplex connections, rooms, and real-time features that scale honestly",
        goals: [
          "Contrast WebSocket with HTTP polling and know when each wins",
          "Establish Socket.io connections, rooms and events",
          "Authenticate and authorize socket connections",
          "Design for scale: horizontal connections and Redis adapters",
        ],
        accent: "lime",
      }),
      keyterms([
        { term: "WebSocket", definition: "A persistent, full-duplex TCP connection — server pushes without being asked.", color: "lime" },
        { term: "Long polling", definition: "HTTP requests held open until there's data — the pre-WebSocket pattern.", color: "amber" },
        { term: "Room", definition: "A server-side grouping of sockets — broadcast to exactly the right set.", color: "sky" },
        { term: "Handshake", definition: "The initial HTTP Upgrade request where auth claims are verified.", color: "rose" },
        { term: "Redis adapter", definition: "The connective tissue across multiple Node instances for rooms/broadcasts.", color: "violet" },
      ], "Real-time vocabulary"),
      compare({
        heading: "Polling vs WebSocket vs SSE",
        left: { label: "Long polling", points: ["Request → wait → data → repeat", "Simple, universally supported", "High latency, chatty"], verdict: "legacy", color: "amber" },
        middle: { label: "SSE", points: ["Server → client, one-way stream", "HTTP-based, auto-reconnect built in", "No client→server streaming"], verdict: "notifications, feeds", color: "sky" },
        right: { label: "WebSocket", points: ["Full duplex over one connection", "Low latency, binary frames", "Reconnect handling is on YOU"], verdict: "chat, games, live collab", color: "lime" },
      }, "Pick the protocol that matches the direction of data"),
      code({
        heading: "Auth'd chat in ~40 lines",
        sub: "Verify identity at the handshake, scope events to rooms",
        lang: "javascript",
        codeLines: [
          "import { Server } from 'socket.io';",
          "const io = new Server(httpServer, { cors: { origin: ALLOWLIST } });",
          "",
          "io.use((socket, next) => {                       // handshake middleware",
          "  const token = socket.handshake.auth?.token;",
          "  try { socket.user = jwt.verify(token, SECRET, { algorithms: ['HS256'] });",
          "    next(); }",
          "  catch { next(new Error('unauthorized')); }",
          "});",
          "",
          "io.on('connection', (socket) => {",
          "  socket.join(`room:${socket.user.sub}`);        // personal room",
          "  socket.on('message:send', (msg) => {",
          "    io.to(`room:${msg.to}`).emit('message:new', { from: socket.user.sub, msg });",
          "  });",
          "  socket.on('disconnect', () => socket.leaveAll());",
          "});",
        ],
        captions: [
          "CORS matters for sockets too — an open origin lets any site open sockets as your users",
          "authenticate in the handshake — never trust socket payloads for identity",
          "rooms give you targeted broadcast: message → exactly one user's listeners",
          "disconnect cleanup prevents leaks in the room membership",
        ],
      }, "The core pattern"),
      steps({
        heading: "Scaling sockets honestly",
        sub: "One instance is a demo; two instances is a design problem",
        steps: [
          { label: "1. multiple instances", detail: "load-balanced Node processes — each holds only ITS connections", color: "lime" },
          { label: "2. Redis adapter", detail: "io.redisAdapter({ pubClient, subClient }) — broadcasts fan across instances", color: "sky" },
          { label: "3. sticky sessions", detail: "a socket's HTTP+WS pair must hit the same instance — LB configure!", color: "amber" },
          { label: "4. reconnect + state", detail: "clients reconnect; keep session/room state in Redis, not process memory", color: "rose" },
          { label: "5. backpressure", detail: "slow consumers need queues — 'socket.buffer.softLimit' and company", color: "violet" },
        ],
      }, "The growth pattern that bites"),
      bullets({
        heading: "Real-time footguns",
        items: [
          { text: "Emitting to socket.id across instances sends to the wrong place — use rooms", kind: "bad" },
          { text: "Sending every keystroke of a collaborative editor | TCP-fragment storms; debounce", kind: "bad" },
          { text: "No heartbeat: dead connections linger; Socket.io sends pings by default — keep them", kind: "good" },
          { text: "Input validation on sockets: a broadcast of user text is XSS payload delivery", kind: "bad" },
          { text: "Rate limit message:send per user — spam is a feature for attackers", kind: "good" },
        ],
      }, "Borrow these scar stories"),
      scenario({
        heading: "Case study: the chat that stopped at one instance",
        text: "A startup's chat worked flawlessly in development — one Node instance. At launch they scaled to four instances behind a load balancer, and messages disappeared randomly: user A's socket lived on instance 1, user B's on instance 3, and io.to() only reached the local cluster. The fix: the Socket.io Redis adapter + sticky sessions, in one afternoon. The lesson: real-time code must be designed multi-instance from the first line — 'it works locally' is the first casualty of scale.",
      }, "Real-world postmortem"),
      quiz([
        { question: "Where must authentication happen for a socket connection?", options: ["On every emitted message", "In the handshake middleware, before connection", "After the first broadcast", "Never — sockets are trusted"], answer: 1, explain: "Handshake middleware runs before connection — reject early, trust the token you verified there." },
        { question: "Why do scaled-out Socket.io deployments need the Redis adapter?", options: ["Redis is faster", "Broadcasts must fan out across all instances' connections", "Redis replaces the database", "It's required by law"], answer: 1, explain: "Without it, io.to() only reaches sockets on the local instance." },
        { question: "WebSocket vs SSE — which direction of data suggests SSE?", options: ["Bidirectional chat", "Server pushing notifications to clients", "Client uploading files", "Peer-to-peer gaming"], answer: 1, explain: "SSE is one-way server→client over HTTP — ideal for feeds and alerts without socket complexity." },
      ], "Check yourself: WebSockets"),
      recap({
        points: [
          "WebSocket = persistent full duplex; SSE = one-way push; polling = legacy",
          "Authenticate in the handshake; CORS-lock origins",
          "Rooms scope broadcasts; never stale socket.id across instances",
          "Scale = Redis adapter + sticky sessions + reconnect/state in Redis",
          "Rate-limit and validate socket input like any other endpoint",
        ],
      }),
    ],
  },
];

// ════════════════════════════════════════════════════════════════
// FULLSTACK CAPSTONE — deep scripts (course-fullstack-capstone)
// ════════════════════════════════════════════════════════════════

export const deepCapstone: LessonVideoScript[] = [
  {
    lessonId: "les-fc-1-1",
    lessonTitle: "Requirements & User Stories",
    scenes: [
      title({
        eyebrow: "Capstone · Kickoff",
        heading: "Requirements & User Stories",
        sub: "From vague idea to stories you can estimate, build against and demo",
        goals: [
          "Write user stories that name actors, goals and value",
          "Split epic ideas into vertically-sliceable stories",
          "Define acceptance criteria that make 'done' testable",
          "Prioritise for the demo, not for perfection",
        ],
        accent: "amber",
      }),
      keyterms([
        { term: "User story", definition: "'As a <role>, I want <goal>, so that <value>' — the promise, not the plan.", color: "lime" },
        { term: "Epic", definition: "A story too big to estimate — split it into vertical slices.", color: "sky" },
        { term: "Acceptance criteria", definition: "Given/When/Then statements that define when a story is done.", color: "amber" },
        { term: "MoSCoW", definition: "Must / Should / Could / Won't — the prioritisation ladder.", color: "rose" },
        { term: "Definition of Done", definition: "The team's shared bar: tested, reviewed, deployed, documented.", color: "violet" },
      ], "Requirements vocabulary that works"),
      code({
        heading: "Stories that survive contact with reality",
        sub: "The difference between a wish and a requirement",
        lang: "text",
        codeLines: [
          "❌ 'Users should be able to sign up.'          — a wish",
          "",
          "✅ As a visitor,",
          "   I want to create an account with my email and password,",
          "   so that I can save my progress and resume later.",
          "",
          "Acceptance criteria:",
          "  Given I'm a new visitor,",
          "  When I submit a valid email + strong password",
          "  Then I land on my dashboard and receive a confirmation email",
          "  And duplicate emails are rejected with a clear message",
          "",
          "  When I submit an invalid email",
          "  Then I see a field-level error and no account is created",
        ],
        captions: [
          "a story names the ACTOR, the GOAL and the VALUE — in one sentence",
          "acceptance criteria are Given/When/Then — testable, not vibes",
          "the 'And' lines are where hidden work lives — write them ALL down",
          "error paths are requirements, not afterthoughts",
        ],
      }, "Formatting is 50% of the discipline"),
      steps({
        heading: "Splitting an epic into slices",
        sub: "Each slice crosses every layer and delivers something demoable",
        steps: [
          { label: "epic: payments", detail: "too big to estimate — too risky to build whole", color: "rose" },
          { label: "slice 1", detail: "mock checkout: collect card details, fake success — UI + validation only", color: "lime" },
          { label: "slice 2", detail: "Stripe test mode: real charge, webhook updates order status", color: "sky" },
          { label: "slice 3", detail: "receipts + refunds admin screen", color: "amber" },
          { label: "rule", detail: "every slice is demoable, testable, releasable — value in every sprint", color: "violet" },
        ],
      }, "Vertical slices, not horizontal moonshots"),
      compare({
        heading: "Requirements that help vs hurt",
        left: { label: "Write", points: ["Stories with acceptance criteria", "Edge cases (empty, duplicate, offline)", "Explicit non-goals", "Success metrics per feature"], verdict: "buildable", color: "lime" },
        right: { label: "Avoid", points: ["'Basically like Uber but…'", "UI pixels specified before logic", "Requirements hidden in one reviewer's head", "Undefined success"], verdict: "unbuildable", color: "rose" },
      }, "The words you choose become the build"),
      bullets({
        heading: "Prioritising for a capstone demo",
        items: [
          { text: "Must: the three journeys your demo narrates — end to end, polished", kind: "good" },
          { text: "Should: the features that answer 'why is this better than a form?'", kind: "info" },
          { text: "Could: nice-to-haves — build ONLY if Must are green", kind: "info" },
          { text: "Won't: write them down so reviewers know you chose deliberately", kind: "good" },
          { text: "A broken Must feature in the demo costs more than an absent Could", kind: "bad", note: "cut scope early, polish the spine" },
        ],
      }, "MoSCoW, capstone edition"),
      scenario({
        heading: "Case study: the story that ate a week",
        text: "A capstone team's requirements said 'users can manage their bookings'. Two developers heard different things: one built an admin grid, the other a drag-drop calendar. Neither was what the stakeholder meant (email notifications + cancel flow). A week of code was thrown away. After that, every story carried acceptance criteria written WITH the stakeholder, reviewed in the kickoff. The grid/calendar ambiguity — a missing actor ('who manages?') and goal ('what outcome?') — never happened again. Requirements are a team sport, and the story format is the shared language.",
      }, "Real-world postmortem"),
      quiz([
        { question: "Which part of 'As a guest, I want to book a tour, so that I can secure a slot' is the VALUE?", options: ["As a guest", "I want to book a tour", "So that I can secure a slot", "None of them"], answer: 2, explain: "The 'so that' clause is the point — the outcome the feature exists to deliver." },
        { question: "What makes acceptance criteria good?", options: ["They're optimistic", "They're testable Given/When/Then statements", "They're written in code", "They name the technology"], answer: 1, explain: "Testable criteria let you know — automatically, even — when done is actually done." },
        { question: "What does 'vertical slice' mean during story splitting?", options: ["Build the database layer first", "One thin feature across all layers, demoable end-to-end", "Stack the UI screens", "Work top-down in the codebase"], answer: 1, explain: "Each slice crosses storage → logic → API → UI, so every sprint delivers something working." },
      ], "Check yourself: requirements"),
      recap({
        points: [
          "Stories: actor + goal + value in one sentence, acceptance criteria attached",
          "Split epics into vertical slices — each demoable, testable, releasable",
          "Write edge cases and non-goals explicitly; hidden requirements become surprises",
          "MoSCoW with demo-first priorities; polish the spine before the wings",
          "Requirements are a team agreement — written, reviewed, shared",
        ],
      }),
    ],
  },
];