import {
  title, keyterms, bullets, steps, diagram, flow, code, terminal, compare, scenario, quiz, stat, recap,
  type LessonVideoScript,
} from "./core";

// ════════════════════════════════════════════════════════════════
// TERRAFORM / INFRASTRUCTURE AS CODE — deep scripts (course-iac-terraform)
// ════════════════════════════════════════════════════════════════

export const deepTerraform: LessonVideoScript[] = [
  {
    lessonId: "les-tf-1-1",
    lessonTitle: "What is Infrastructure as Code?",
    scenes: [
      title({
        eyebrow: "Module 1 · IaC Foundations",
        heading: "What is Infrastructure as Code?",
        sub: "Declarative config, the plan/apply loop, state — and why cloud without IaC is an incident",
        goals: [
          "Explain IaC's promise: reproducible, reviewable, versioned infrastructure",
          "Compare declarative (Terraform) vs imperative (CLI scripts) approaches",
          "Understand the plan/apply lifecycle and what state is for",
          "Model environments: dev/stage/prod from the same code",
        ],
        accent: "teal",
      }),
      keyterms([
        { term: "Declarative", definition: "You declare the END STATE; the tool figures out the steps. Terraform's whole model.", color: "lime" },
        { term: "State", definition: "Terraform's record of what it created — the source of truth for diffs and deletes.", color: "amber" },
        { term: "Plan", definition: "A dry-run diff: what will be created, changed, destroyed — readable before you commit.", color: "sky" },
        { term: "Apply", definition: "Executing the plan — the only step that touches real cloud resources.", color: "violet" },
        { term: "Drift", definition: "The difference between declared state and reality — something clicked a console button.", color: "rose" },
      ], "Five words that define the IaC mindset"),
      compare({
        heading: "Imperative vs declarative",
        left: { label: "Imperative (CLI scripts)", points: ["You script every step: create → configure → attach", "Skip a step and half-built state happens", "Nobody runs the same smoke test", "Drift is invisible until it explodes"], verdict: "brittle at scale", color: "rose" },
        right: { label: "Declarative (Terraform)", points: ["You state the end: 'two t3.micros + RDS'", "Terraform plans the steps for you", "Same code → dev/stage/prod", "Drift is a visible diff on every plan"], verdict: "reproducible", color: "lime" },
      }, "The fork every team faces"),
      code({
        heading: "The same resource, two mindsets",
        sub: "Ten lines of HCL vs an undocumented sequence of ~10 CLI commands",
        lang: "hcl",
        codeLines: [
          "resource \"aws_instance\" \"web\" {",
          "  ami           = data.aws_ami.ubuntu.id",
          "  instance_type = \"t3.micro\"",
          "  vpc_security_group_ids = [aws_security_group.web.id]",
          "  iam_instance_profile = aws_iam_instance_profile.web.name",
          "  tags = { Name = \"web-prod\" }",
          "}",
          "",
          "# the CLI alternative: ~10 commands, each with flags, in exactly the right order,",
          "# run by Someone who remembers the 'special' order from last time",
        ],
        captions: [
          "HCL = HashiCorp Configuration Language — Terraform's domain-specific declarative DSL",
          "the AMI is looked up via data source — not hardcoded to an image that ages",
          "security groups and IAM are their own resources — dependency graph, not sequence",
          "tags make the resource findable and cost-attributable",
        ],
      }, "Uno script, no sequence"),
      steps({
        heading: "The plan/apply loop",
        sub: "Every change to infrastructure runs the same four steps",
        steps: [
          { label: "1. init", detail: "download providers and modules — the first command of every project", color: "sky" },
          { label: "2. plan", detail: "compute the diff from state — read it, review it, question it", color: "violet" },
          { label: "3. apply", detail: "execute exactly what was planned — destroy-warnings are final warnings", color: "rose" },
          { label: "4. commit the state", detail: "state in a remote backend + your config in git = full history", color: "lime" },
        ],
      }, "Repeatable, reviewable, reversible"),
      bullets({
        heading: "What IaC actually buys you",
        items: [
          { text: "Environments become branches of the same code — dev ≠ 'the one with the weird config'", kind: "good" },
          { text: "PR review of infrastructure: plans in CI comments mean nobody merges blind", kind: "good" },
          { text: "Reproducibility: a fresh environment from the config in under an hour", kind: "good" },
          { text: "Kill-and-rebuild: dispose environments like branches — the cloud bill drops", kind: "good" },
          { text: "Without state: drift is a console click away from being a production outage", kind: "bad" },
        ],
      }, "The promises, made concrete"),
      scenario({
        heading: "Case study: the environment nobody could rebuild",
        text: "A company's staging environment had grown from console clicks over 14 months. When the compliance audit demanded 'reproduce staging in a sandbox', three engineers spent eleven days reverse-engineering it — and the reproduction differed in subtle ways that surfaced six weeks later as a production incident. The rebuild as code took three weeks, after which spin-up of a pristine staging was a CI job. The audit cost became the implementation investment; the doc of 'what we think staging contains' became terraform code with review trail.",
      }, "Real-world postmortem"),
      quiz([
        { question: "What is Terraform's state file?", options: ["Documentation", "Its record of created resources — the diff basis and delete list", "A cache for faster runs", "A backup of your code"], answer: 1, explain: "State is the tool's memory of reality — without it, Terraform can't plan diffs or delete safely." },
        { question: "Which command executes changes?", options: ["plan", "apply", "init", "validate"], answer: 1, explain: "plan previews; apply executes — the line between safe review and real change." },
        { question: "What is drift?", options: ["Network lag", "The gap between declared and actual infrastructure", "A Terraform warning", "A state file backup"], answer: 1, explain: "Clicking console buttons while Terraform owns the resource creates drift — detected on the next plan." },
      ], "Check yourself: IaC"),
      stat({
        heading: "IaC by the numbers",
        stats: [
          { value: "4", label: "commands: init → plan → apply → commit state", color: "lime" },
          { value: "1", label: "source of truth — the git repo, not the console", color: "amber" },
          { value: "100%", label: "of incidents trace back to drift when config was managed by hand", color: "rose" },
        ],
      }, "Boring process, extraordinary reliability"),
      recap({
        points: [
          "Declarative config: state the end, let the tool plan the steps",
          "State is Terraform's memory — remote backends make it shared and safe",
          "plan → review → apply: every change is a reviewable diff",
          "Environments from the same code: dev/stage/prod as variables, not forks",
          "Console clicks create drift; drift creates incidents; code creates history",
        ],
      }),
    ],
  },
  {
    lessonId: "les-tf-2-1",
    lessonTitle: "Variables, Locals & Outputs",
    scenes: [
      title({
        eyebrow: "Module 2 · Language",
        heading: "Variables, Locals & Outputs",
        sub: "The three valves that turn one config into every environment",
        goals: [
          "Declare and type variables; pass values via file, env and CLI",
          "Use locals for derived values that stay DRY",
          "Expose outputs and consume them across modules and CLI",
          "Apply validation and sensitive flags to variables",
        ],
        accent: "teal",
      }),
      keyterms([
        { term: "Variable", definition: "The public input to a config or module — typed, optional, validated.", color: "lime" },
        { term: "Local", definition: "A derived value computed from variables — module-internal, never overridden by callers.", color: "sky" },
        { term: "Output", definition: "A published result — resource attributes other configs and scripts can consume.", color: "amber" },
        { term: "TF_VAR_", definition: "Environment-variable prefix letting CI/automation inject values without file edits.", color: "violet" },
        { term: "Sensitive", definition: "Marks a value as secret — Terraform redacts it in plans and output.", color: "rose" },
      ], "The three valves of a Terraform config"),
      code({
        heading: "One config, every environment",
        sub: "Variabilise the things that differ: names, sizes, counts, credentials",
        lang: "hcl",
        codeLines: [
          "variable \"environment\" {",
          "  type        = string",
          "  description = \"dev | stage | prod\"",
          "  validation {",
          "    condition     = contains([\"dev\", \"stage\", \"prod\"], var.environment)",
          "    error_message = \"environment must be dev, stage or prod.\"",
          "  }",
          "}",
          "variable \"db_password\" { type = string; sensitive = true }",
          "",
          "locals {",
          "  name_prefix = \"app-${var.environment}\"",
          "  instance_type = var.environment == \"prod\" ? \"m6i.large\" : \"t3.micro\"",
          "}",
          "",
          "output \"web_url\" {",
          "  value = aws_instance.web.public_dns",
          "  description = \"The app entry point\"",
          "}",
        ],
        captions: [
          "validation turns typos into errors at plan time — 'stage' with one 'g' fails loudly",
          "sensitive redacts the password from plans and logs — secrets stay unreadable",
          "locals keep derived values in one place — change the rule once",
          "outputs let other modules and CI consume your results without guessing",
        ],
      }, "The language of environment variance"),
      flow({
        heading: "What overrides what",
        sub: "Higher-precedence sources win — check your override assumptions",
        nodes: [
          { id: "a", label: "CLI -var flag", shape: "rect", color: "rose" },
          { id: "b", label: "TF_VAR_ env", shape: "rect", color: "amber" },
          { id: "c", label: "terraform.tfvars", shape: "rect", color: "sky" },
          { id: "d", label: "auto tfvars", shape: "rect", color: "violet" },
          { id: "e", label: "default", shape: "rect", color: "lime" },
          { id: "f", label: "Value", shape: "pill", color: "slate" },
        ],
        edges: [ { from: "a", to: "f" }, { from: "b", to: "f" }, { from: "c", to: "f" }, { from: "d", to: "f" }, { from: "e", to: "f" } ],
      }, "Precedence, in descending order"),
      bullets({
        heading: "Variable hygiene that saves incidents",
        items: [
          { text: "Terraform.tfvars in git for non-secrets; secrets via TF_VAR_/vault at apply time", kind: "good" },
          { text: "terraform.tfvars (no prefix) is auto-loaded — a committed file named that way wins silently", kind: "bad", note: "name secret files *.auto.tfvars temporarily or use -var-file explicitly" },
          { text: "Type everything: list(string), map(string), object({}) — untyped novices? No", kind: "info" },
          { text: "Validate early, validate often: conditions beat post-hoc drift complaints", kind: "good" },
        ],
      }, "Prevent the silent override"),
      steps({
        heading: "Passing values into a module",
        sub: "Modules are functions: inputs are variables, outputs are the return values",
        steps: [
          { label: "1. declare", detail: "variables with types, defaults and validation inside the module", color: "sky" },
          { label: "2. call", detail: "module \"web\" { source = \"../modules/web\" ; environment = var.environment }", color: "amber" },
          { label: "3. read outputs", detail: "module.web.web_url — compose modules like a typed API", color: "violet" },
          { label: "4. avoid cross-module reach ", detail: "modules should not reach into each other's internals — outputs only", color: "rose" },
        ],
      }, "Modules as composable functions"),
      scenario({
        heading: "Case study: the accidental prod deployment",
        text: "A team's CI injected environment names through a TF_VAR_environment set by a shared bash function. Someone refactored the function and removed the export — silently. The next deploy ran with the default 'dev', and the job that was supposed to patch staging applied to… staging, fine. But weeks later, a 'prod' job ran without the variable and applied a DEV-sized instance in prod. Detecting it took a cost alert. The fix: no defaults for environment, validation that contains([dev,stage,prod]), and pipeline guard that refuses prod without an explicit approval token. Mandatory inputs turn silent assumptions into loud failures.",
      }, "Real-world postmortem"),
      quiz([
        { question: "Which input source has the HIGHEST precedence?", options: ["Default", "terraform.tfvars", "TF_VAR_ environment variable", "CLI -var flag"], answer: 3, explain: "explicit -var flags win over env vars, tfvars files, and defaults — in that order." },
        { question: "What does `sensitive = true` do?", options: ["Encrypts the state", "Redacts the value in plans and outputs", "Prevents changes", "Enables logging"], answer: 1, explain: "Sensitive values are masked in plan output, CLI and logs — the secret still reaches the API where it must." },
        { question: "When should you use a local instead of a variable?", options: ["When callers need to override it", "For derived values no caller should set", "For secrets", "For module outputs"], answer: 1, explain: "Locals are internal derived values — caller-overridable only through variables they feed into." },
      ], "Check yourself: variables"),
      recap({
        points: [
          "Variables are the public API; locals are internal derivation; outputs are the return values",
          "Precedence: -var > TF_VAR_ > tfvars > default — override silently and you'll be found out",
          "Validate variable domains with conditions; mark secrets sensitive",
          "Env-injected values must be mandatory (no default) where wrong values are dangerous",
          "One config + variables = dev, stage and prod from the same reviewed code",
        ],
      }),
    ],
  },
  {
    lessonId: "les-tf-3-1",
    lessonTitle: "Creating Modules",
    scenes: [
      title({
        eyebrow: "Module 2 · Language",
        heading: "Creating Modules",
        sub: "The composition unit of Terraform: inputs, outputs, versioning, and the registry",
        goals: [
          "Structure a module: variables, resources, outputs, README",
          "Compose modules hierarchically without reaching inside them",
          "Version modules like libraries — semver tags, changelogs",
          "Reuse modules across teams and environments safely",
        ],
        accent: "teal",
      }),
      keyterms([
        { term: "Module", definition: "A self-contained folder of .tf files with a contract of variables and outputs.", color: "lime" },
        { term: "Root module", definition: "The top-level config you run terraform apply from — everything else is called by it.", color: "sky" },
        { term: "Registry", definition: "Terraform's public and private module repositories — versioned, documented dependencies.", color: "amber" },
        { term: "Dependency graph", definition: "Terraform's DAG over resources — parallel where safe, ordered where needed.", color: "violet" },
        { term: "Module version", definition: "A semantic version (v1.2.3) you pin to — updates are deliberate upgrades, not surprises.", color: "rose" },
      ], "Composition vocabulary"),
      diagram({
        heading: "A module hierarchy that scales",
        sub: "Leaf modules do one thing; the root composes them with values",
        rows: [
          { label: "root (environment)", detail: "calls network, web, data modules; decides sizes, names, tags", color: "sky" },
          { label: "modules/network", detail: "VPC, subnets, routes, gateways — callable by any environment", color: "lime" },
          { label: "modules/web", detail: "ASG, ALB, security groups — exposes web_url, asg_name", color: "amber" },
          { label: "modules/data", detail: "RDS + secrets — exposes db_endpoint, secrets_arn", color: "violet" },
          { label: "golden path", detail: "a team's canonical stack: network + web + data, reused everywhere", color: "rose" },
        ],
      }, "One root, small leaves, clear contracts"),
      code({
        heading: "A module with a contract",
        sub: "Like a function: typed inputs, documented outputs",
        lang: "hcl",
        codeLines: [
          "# modules/web/main.tf",
          "variable \"name_prefix\" { type = string }",
          "variable \"instance_type\" { type = string; default = \"t3.micro\" }",
          "variable \"subnet_ids\" { type = list(string) }",
          "variable \"security_groups\" { type = list(string); default = [] }",
          "",
          "resource \"aws_instance\" \"web\" {",
          "  ami                    = data.aws_ami.ubuntu.id",
          "  instance_type          = var.instance_type",
          "  vpc_security_group_ids  = concat([aws_security_group.web.id], var.security_groups)",
          "  subnet_id              = var.subnet_ids[0]",
          "  tags                   = { Name = \"${var.name_prefix}-web\" }",
          "}",
          "",
          "output \"instance_id\" { value = aws_instance.web.id }",
        ],
        captions: [
          "every external dependency is an input — modules never guess",
          "defaults only where safe; required values have no default (fail loud)",
          "outputs are the module's public API — consumers never touch internals",
          "this pattern makes modules testable in isolation",
        ],
      }, "The contract pattern"),
      steps({
        heading: "Authoring a module people trust",
        sub: "Your future self is the main consumer — write for them",
        steps: [
          { label: "1. one responsibility", detail: "a module that does 'web + db + cache' is a monolith in module form", color: "sky" },
          { label: "2. document", detail: "README with inputs, outputs, examples — the registry style", color: "amber" },
          { label: "3. version it", detail: "git tag v1.2.3 + changelog; consumers pin ~> 1.2", color: "violet" },
          { label: "4. test it", detail: "terratest or at least a plan check in CI for every module change", color: "rose" },
          { label: "5. mark deprecated", detail: "when it's superseded, say so — silence is how drift starts", color: "lime" },
        ],
      }, "Library discipline, applied to infrastructure"),
      compare({
        heading: "Roll your own vs the registry",
        left: { label: "Own modules", points: ["Your exact conventions", "You maintain tests/docs/versions", "Good for org-specific stacks"], verdict: "once teams > 3", color: "lime" },
        right: { label: "Registry modules", points: ["Community-reviewed, tested", "Versioned upgrades, docs, examples", "Vet supply-chain: is it maintained? who owns it?"], verdict: "start here, own later", color: "violet" },
      }, "Both are legitimate — know which phase you're in"),
      bullets({
        heading: "Module mistakes with real costs",
        items: [
          { text: "A module used by 12 environments changed its output names — all 12 plans broke simultaneously", kind: "bad", note: "outputs are a contract: version them" },
          { text: "A 'vpc' module grew VPC + app + CI into one folder — every team got everything", kind: "bad", note: "one responsibility per module" },
          { text: "Module pulled from git @ main with no pin: its author's commit broke prod next week", kind: "bad", note: "pin versions or tags, upgrade deliberately" },
          { text: "Two modules both creating a security group with the same name — collision at apply", kind: "bad", note: "prefix resources with the module/name context" },
        ],
      }, "Borrow these stories before they're yours"),
      scenario({
        heading: "Case study: the module that became a monolith",
        text: "A platform team's 'service' module originally launched a VM + load balancer. Over two years it accreted database, cache, queues, cron and feature flags — every new service inherited all of it, and single-team PRs touched everyone's infrastructure. Deploys grew correlated: one module change broke four unrelated services in the same window. The refactor split the module by responsibility and introduced composite 'golden path' modules that merely COMPOSED the small ones. Services could now opt into pieces, and blast radius dropped from 'all services' to 'the services that share this leaf'.",
      }, "Real-world postmortem"),
      quiz([
        { question: "What is a module's public API?", options: ["Its resource names", "Its variables and outputs", "Its README", "Its git history"], answer: 1, explain: "Consumers interact through declared inputs and published outputs — everything else is internal." },
        { question: "How should you consume a shared module?", options: ["Pinned to a version/tag, upgraded deliberately", "Track main at HEAD", "Copy the folder", "Re-create it per project"], answer: 0, explain: "Version pins make upgrades deliberate events with changelogs — not silent main-branch surprises." },
        { question: "What's the fix for a module that does web + DB + cache?", options: ["Keep it — one module is simpler", "Split by responsibility, compose via a golden path module", "Duplicate it per service", "Move it to the registry"], answer: 1, explain: "Small single-purpose leaves + composed stacks keep blast radius small and testing real." },
      ], "Check yourself: modules"),
      recap({
        points: [
          "Modules are functions: typed inputs, documented outputs, one responsibility",
          "Compose small leaves; the root wires values — never reach into internals",
          "Version modules like libraries: semver tags, changelogs, pinned consumption",
          "Test module changes before merging, in their own environment",
          "Registry modules to start; own modules once conventions matter",
        ],
      }),
    ],
  },
  {
    lessonId: "les-tf-4-1",
    lessonTitle: "Remote State with S3",
    scenes: [
      title({
        eyebrow: "Module 3 · State & Collaboration",
        heading: "Remote State with S3",
        sub: "Why local state is a single-player game, and the locking pattern that makes teams safe",
        goals: [
          "Explain state's role and the failure modes of local state",
          "Configure an S3 backend with DynamoDB locking",
          "Understand state isolation per environment",
          "Handle secrets in state and protect state files",
        ],
        accent: "teal",
      }),
      keyterms([
        { term: "Backend", definition: "Where state lives — local file, S3, or Terraform Cloud. Remote = collaboration.", color: "lime" },
        { term: "Locking", definition: "A DynamoDB item that prevents two applies racing on the same state.", color: "amber" },
        { term: "State isolation", definition: "Separate state per environment so prod applies never see dev's plan.", color: "violet" },
        { term: "State secrets", definition: "State contains real outputs — passwords, IPs. Protection is mandatory, not nice-to-have.", color: "rose" },
        { term: "terraform import", definition: "Adopting click-built resources into state so code can manage them.", color: "sky" },
      ], "The words of state management"),
      diagram({
        heading: "The collaborative state pattern",
        sub: "This is what every serious Terraform setup looks like",
        rows: [
          { label: "Terraform apply (CI / laptop)", detail: "reads state → plans → acquires lock → applies → releases lock", color: "sky" },
          { label: "S3 bucket (state)", detail: "versioned, server-side encrypted, block-public-access ON", color: "lime" },
          { label: "DynamoDB (lock table)", detail: "one item per in-flight apply — the concurrency guard", color: "amber" },
          { label: "Environment separation", detail: "dev.state, stage.state, prod.state — never shared in one file", color: "violet" },
          { label: "Backup/version history", detail: "S3 versioning = time travel for your infrastructure", color: "rose" },
        ],
      }, "The architecture of safe collaboration"),
      code({
        heading: "The backend block that makes teams safe",
        sub: "Ten lines at the top of the root config — then state is remote forever",
        lang: "hcl",
        codeLines: [
          "terraform {",
          "  backend \"s3\" {",
          "    bucket         = \"acme-tfstate\"",
          "    key            = \"envs/prod/network.tfstate\"",
          "    region         = \"us-east-1\"",
          "    encrypt        = true",
          "    dynamodb_table = \"tfstate-lock\"",
          "    # separate key per environment AND per component",
          "  }",
          "}",
          "",
          "resource \"aws_dynamodb_table\" \"tfstate_lock\" {",
          "  name         = \"tfstate-lock\"",
          "  billing_mode = \"PAY_PER_REQUEST\"",
          "  hash_key     = \"LockID\"",
          "  attribute { name = \"LockID\"; type = \"S\" }",
          "}",
        ],
        captions: [
          "key = env + component → each environment is fully isolated",
          "dynamodb_table turns on advisory locking — two applies can't interleave",
          "encrypt=true + a KMS key for the bucket protects the secrets inside state",
          "the lock table itself is defined in code — bootstrapped once, then self-managed",
        ],
      }, "The exact pattern"),
      steps({
        heading: "Bootstrapping remote state, safely",
        sub: "The chicken-and-egg is real; the sequence matters",
        steps: [
          { label: "1. create bucket + lock table", detail: "one tiny bootstrap config, applied once, with local state by hand", color: "sky" },
          { label: "2. add the backend block", detail: "terraform init -reconfigure to migrate the local state file up", color: "amber" },
          { label: "3. verify", detail: "terraform state list works; the S3 object exists and is versioned", color: "lime" },
          { label: "4. protect", detail: "versioning ON, block public access ON, KMS encryption, lifecycle to expire old", color: "violet" },
          { label: "5. standardise", detail: "one module/pattern per component so the whole company matches", color: "rose" },
        ],
      }, "Once per account; thereafter, routine"),
      bullets({
        heading: "State disasters and their causes",
        items: [
          { text: "Two engineers applied the same local state simultaneously — half-provisioned resources, corrupted file", kind: "bad", note: "no lock, no remote state" },
          { text: "Prod state in a public repo by mistake — the plan output contained RDS ARNs and IPs", kind: "bad", note: "block public access, never git secrets" },
          { text: "A state file deleted 'to start fresh' — Terraform forgot everything; orphaned AWS resources kept billing", kind: "bad", note: "state removal ≠ resource removal; destroy first" },
          { text: "State drift from console edits — next plan proposed destroying the console-created resource", kind: "bad", note: "terraform import, or delete-then-adopt deliberately" },
        ],
      }, "Each pattern is a person I've met"),
      scenario({
        heading: "Case study: the two-applier incident",
        text: "A platform team of six used local state in a shared folder on one engineer's machine. Two engineers applied VPC changes at the same moment; the state file corrupted mid-write — one copy on each disk, diverged, and half the VPC existed in neither. Recovery was a weekend: importing 40+ resources, reconciling the drift by hand. The team's fix was the pattern above — S3 backend + DynamoDB lock + versioning + per-environment keys — applied in a single afternoon, and terraform state rm became a reviewed ceremony rather than a habit. Distributed systems problems need distributed-system answers.",
      }, "Real-world postmortem"),
      quiz([
        { question: "What stops two Terraform applies from corrupting shared state?", options: ["git", "The S3 key", "DynamoDB locking", "A VPN"], answer: 2, explain: "The lock table holds one item per in-flight apply; a second apply fails fast instead of racing." },
        { question: "Why separate state per environment?", options: ["It's prettier", "Prod plans must never be contaminated by dev resources", "S3 charges per file", "Terraform requires it"], answer: 1, explain: "Isolated state keeps each environment's diff clean and its destroys scoped." },
        { question: "A console-created resource you want in Terraform should be…", options: ["Recreated in code, deleted manually", "Adopted with terraform import", "Ignored — drift is fine", "Duplicated in state by hand-editing"], answer: 1, explain: "Import brings the real resource under code's management without downtime or double-creation." },
      ], "Check yourself: remote state"),
      stat({
        heading: "State safety by the numbers",
        stats: [
          { value: "1", label: "lock table can be bootstrapped and forgotten", color: "lime" },
          { value: "3", label: "protections on the state bucket: version, encrypt, block-public", color: "amber" },
          { value: "0", label: "legitimate reasons for a prod state file in a public repo", color: "rose" },
        ],
      }, "Boring to set up, priceless in an incident"),
      recap({
        points: [
          "Remote state is collaboration; local state is a single-player save file",
          "S3 backend + DynamoDB lock + versioning = safe, concurrent, recoverable",
          "Isolate state per environment and per component — clean diffs, scoped destroys",
          "State holds secrets: encrypt, block public access, version, expire",
          "Console-built resources get imported into code management, not half-copied",
        ],
      }),
    ],
  },
];